### ISSUE TITLE
Broken anchor link on /install/linux/docker-ce/debian page

### ISSUE THREAD

**Issue by davidnuzik** [docker/docker.github.io#10001]
File: [install/linux/docker-ce/debian.md](https://docs.docker.com/install/linux/docker-ce/debian/)

The **Docker variants** link ( https://docs.docker.com/install/#docker-variants ) seems to be broken. It will take you to the /install page but there is no docker-variants header or section to link to so the anchor does not work.

![image](https://user-images.githubusercontent.com/45179589/70558075-66d0b700-1b41-11ea-9752-49a43289db8f.png)

"different Docker editions" makes me think of something else besides official docker-ee or docker-ce if by this phrase we meant different builds (nightly for example, etc) then perhaps the wording here should be changed / updated. My guess is this was an old link with anchor and it's either no longer needed or this section should be updated.

**Comment by usha-mandya** [comment]
@davidnuzik Thanks for the feedback. The page https://docs.docker.com/get-docker/ describes the supported platforms you can now run Docker on. If you are looking for Docker Enterprise, please refer to the Mirantis documentation as Docker Enterprise is now part of Mirantis.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
