### ISSUE TITLE
Error: error contacting notary server: tls: oversized record received with length 20527

### ISSUE THREAD

**Issue by Sandhya131** [docker/docker.github.io#10087]
**Description:**
I'm getting this error when I try to connect with private docker repositories from my server 
" Error: error contacting notary server: tls: oversized record received with length 20527 "

I have added the private in the Insecure repositories in the server in /etc/docker/daemon.json file . I was able to connect to the repo earlier but suddenly started facing this issue. 

### Problem location
Server belongs to a kubernetes cluster

**Docker Version output -**
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false

Server details:
Ubuntu 16.04.3

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
