### ISSUE TITLE
trust_sandbox.md: Certificates in the content trust sandbox has been expired.

### ISSUE THREAD

**Issue by nonylene** [docker/docker.github.io#10085]
File: [engine/security/trust/trust_sandbox.md](https://docs.docker.com/engine/security/trust/trust_sandbox/)

When I have pushed to a sandbox register with following the `Test some trust operations` section, I got a certificate error.

```
/ # docker push sandboxregistry:5000/test/trusttest:latest
The push refers to repository [sandboxregistry:5000/test/trusttest]
5f70bf18a086: Layer already exists
c22f7bc058a9: Layer already exists
latest: digest: sha256:7034d197b82fcb07299fda8b05c91d1601ce64f31bc102b1345d03a2953d210a size: 734
Signing and pushing trust metadata
Error: error contacting notary server: x509: certificate has expired or is not yet valid
```

Certificates for the sandbox Notary server seems to be expired now.

```
/ # openssl x509 -in /notarycerts/notary-signer.crt -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            f9:47:61:9c:e9:d5:d6:87
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, ST = CA, L = San Francisco, O = Docker, CN = Notary Intermediate Testing CA
        Validity
            Not Before: Feb 17 00:43:17 2017 GMT
            Not After : Mar  9 00:43:17 2019 GMT <<< Expired!
...
```

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
