### ISSUE TITLE
/etc/docker/daemon.json is now named /etc/docker/key.json

### ISSUE THREAD

**Issue by khennicb** [docker/docker.github.io#10138]
File: [config/daemon/ipv6.md](https://docs.docker.com/config/daemon/ipv6/)

Current sentence : 
Edit /etc/docker/daemon.json and set the ipv6 key to true

Should be :
Edit /etc/docker/key.json and set the ipv6 key to true

**Comment by jangrewe** [comment]
@khennicb  No, it should not. Those are completely different files with completely different purposes. Please remove/update your comment before somebody catches a footbullet.

**Comment by khennicb** [comment]
It's not that I don't trust your words @jangrewe 
But do you know where I can read about the purpose of each of those two files ?

**Comment by jangrewe** [comment]
Well, it's kinda obvious from the filename that one is for the configuration for the daemon, and the other contains a key.
There's no official documentation about it, AFAIK, but that's also because it's a file that nobody should ever need to touch, if he doesn't know that he's doing - or in other words: the exact *opposite* of a config file.

Here's some background info, though: https://github.com/moby/moby/issues/7667

**Comment by khennicb** [comment]
Alright, I see

> How did you even come to the conclusion that this is now the new name of the file? Just because it exists and contains some JSON? I think the Docker docs mention everywhere that you have to create the file yourself, if it doesn't exist yet.

Yea, most likely.   
It was a year ago, I don't remember

**Comment by khennicb** [comment]
thanks for replying to my old issue :)
