### ISSUE TITLE
Feedback for: docker-cloud/installing-cli.md

### ISSUE THREAD

**Issue by Downes** [docker/docker.github.io#1013]
File: [docker-cloud/installing-cli.md](https://docs.docker.com/docker-cloud/installing-cli/)

On the previous page in the docs, it says having a running instance of docker on the local machine is optional.

However, on this page it says "First, you should log in using the docker CLI and the docker login command." which makes it look like it is *not* optional.

Maybe the export DOCKERCLOUD_USER command would help here? I don't know.

**Comment by sanscontext** [comment]
Hey @Downes thanks for your feedback. The page you've linked to is a standalone page and isn't part of a tutorial. Originally the tutorials used the `docker-cloud login` command, but since we've centralized our accounts this is now part of the `docker login` command. I'm checking with the team to see what updates I should make to clarify here.
