### ISSUE TITLE
no caching for lines inside requirements.txt

### ISSUE THREAD

**Issue by hiddenslave** [docker/docker.github.io#10153]
Our development involves rebuilding container multiple times. Since docker is not able to cache contents of requirements.txt , all pip packages are reinstalled for any modifications in requirements.txt.
Is there already a solution for this issue ?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. For feature requests, please use https://github.com/moby/moby
If you have a Docker subscription, please ask help from your support contact. Otherwise, you can try to get support from the Docker Community Slack or Forums:
- https://dockercommunity.slack.com/
- https://forums.docker.com/
