### ISSUE TITLE
Contents are no longer exists on this site https://docs.docker.com/v17.12/docker-for-windows/

### ISSUE THREAD

**Issue by Aakanksha-Mane** [docker/docker.github.io#10372]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by usha-mandya** [comment]
Hello @Aakanksha-Mane Thanks for your feedback. We recommend that you upgrade to the latest version of Docker Desktop. Our latest Docker Desktop for Windows docs are at https://docs.docker.com/docker-for-windows/. 
I'm closing this issue because Docker Desktop is not supported on v17.12. Please feel free to reopen this issue with more information if I've misunderstood. Thanks.
