### ISSUE TITLE
Is there a plan to solve the time synchronization limitation with win10 ?

### ISSUE THREAD

**Issue by fbeve** [docker/docker.github.io#10371]
File: [docker-for-windows/release-notes.md](https://docs.docker.com/docker-for-windows/release-notes/)

This is a known issue in latest stable release: 

"In some cases, Docker containers do not synchronize time with the host when the host machine is put to sleep."

https://docs.docker.com/docker-for-windows/release-notes/

I'd like to know when this will be solved. as The only valid solution found is to reboot my laptop everyday...
(I've already tried severaly trick recommended for this issue)

**Comment by usha-mandya** [comment]
@fbeve The fix is being worked on and it may land in the upcoming Stable release. 

I'm closing this issue as this is a Github repository for Docker documentation. 
Please file any future issues related to Docker Desktop in https://github.com/docker/for-win/ or https://github.com/docker/for-mac/ GitHub repositories. Thank you.

**Comment by usha-mandya** [comment]
@fbeve There is an internal build with the fix. You can find more information on the for-win issue https://github.com/docker/for-win/issues/4526#issuecomment-596636570.

Hope this helps!
