### ISSUE TITLE
Need to change the command to match the output

### ISSUE THREAD

**Issue by YashwanthKumarJ** [docker/docker.github.io#10426]
File: [engine/swarm/swarm-tutorial/inspect-service.md](https://docs.docker.com/engine/swarm/swarm-tutorial/inspect-service/)

docker service inspect --pretty helloworld command and its output isn't correct. Remove the --pretty in the command. The --pretty command json output is mentioned in the subsequent section

**Comment by thaJeztah** [comment]
Thanks for reporting, but I don't see a mistake on that page; it describes:

> Run `docker service inspect --pretty <SERVICE-ID>` to display the details about a service in an easily readable format.

(followed by an example of the "pretty" output), then:

> Tip: To return the service details in json format, run the same command without the `--pretty flag`.

followed by an example of the JSON output format



I'm closing this issue, because of the above, but feel free to continue the conversation in case I didn't understand your report
