### ISSUE TITLE
Not documented: Restore containers on crashed node in Swarm

### ISSUE THREAD

**Issue by MathiasRenner** [docker/docker.github.io#105]
I could not find the docs in `engine/swarm/admin_guide.md` for this scenario:

I am looking for a command that allows me to restore the containers to a node that had crashed and is now back up and running.
This node does not get the previous containers be default - how can I trigger this?

**Comment by mstanleyjones** [comment]
Hi, and thanks for your feedback. The swarm is not rebalanced when a new node is added. When your node rejoined the swarm, its container assignments were discarded, and the restored node is effectively a new node. To rebalance, you can [update](https://docs.docker.com/engine/reference/commandline/service_update/) or [scale](https://docs.docker.com/engine/reference/commandline/service_scale/) the service.

I have filed #148 to clarify this behavior.

**Comment by mstanleyjones** [comment]
Fixed via #148.

**Comment by MathiasRenner** [comment]
@mstanleyjones @thaJeztah @aaronlehmann  Thanks for updating the docs, but the hint you added to the docs via https://github.com/docker/docker.github.io/pull/148 does not help me.

You recommend to use `update` or `scale` the service in order to force rebalancing the swarm. And how exactly? I could not find any command line parameter for any of the two commands that helps for this scenario...

**Comment by mstanleyjones** [comment]
The commands you want are [`docker service update`](https://docs.docker.com/engine/reference/commandline/service_update/) or [`docker service scale`](https://docs.docker.com/engine/reference/commandline/service_scale/). My fix in #148 includes links to each of these.

In the case of scaling, the easiest thing to do would be to scale up or down. For instance, if you do `docker service ls` and see that your current scale is 50, you might scale to 51 by doing `docker service scale myservice=51`. You could set it back to 50 afterward. **When scaling a service, preference is given to under-loaded nodes.** It's always possible that other nodes are under-loaded as well, so just scaling up by 1 might not do it. You might need to scale up by small increments a few times until you get the workload balance you want on the new node, and then scale back down to the scale you really want.

In the case of `service update`, not all of the update commands will rebalance your service, after all. I'm going to do a follow-on update to clarify this in the docs.

This all sounds very roundabout, but that's because micro-managing your swarm is not usually necessary. Your swarm will manage itself over the long term and ensure that the correct number of containers are running. If you feel strongly that more balancing-related features should be added, please consider submitting a feature request for this in the `docker/docker` repository.

I'll ping this issue when the follow-on pull request is ready for review.

**Comment by mstanleyjones** [comment]
@MathiasRenner Please take a look at PR #178 and see if that helps clarify this for you.

**Comment by mstanleyjones** [comment]
Fixed by #148 and #178

**Comment by MathiasRenner** [comment]
@mstanleyjones Sorry for the late respone. And thanks for your specific description in the docs, awesome!

Meanwhile, this PR https://github.com/docker/swarmkit/pull/1664 provides the functionality I was looking for, so you probably can update the docs again :D

**Comment by mstanleyjones** [comment]
Sure, when it gets into a release. :)
