### ISSUE TITLE
docker for aws

### ISSUE THREAD

**Issue by kristofrk** [docker/docker.github.io#10501]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by kristofrk** [comment]
I could not access the Docker for AWS documentation. I searched in Docker docs, followed the link and got an error message for  https://docs.docker.com/docker-for-aws/

**Comment by NorthwoodsTechExploratory** [comment]
I am experiencing exactly the same problem as @kristofrk . Any update from Docker or from others with information about this matter is welcome. Thanks.

**Comment by groja** [comment]
I've also run into this. I assume it's because of this pull request https://github.com/docker/docker.github.io/pull/10487 which "removed obsolete products".

It may be true that the overall docker-for-aws and docker-for-azure products no longer exist, but the cloudstor plugin is still available for independent installation from https://hub.docker.com/r/docker4x/cloudstor/tags (including CE versions) and this was the only real place it was documented. It would be good to understand if this means that the plugin is being retired or end-of-lifed because some people are using it!

**Comment by cliftbar** [comment]
Agreed, would like to know if there's a different place to find documentation and if the cloudstor plugin is going to be taken down anytime soon.  Also, whats the appropriate alternative? because i'm using this and will need to figure out moving off if its dead (for the record, it was very convenient).

Also, for those looking for docs, wayback machine link https://web.archive.org/web/2019*/https://docs.docker.com/docker-for-aws/deploy/

**Comment by zeferino90** [comment]
Hi, same here, those templates where the easiest way to deploy a swarm on aws. A moments ago I downloaded all the templates from the archive.

CE (Stable)
18.03.0
http://editions-us-east-1.s3.amazonaws.com/aws/stable/18.03.0/Docker.tmpl

EE
17.06.2
Docker EE Basic: https://editions-us-east-1.s3.amazonaws.com/aws/17.06/17.06.2/Docker-EE.tmpl
Docker EE Standard and Advanced: https://editions-us-east-1.s3.amazonaws.com/aws/17.06/17.06.2/Docker-DDC.tmpl
17.03.2
https://editions-us-east-1.s3.amazonaws.com/aws/17.03/17.03.2/Docker.tmpl

Thanks @cliftbar
