### ISSUE TITLE
docker service ps output doesn't match description

### ISSUE THREAD

**Issue by Gmikeit** [docker/docker.github.io#10608]
File: [engine/swarm/how-swarm-mode-works/swarm-task-states.md](https://docs.docker.com/engine/swarm/how-swarm-mode-works/swarm-task-states/)

At the bottom of the page there is the output of docker service ps.
The paragraph accompanying the output says

> The CURRENT STATE field shows the task’s state and how long it’s been there.

But the output column heading is DESIRED STATE.
Shouldn't the output show CURRENT STATE if you are referring to it in the text?

**Comment by thaJeztah** [comment]
The `CURRENT STATE` column is in the example output, but the output is quite wide, so you may have to scroll horizontally;

<img width="929" alt="Screenshot 2020-04-30 at 01 39 22" src="https://user-images.githubusercontent.com/1804568/80657292-83837200-8a83-11ea-8627-684fa7729055.png">


I'll open a PR to reduce the width of the example output so that it's in view without scrolling

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker.github.io/pull/10727 with a fix
