### ISSUE TITLE
How to get around Index column size too large. The maximum column size is 767 bytes. 

### ISSUE THREAD

**Issue by andrewtrecha** [docker/docker.github.io#10605]
Receive error message on WordPress column size when trying to import db from production to local.

Are there any config settings I can change to allow the import to happen?\

Using docksal with docker.

**Comment by thaJeztah** [comment]
This sounds like an issue with WordPress, not docker.

Please keep in mind that this GitHub issue tracker is for reporting bugs/issues with the documentation, and not intended [as a general support forum](https://raw.githubusercontent.com/docker/docker.github.io/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)
- StackOverflow (https://stackoverflow.com)

I'm closing this issue because this is not related to the documentation, but feel free to comment after I closed
