### ISSUE TITLE
Feedback for: engine/installation/linux/ubuntulinux.md

### ISSUE THREAD

**Issue by RichardJECooke** [docker/docker.github.io#1063]
File: [engine/installation/linux/ubuntulinux.md](https://docs.docker.com/engine/installation/linux/ubuntulinux/)

Your `Uninstallation` section does not work. I type in the commands and then I type `docker -v` and it still shows me 1.12

**Comment by mstanleyjones** [comment]
Thanks for the report. Are you sure that the `docker` executable you have is not coming from a different Docker that wasn't supplied by Docker.com? There is a version of Docker in the Ubuntu repository with the package name `docker` instead of `docker-engine`. To see where your file comes from, you can do `which docker` and then `apt-file search <path/to/docker>`.

In addition, the installation and uninstallation instructions have been rewritten and reorganized. Please have a look at https://docs.docker.com/engine/installation/linux/ubuntu/#/uninstall-docker.

**Comment by RichardJECooke** [comment]
Sorry, I forgot where I put this issue. I think I might have installed through LinuxBrew. Closing this.
