### ISSUE TITLE
Link to download file is not found (404)

### ISSUE THREAD

**Issue by jeffstevens98** [docker/docker.github.io#10641]
File: [engine/install/centos.md](https://docs.docker.com/engine/install/centos/)

My class ran through this tutorial as a group and found that when we attempted to install Docker onto our raspberry pis running centOS that the download link lead to a 404 error.

**Comment by usha-mandya** [comment]
Hello @jeffstevens98, apologies for the inconvenience caused to you and your group. The CentOS download link works fine for me. Could you give this a try again and let me know if you are still experiencing any issues? Thanks.

**Comment by thaJeztah** [comment]
This is expected, because we currently don't provide packages for CentOS on Raspberry Pi (arm32) platforms, only on arm64; https://docs.docker.com/engine/install/

<img width="881" alt="Screenshot 2020-04-24 at 13 55 39" src="https://user-images.githubusercontent.com/1804568/80210077-6722a800-8633-11ea-9af2-c315e6740f7d.png">

Let me close this issue, but feel free to continue the conversation
