### ISSUE TITLE
Installation on Mint is misleading

### ISSUE THREAD

**Issue by ngaro** [docker/docker.github.io#10656]
File: [engine/install/index.md](https://docs.docker.com/engine/install/)

It mentions _Users of Debian derivatives such as “BunsenLabs Linux”, “Kali Linux” or “Linux Mint” should follow the installation instructions for Debian_ .
This is only correct if one would describe "LMDE" (Debian-based Mint) as "Mint". LMDE is by far the least used version of Mint. The most used versions of Mint are all based on Ubuntu, but Mint isn't mentioned among the Ubuntu derivatives.

I would suggest using the wording:

- _Users of Debian derivatives such as “BunsenLabs Linux”, “Kali Linux” or “LMDE” should follow the installation instructions for Debian_
- _Likewise, users of Ubuntu derivatives such as “Kubuntu”, “Lubuntu”, “Xubuntu” or "Linux Mint" should follow the installation instructions for Ubuntu_

**Comment by thaJeztah** [comment]
Thanks for reporting; I'm not too familiar with all derivatives. The intent was to at least mention some distro's that people could be running, but which we don't officially support (at least, don't test/verify on). We frequently received pull requests to add those to our installation instructions, but because (as mentioned) we don't support/test those we try to avoid that, so instead give some "pointers" what _could_ work for those.

I'll update the page to change it to `"LMDE" (Debian-based Mint)`

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker.github.io/pull/10696
