### ISSUE TITLE
Debian install instructions bug

### ISSUE THREAD

**Issue by greyltc** [docker/docker.github.io#10677]
Follwing this guide to install on debian jesse:

File: [engine/install/debian.md](https://docs.docker.com/engine/install/debian/)

Says to run
```
$ sudo apt-get install docker-ce docker-ce-cli containerd.io
```
but the result there is:
```
E: Unable to locate package docker-ce-cli
```

Looks like `docker-ce-cli` does not exist in jesse stable repo?

**Comment by greyltc** [comment]
Also, maybe the libseccomp2 version requirement is bad?
```
$ sudo apt-get install docker-ce containerd.io libseccomp2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 containerd.io : Depends: libseccomp2 (>= 2.3.0) but 2.1.1-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by thaJeztah** [comment]
Debian Jesse is no longer supported; https://docs.docker.com/engine/install/debian/#os-requirements. Docker requires Debian 9 (stretch) or Debian 10 (buster)

Also make sure to add the download.docker.com repository to your apt configuration, as outlined in the [set up the repository](https://docs.docker.com/engine/install/debian/#install-using-the-repository) step.

I'm closing this issue because of the above, but feel free to continue the conversation
