### ISSUE TITLE
the download page for windows is broken

### ISSUE THREAD

**Issue by nmagen** [docker/docker.github.io#10697]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by thaJeztah** [comment]
You didn't provide the link that was broken, but I suspect this was related to https://github.com/docker/docker.github.io/pull/10691

should be fixed by https://github.com/docker/docker.github.io/pull/10691 (which will be published on docs.docker.com soon)

Meanwhile, the correct URL is https://docs.docker.com/docker-for-windows/install/
