### ISSUE TITLE
how to make a real operation system be an Docker image

### ISSUE THREAD

**Issue by tangmaomao16** [docker/docker.github.io#10709]
### how to make a real operation system be an Docker image
In the past time, I didn't learn much knowledge of Docker. I started my coding on Ubuntu 1804 operation system, and I downloaded many software.
Now I need to migrate into another machine Ubuntu 1604, and there is Docker software on that.
So I want to make a real operation system, my Ubuntu 1804, be an Docker image; and then I can run the Docker container on other machine such as the Ubuntu 1604. How to do this? Or how to most easily migrate from one machine to another machine?

**Comment by thaJeztah** [comment]
Please keep in mind that this GitHub issue tracker is for reporting bugs/issues with the documentation, and not intended [as a general support forum](https://raw.githubusercontent.com/docker/docker.github.io/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)
- StackOverflow (https://stackoverflow.com)

I'm closing this issue because this is not related to the documentation, but feel free to comment after I closed
