### ISSUE TITLE
URL to install docker on Ubuntu 14.04 LTS no longer exists

### ISSUE THREAD

**Issue by dheerajmpai** [docker/docker.github.io#10921]
### Problem description

[This page](https://docs.docker.com/ee/docker-ee/ubuntu/), the enterprise version, has a link to [this page](https://docs.docker.com/engine/install/ubuntu.md) (The community version doc) . But the link does not exist. Returns 404.

### Problem location

- I saw a problem on the following URLs: https://docs.docker.com/ee/docker-ee/ubuntu/, https://docs.docker.com/engine/install/ubuntu.md

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/engine/install/ubuntu.md

### Suggestions for a fix

Add the documentation that previously existed. Or correct the link

**Comment by thaJeztah** [comment]
The enterprise docs are now located on the Mirantis website, but you're likely looking for this page; https://docs.docker.com/engine/install/ubuntu/

Note however that Ubuntu 14.04 reached EOL, and is no longer supported by Docker. Ubuntu 14.04 installs (because they're EOL) no longer receive security updates, so I highly recommend upgrading your system as you may be running with unpatched security vulnerabilities
