### ISSUE TITLE
Metrics address is not working with 127.0.0.1

### ISSUE THREAD

**Issue by shazforiot** [docker/docker.github.io#11007]
File: [config/daemon/index.md](https://docs.docker.com/config/daemon/)

Hello Team,

When I added the below json in to daemon.json. metrics is not working

{
  "metrics-addr" : "127.0.0.1:9323",
  "experimental" : true
}

I had to change the 127.0.0.1 to 0.0.0.0 to have it working. Can you check if this need to be updated here?

{
  "metrics-addr" : "0.0.0.0:9323",
  "experimental" : true
}

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. I don't see that info in that topic. As this issue is old, some context may have changed. It is located in https://docs.docker.com/config/daemon/prometheus/ and https://docs.docker.com/engine/reference/commandline/dockerd/#miscellaneous-options
There is another ticket for with that info. Closing this in favor of https://github.com/docker/docker.github.io/issues/13010
