### ISSUE TITLE
Docker captures container log garbled

### ISSUE THREAD

**Issue by my1990** [docker/docker.github.io#11015]
The internal Chinese of the container is displayed normally, but the external view of the container is garbled? Why is that? The server code has been set consistently
![1111100618212640](https://user-images.githubusercontent.com/16768690/85025952-a3453580-b1aa-11ea-8834-cd9dfe80880b.png)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.  If the issue is still applicable and you believe it is a bug, please help create an issue in the appropriate repo, https://github.com/moby/moby for engine or https://github.com/docker/cli for CLI
If you're looking for support, you can try the Docker Community Slack or forums:
- https://dockercommunity.slack.com/
- https://forums.docker.com/
