### ISSUE TITLE
The command to pass specific gpu ids to docker run command needs gpu ids in quotes

### ISSUE THREAD

**Issue by Shreeyak** [docker/docker.github.io#11010]
File: [config/containers/resource_constraints.md](https://docs.docker.com/config/containers/resource_constraints/)

Referencing [this issue](https://github.com/NVIDIA/nvidia-docker/issues/1026) 

The below command:
`$ docker run -it --rm --gpus device=0,2 nvidia-smi`

Should be:
`$ docker run -it --rm --gpus '"device=0,2"' nvidia-smi`

I'm using `Docker version 19.03.10, build 9424aeaee9`

**Comment by paulraines68** [comment]
This is ridiculous the way --gpus arguements are parsed.

If you have a job in a batch system like SLURM with CUDA_VISIBLE_DEVICES set how are you to use it properly in a docker call?

If I have a box like the DGX A100 with 8 GPUS and get a job to use all so CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 and do

`docker run --gpus $CUDA_VISIBLE_DEVICES ...`

which is the most obvious thing to do it silently ignores all the numbers except the final "7" and gives you just 7 GPUs to use.

Because of the way the quoting works, I see no way to actually pass this properly

`docker run --gpus '"device=$CUDA_VISIBLE_DEVICES"' ...`

obviously fails since the single quotes make the variable not extrapolate.  Doing it without quotes gives you the "cannot set both Count and DeviceIDs on device request" error.  I mean what brain dead parser cannot tell from the device= string being there that this is NOT A COUNT!

So having CUDA_VISIBLE_DEVICES set to some list of the GPU IDs, how is one supposed to use this with the docker --gpus argument in a script?  Am I missing something obvious?

**Comment by paulraines68** [comment]
This is what I have resorted to:

`eval "echo docker run --gpus "'\"device=$CUDA_VISIBLE_DEVICES\"'" -it --rm --network host tf2-py3-x11"`

**Comment by moi90** [comment]
Yes, this is really annoying!

**Comment by craig-osterhout** [comment]
Fixed in https://github.com/docker/docker.github.io/commit/4f12a72ffcb658576bd6ceb65b2a4b3db3138392

**Comment by moi90** [comment]
Please reopen. The "fix" just documented this quirk. I am aware that the quotes are currently required and I would like to have the command line parsing improved so they are not.

**Comment by moi90** [comment]
Thanks for documenting this quirk!

I can only advocate fixing the actual parsing error: https://github.com/docker/cli/issues/2937

**Comment by BWBrook** [comment]
I found another, simpler solution:
docker run --env CUDA_VISIBLE_DEVICES=$g --gpus all ...

where $g can be set to the CUDA number of whatever GPU you wish to direct as your target
