### ISSUE TITLE
env.list example

### ISSUE THREAD

**Issue by aianni** [docker/docker.github.io#11026]
File: [engine/reference/commandline/run.md](https://docs.docker.com/engine/reference/commandline/run/)

I think that in env.list file the value "denis" is missing for env var "USER".
In addition "denis" could be "Denis"

Regards
Andrea

cat env.list
VAR1=value1
VAR2=value2
USER <-- here is missing the value

$ docker run --env-file env.list ubuntu env | grep VAR
VAR1=value1
VAR2=value2
USER=denis

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.  As this issue is old, some additional context may have been added to that topic. The example with no value is showing what happens when a value is not assigned.
If the issue is still applicable, please help create an issue in the upstream source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
