### ISSUE TITLE
Sorry, we can't find that page There might be a mistake in the URL ▶ or you might’ve clicked a link to content that no plus ▶ exists.  If you think it’s the latter, please file an issue at https://github.com/docker/docker.github.io and let us know what happened. Please also include a link to where the error occurred, if applicable.

### ISSUE THREAD

**Issue by jy257** [docker/docker.github.io#11099]
The command 'docker' could not be found in this WSL 1 distro.
We recommend to convert this distro to WSL 2 and activate
the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.

Why I see it?

### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by StefanScherer** [comment]
Hi @jy257,

I try to answer your question, but I maybe need more information of your setup.
You see the message

```
The command 'docker' could not be found in this WSL 1 distro.
We recommend to convert this distro to WSL 2 and activate
the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.
```

when you type `docker` in a WSL distro which is not a WSL 2 distro. Docker Desktop ships a small helper script to guide users what to do next when docker doesn't work. That's why you see it.

Docker Desktop only works within WSL 2 distros that have the WSL integration enabled in the settings.
It looks like your WSL distro is version 1. The link to our docs page https://docs.docker.com/docker-for-windows/wsl/ shows the requirements as well as the steps needed to enable the Docker integration.

Which version of Windows do you have? You could run `cmd.exe /c winver` and paste the output.
Which WSL distros do you have? You could run `wsl.exe -l -v` to list all distros including the version number.

Thanks.

**Comment by jy257** [comment]
Microsoft Windows [Version 10.0.17134.1246
