### ISSUE TITLE
Document -H/--host option

### ISSUE THREAD

**Issue by bfirsh** [docker/docker.github.io#11098]
File: [engine/reference/commandline/cli.md](https://docs.docker.com/engine/reference/commandline/cli/)

On this page, the format for `--host` is not documented. Or, if it is documented, it should be linked to from this page.

Similarly, the documentation for `context create` does not document it either. Specifically, I'm looking for how to use `ssh://` URLs. I'll keep on hunting, but I'm guessing it isn't documented anywhere.

**Comment by lfmunoz** [comment]
SSH URLs might be related to my issue:

https://github.com/docker/docker.github.io/issues/11747

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This particular content is maintained in an upstream repo with the CLI. If the issue is still applicable, please help create an issue in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
There is a little more info on the man page at https://github.com/docker/cli/blob/master/man/docker.1.md
