### ISSUE TITLE
export / import error: archive/tar: invalid tar header

### ISSUE THREAD

**Issue by buenos-dan** [docker/docker.github.io#11101]
### Problem description

I'm trying to export a docker form ubuntu18.04, and import it into jetson nano.
ubuntu18.04:  "docker export -o xxx.tar  <dockerID>"
jetson_nano: "docker import xxx.tar"
then I got the error:  "Error response from daemon: Error processing tar file(exit status 1): archive/tar: invalid tar header"

first, I use "docker export <dockerID>  > xxx.tar",    and I find some suggestions using "docker export -o xxx.tar  <dockerID>“
but it is still not work. 

why I want to transport a docker from ubuntu to jetson nano( also a linux os),   I complie a ros project succeed in ubuntu18.04's docker, and failed in jetson nano's docker. All steps are the same. this really confused me.

can any body help me? thanks.

**Comment by usha-mandya** [comment]
Hello @buenos-dan Thanks for your feedback. This doesn't look like a documentation issue. You can ask your question on the [Docker Community Slack channel](http://dockr.ly/slack) for general support from the community. I'm closing this issue here as it is not related to documentation. Feel free to add a comment if I've misunderstood your question. Thanks.
