### ISSUE TITLE
Why there is no development environment after switching users

### ISSUE THREAD

**Issue by HaoweiGis** [docker/docker.github.io#11136]
### Problem location
```
root@bd5ecd2bcafd:/workspace# python
Python 3.7.7 (default, Mar 23 2020, 22:36:06) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
[1]+  Stopped                 python
root@bd5ecd2bcafd:/workspace# su
root@bd5ecd2bcafd:/workspace# python
bash: python: command not found
```
Hope to get an answer！

**Comment by thaJeztah** [comment]
Please keep in mind that the GitHub issue tracker is for reporting issues with the documentation at docs.docker.com, and not intended as a general support forum. For other type of questions, consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- StackOverflow
- the Docker Support Forums - https://forums.docker.com

I'm closing this issue because of the above, but feel free to continue the conversation
