### ISSUE TITLE
Cannot remove images with dependencies

### ISSUE THREAD

**Issue by GusGF** [docker/docker.github.io#11132]
I've got a list of images I somehow seemed to have ended up with mysteriously which have no repo name, tag but do have an ID. When I try to delete these images this happens

`Error response from daemon: conflict: unable to delete f53f0ed3e7ea (cannot be forced) - image has dependent child images`

In quite a few places this seems to have been offered up as part of the solution:
`docker inspect --format='{{.Id}} {{.Parent}}' $(docker images --filter since=747ac7781702 -q)`

But it doesn't work for me:
```
unknown flag: --filter
See 'docker inspect --help'.
```

I don't want to obliterate all my images just the ones which are taking up space on my computer and have no identifiers apart from the image ID. Any idea how I do this?

VERSION INFO
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by GusGF** [comment]
Okay in the end I managed to get rid of these loose ends by running:
`docker system prune -a`

```
docker system prune -a
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all images without at least one container associated to them
  - all build cache

Are you sure you want to continue? [y/N] docker system prune -a
```


I'd still be interested to know why this command didn't work for me
`docker inspect --format='{{.Id}} {{.Parent}}' $(docker images --filter since=747ac7781702 -q)`

**Comment by usha-mandya** [comment]
@GusGF Thanks for your feedback. 

Could you try the `docker image prune` command to remove images? You can find the details and example usage here - https://docs.docker.com/engine/reference/commandline/image_prune/

Also, the latest Docker Desktop Edge release introduces the new **Images** view GUI that lets you see a list of images on your disk delete unwanted images to reclaim space. You can find more details about this update and a link to the Edge download on the Release notes page

- https://docs.docker.com/docker-for-mac/edge-release-notes/#docker-desktop-community-2340
- https://docs.docker.com/docker-for-windows/edge-release-notes/#docker-desktop-community-2340

If you are still experience any issues, suggest you create an issue in the https://github.com/docker/for-linux/issues repository.

**Comment by GusGF** [comment]
Thanks for the info :)

**Comment by thaJeztah** [comment]
This happens if there are images that are used as "build cache" for `docker build`. When using `docker build`, docker keeps track of images that are used as "parent" image using metadata on the image, and prevents those images from being deleted so that the build-cache is preserved.

There's a proposal I opened (https://github.com/moby/moby/issues/30722, which also has some more details on this) to allow removing these images (and thus remove the "build cache"), however, the "next generation" builder (BuildKit) does not have the same problem as it doesn't use the image store for it's cache. You can use BuildKit as builder by setting the `DOCKER_BUILDKIT=1` environment variable (more details about buildkit can be found here; https://docs.docker.com/develop/develop-images/build_enhancements/).

We're in the process of making BuildKit the default builder on Docker Desktop, but even once that's the case, using `docker system prune` (and related `docker image prune`, `docker volume prune` etc. commands) and/or the Docker Desktop images GUI will be the recommended way to remove unused resources.

**Comment by thaJeztah** [comment]
Let me go ahead and close this issue, but feel free to continue the conversation 👍
