### ISSUE TITLE
BSOD HYPERVISOR_ERROR after using Docker for windows

### ISSUE THREAD

**Issue by DialgicMew** [docker/docker.github.io#11139]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

Whenver i use docker desktop on my windows 10 insider preview the next reboot after my usage of the application causes VSOD Error on my PC. Please help

**Comment by usha-mandya** [comment]
@DialgicMew Thanks for your feedback. This looks like a product issue, rather than a documentation bug. Please use the following links to report Docker Desktop product issues: 

- https://github.com/docker/for-win/issues
- https://github.com/docker/for-mac/issues

I'm closing this issue here as it is not a documentation issue.
