### ISSUE TITLE
docker-compose --version docs outdated?

### ISSUE THREAD

**Issue by kirbygit** [docker/docker.github.io#11164]
### Problem description
![Screenshot from 2020-07-20 09-30-58](https://user-images.githubusercontent.com/20747057/87962465-1a047580-ca6c-11ea-902f-fda990099614.png)

### Problem location

- I saw a problem on the following URL: <URL>
I saw a problem on the following URL https://docs.docker.com/compose/install/
- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

### Suggestions for a fix

Update docs?
Im not sure if it outdated or not but docker compose --version fixes it on docs.

**Comment by usha-mandya** [comment]
@kirbygit That's interesting. Could you let us know how you installed Docker and if you are running Docker on Mac, could you let us know the version of macOS?

**Comment by kirbygit** [comment]
@usha-mandya  I installed docker on Ubuntu

**Comment by usha-mandya** [comment]
Thanks. Could you let me know the macOS version?

**Comment by kirbygit** [comment]
Ubuntu 18.04LTS not on mac

**Comment by usha-mandya** [comment]
@kirbygit I don't think this is a documentation issue. The command `docker-compose --version` works fine for me

![image](https://user-images.githubusercontent.com/47779042/88072069-82d31700-cb6c-11ea-9154-a4459a7c81db.png)

I'm closing this issue here as this is not related to documentation. You can create an issue in the https://github.com/docker/compose repository. However, feel free to continue the conversation here after I close.

**Comment by kirbygit** [comment]
I see its on the compose repo problem

**Comment by kirbygit** [comment]
works fine now thanks

**Comment by usha-mandya** [comment]
@kirbygit Thanks for the update!
