### ISSUE TITLE
give a working example for --format please

### ISSUE THREAD

**Issue by jnweiger** [docker/docker.github.io#11283]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

It says:
| To view an image’s labels, use the docker image inspect command. You can use the --format option to show just the labels;
| 
| docker image inspect --format='' myimage

This command does not work. There is something missing within the quotes.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue.
If you do `docker image inspect myimage`, you can see the unformatted output, and then from there you can specify the output you want to see and format, for example ` image inspect --format '{{.Config.Labels}}' myimage`

This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference
