### ISSUE TITLE
Feedback for: docker-cloud/apps/deploy-to-cloud-btn.md - Docker Button

### ISSUE THREAD

**Issue by niccokunzmann** [docker/docker.github.io#1133]
File: [docker-cloud/apps/deploy-to-cloud-btn.md](https://docs.docker.com/docker-cloud/apps/deploy-to-cloud-btn/)

When I go to the link https://cloud.docker.com/stack/deploy/?repo=https://github.com/loklak/loklak_server
I get a 404 page.
Also I get a 404, when I access the example page: https://cloud.docker.com/stack/deploy/?repo=https://github.com/docker/dockercloud-quickstart-python

Related Issue: loklak/loklak_server#1001

I would like to get a cloud deployment as mentioned in the docs.

**Comment by sanscontext** [comment]
Hi @niccokunzmann, you usually see this when you are not logged in to Docker Cloud when you click the button. (See the "Note" on the first page.)  Please confirm that you're logged in and see if it works after that? Since this isn't an issue with the documentation, I'm going to close this ticket. If you determine that there's a bug, please email support@docker.com for assistance.

**Comment by niccokunzmann** [comment]
I would rather see that I need to log in. Where do I need to go to implement this?
