### ISSUE TITLE
Getting the error "read-only file system" every time I try to build 

### ISSUE THREAD

**Issue by cdastmalchi** [docker/docker.github.io#11397]
I was having issues recently with building/pushing my docker images, so I thought updating the docker software would resolve this, but it did not appear to. Even after updating to `Docker version 19.03.12, build 48a66213fe`, any time I try to build something, I get the error:

`Error response from daemon: mkdir /var/lib/docker/tmp/docker-builder125433410: read-only file system` 

When I try re-building the same images on a virtual machine (e.g. Amazon EC2 instance), it works. And the docker version I have on the virtual machine is `Docker version 19.03.6-ce, build 369ce74`. 

Any ideas as to how I can resolve this?

**Comment by thaJeztah** [comment]
"read-only file system" can also be an indication that there's a problem with the disk. The system can out the disk in read-only mode to allow verifying and/or repairing the disk.

  
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md) related to the documentation.

For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because of the above, but feel free to continue the conversation

**Comment by cdastmalchi** [comment]
Oh gotcha! I was previously getting warnings that my disk-space is low, but I've created more space since then. If that's what is causing the issue, how would I address that?
