### ISSUE TITLE
Security Scan Information Currently Incorrect

### ISSUE THREAD

**Issue by severusdenton** [docker/docker.github.io#11478]
File: [docker-hub/official_images.md](https://docs.docker.com/docker-hub/official_images/)

This page says that security scan information is available for official images, but this does not appear to be the case,. At least not for amazoncorretto which is the official image I was trying to view scan results for today. I was logged in.

A few other people seem to have hit the same issue, and they've mentioned it on the Docker forum here:

https://forums.docker.com/t/official-image-vulnerability-scanning-is-missing-in-action/96809

It would be great if the feature could be fixed, or if the page could be updated to provide alternative instructions to view the scan results (if indeed they are reachable by another route). In the worst case, the reference to scan results should just be removed.

**Comment by thaJeztah** [comment]
Thanks for reporting; this should be fixed by https://github.com/docker/docker.github.io/pull/11555

image scanning is currently being reimplemented on Docker Hub; you may be interested in https://docs.docker.com/docker-hub/vulnerability-scanning/ and https://docs.docker.com/engine/scan/

Let me close this ticket, because the information was removed, but feel free to continue the conversation
