### ISSUE TITLE
The docs are not porting the repo to my Kali box for docker installation.

### ISSUE THREAD

**Issue by themaverick** [docker/docker.github.io#11481]
File: [engine/install/debian.md](https://docs.docker.com/engine/install/debian/)

https://medium.com/@airman604/installing-docker-in-kali-linux-2017-1-fbaa4d1447fe

This link has a working debian sources list addition. Please replicate on Kali 2020.2a

**Comment by thaJeztah** [comment]
Thanks for opening this ticket; while it may work, we don't officially support Ubuntu and Debian derivatives, such as Kali Linux. Given that we don't test docker on these distros, we don't mention them in our installation guide, but make mention of these in the "other distributions" section on this  page: https://docs.docker.com/engine/install/

Let me close this ticket because of the above, but feel free to continue the conversation
