### ISSUE TITLE
Clarify how to create config for an image manifest

### ISSUE THREAD

**Issue by goofballLogic** [docker/docker.github.io#11681]
File: [registry/spec/manifest-v2-2.md](https://docs.docker.com/registry/spec/manifest-v2-2/)

In the section about creating an image manifest it states about the required config property: 
```
The config field references a configuration object for a container, by digest. This configuration item is a JSON blob that the runtime uses to set up the container.
```
However it's not clear what this JSON blob is or should be, nor how I'm supposed to provide it to the endpoint.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the source repo at https://github.com/distribution/distribution/blob/main/docs/spec/manifest-v2-2.md
For additional support, please check https://docs.docker.com/registry/help/
