### ISSUE TITLE
Ronin-server example error

### ISSUE THREAD

**Issue by russsaidwords** [docker/docker.github.io#11778]
File: [get-started/nodejs/build-images.md](https://docs.docker.com/get-started/nodejs/build-images/)

On following this file's current steps and running `node server.js` I am getting the error: "Error: 'app.router' is deprecated!" I tried going down the rabbit hole on both the npm website and with a search of the web, but this project isn't documented anywhere.

**Comment by Colin-R** [comment]
I am also facing this issue.

**Comment by kgkars** [comment]
I was running into the same issue when doing the Docker tutorial for node; but then I realized I had made a typo.

Make sure you have Router with a capital 'R' instead of with a lowercase 'r' in line 6 of your server.js file. Once I corrected my typo, I was able to get the Docker tutorial to work without a problem.

**Comment by craig-osterhout** [comment]
@kgkars, thanks for troubleshooting and sharing the solution.
@russsaidwords, thanks for sharing the issue. As mentioned above, it looks like a transcription error. If you still experience the issue after fixing the capitalization, please let us know.
