### ISSUE TITLE
404 at /compose/install/%E2%80%A8

### ISSUE THREAD

**Issue by younesk8** [docker/docker.github.io#12176]
I found a broken link : https://docs.docker.com/compose/install/%E2%80%A8
I arrived on this page through: https://yoandev.co/

**Comment by thaJeztah** [comment]
Looks like a broken link on https://yoandev.co/ the correct URL should be https://docs.docker.com/compose/install/

If you know on what page the broken link was, I suggest reporting this to the owner of https://yoandev.co/.


I'm closing this ticket, because this is not something we can fix in our docs, but feel free to continue the conversation
