### ISSUE TITLE
What command line?

### ISSUE THREAD

**Issue by HekiShavik** [docker/docker.github.io#12199]
File: [get-started/index.md](https://docs.docker.com/get-started/)
The video mentions a command line. Nowhere is it mentioned what that command line is. It is just there all of a sudden. Please help the complete noobs a little here.

Another thing is the docker file. Where? What? How?

---

So I decided to thoroughly read the documentation instead of just glancing over it. Like carefully, word for word. It describes the docker file and what is in it, the syntax and that it basically is a text file, but no mention of where - except it in passing in [Understand build context](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#understand-build-context)
This information should be consolidated.

---

It turns out that the "Copy and paste this command into your terminal and then come back" from the Docker Desktop window actually means a PowerShell console (yes, I use Windows). What it actually means is "Copy and paste this command into your PowerShell, close this window and reopen".

---

If port 80 is in use already (by a local IIS or otherwise), the getting-started container will not run. Using '81:80' makes it work when navigating to http://localhost:81/ - but the documentation was not helpful at all in this regard.

It is rather funny that I am met with this _after_ I got the container running by wild guesses:

* `-p 80:80` - map port 80 of the host to port 80 in the container

Along with answers to all my other questions.

---

I could have spent this past hour and a half a whole lot better with a few friendly nudges instead of a whole lot of "everyone knows this".

Well, I am sorry if I am harsh like that, but the frustration was massive.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As the issue is old, the context may have changed. The documents have been updated heavily in the past year.
The command line is now explained at the start of the tutorial at in https://docs.docker.com/get-started/#start-the-tutorial
The reference information about port mapping is also now at the start of the tutorial.
A description of the Dockerfile is now at the second step of the tutorial at https://docs.docker.com/get-started/02_our_app/#build-the-apps-container-image
