### ISSUE TITLE
Doesn't create running to-do app container

### ISSUE THREAD

**Issue by jcrock7723** [docker/docker.github.io#12225]
File: [get-started/06_bind_mounts.md](https://docs.docker.com/get-started/06_bind_mounts/)

Run the following command. We’ll explain what’s going on afterwards:

 docker run -dp 3000:3000 \
     -w /app -v "$(pwd):/app" \
     node:12-alpine \
     sh -c "yarn install && yarn run dev"

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As this issue is old, some context may have been lost. Since there appears to be no issues with the documentation itself, this issue will be closed.  When troubleshooting, it is helpful to share the output that results from the command. You may try the Docker Community Forums to get help troubleshooting your environment.
