### ISSUE TITLE
404 at /engine/userguide/eng-image/dockerfile

### ISSUE THREAD

**Issue by TitouanBgr** [docker/docker.github.io#12333]
I found a broken link : https://docs.docker.com/engine/userguide/eng-image/dockerfile
I arrived on this page through: https://brightinventions.pl/

**Comment by thaJeztah** [comment]
I think that may be a broken link on that website; while there used to be a `dockerfile_best-practices` page (https://github.com/docker/docker.github.io/tree/3c44bc7f746d161efb4399a56db809c352ab5521/engine/userguide/eng-image), I don't think there was a `dockerfile` page; https://github.com/docker/docker.github.io/tree/v17.09-release/engine/userguide/eng-image.

I checked if there's a redirect for that old URL, and confirmed that it's redirecting correctly;  https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices redirects to https://docs.docker.com/develop/develop-images/dockerfile_best-practices/, which is where that content currently lives.

I'd recommend contacting https://brightinventions.pl/ to update the URL on their website.

Let me close the ticket here because of the above, but feel free to continue the conversation
