### ISSUE TITLE
Copying code from text-fields is non-trivial

### ISSUE THREAD

**Issue by DannyDannyDanny** [docker/docker.github.io#12513]
I can't seem to (easily) copy-paste from the text-box. If this intended behavior, then please close the issue.

[Example 1](https://github.com/docker/machine/releases/): I drag over the text and expect it all to be selected like:
![image](https://user-images.githubusercontent.com/16453674/111434723-2e366a80-8700-11eb-97f6-358bb558f970.png)

[https://docs.docker.com/machine/install-machine/](https://github.com/docker/machine/releases/): But instead on [machine/install-machine.md](https://docs.docker.com/machine/install-machine/) I get:
![image](https://user-images.githubusercontent.com/16453674/111433416-8e2c1180-86fe-11eb-9107-96cac5854c07.png)

Very probably related to issue [11695](https://github.com/docker/docker.github.io/issues/11695)

**Comment by IanVaughan** [comment]
I see this as a bug, code examples should be easy to copy.

Example from https://docs.docker.com/compose/rails/

<img width="1012" alt="Screenshot 2021-04-08 at 17 10 41" src="https://user-images.githubusercontent.com/158600/114060765-9e628700-988d-11eb-9584-71e30f6a9f7c.png">

It only highlights and therefore I can only copy the code itself, not the comments.

Ideally, there would also be a copy to clipboard on each code snippet.

**Comment by DannyDannyDanny** [comment]
In your example, the selective-_selection_-behavior (for lack of a better name), works exactly as intended.

I'm clueless where this behavior is implemented. Perhaps it can be disabled in the docker documentation.

**Comment by githubjeka** [comment]
Same too. Cant copy code.

Chrome 89.0.4389.114

![image](https://user-images.githubusercontent.com/874234/114664838-f45b8280-9d04-11eb-82b7-217c7cf734bc.png)

**Comment by githubjeka** [comment]
P.S. After update Docker on Windows my IDE lost connect with `docker-machine.exe`

![image](https://user-images.githubusercontent.com/874234/114665041-31277980-9d05-11eb-89af-e1702294dd30.png)

expect a large influx of people https://docs.docker.com/machine/install-machine/ :)

**Comment by DannyDannyDanny** [comment]
@githubjeka 

I think you've posted the your snippet on the wrong issue. The snippet looks like a _windows + git bash_ script that installs docker-machine.

This issue and its comments relate to copying code snippets from docker documentation.

**Comment by thaJeztah** [comment]
Looks like the problem is that the command is wrapped over multiple lines, but does not use line-continuation symbols (`\`) for the wrapped lines; as a result the code-highlighter marks those lines as "process output", which is excluded from selections.

Pushing a PR to fix

**Comment by thaJeztah** [comment]
Pull request: https://github.com/docker/docker.github.io/pull/12716

**Comment by IanVaughan** [comment]
I may be mistaken, but the issue is not related to `&&` vs `\`, as per my screenshot above from  https://docs.docker.com/compose/rails/, it does not copy comments.

Looking at the source it can be seen to be just normal lines:

<img width="709" alt="Screenshot 2021-04-20 at 13 35 53" src="https://user-images.githubusercontent.com/158600/115396833-56bcf300-a1dd-11eb-90f8-9c7660e7a9aa.png">

https://github.com/docker/docker.github.io/blob/master/samples/rails.md

So this issue is still open for me.

**Comment by thaJeztah** [comment]
@IanVaughan ah; sorry I missed your example; related, but different cause: let me work on a fix for that one

**Comment by DannyDannyDanny** [comment]
Works like a charm @thaJeztah !

Screen shot take from [your preview](https://deploy-preview-12718--docsdocker.netlify.app/machine/install-machine/).

![image](https://user-images.githubusercontent.com/16453674/115406690-b1f7e100-a1ef-11eb-9378-7ed4b7d3a02e.png)

**Comment by thaJeztah** [comment]
Great!

So; the issue was that we try to make our `console` examples better copy/pasteable; those examples often contain a combination of

- a prompt (`$` or `PS>`)
- the "command" to run (e.g. `docker run foo`)
- output example of the command

And in those cases we try to avoid users accidentally copying the prompt or the output of the command; the CSS rule was a bit overly optimistic and applied the same to other situations (such as YAML examples or script examples), and yes, for those, you want to copy everything.

Looks like it fixed now, so 🎉, but if you find examples in the docs that still have an issue, feel free to open a new ticket (there probably may be some issues left to address)
