### ISSUE TITLE
404 at /install/linux/linux-postinstall/%20sudo%20groupadd%20docker%20sudo%20usermod%20-aG%20docker%20$USER

### ISSUE THREAD

**Issue by Elias-Betancourt** [docker/docker.github.io#13246]
I found a broken link : https://docs.docker.com/install/linux/linux-postinstall/%20sudo%20groupadd%20docker%20sudo%20usermod%20-aG%20docker%20$USER

**Comment by thaJeztah** [comment]
The correct url should be:

https://docs.docker.com/install/linux/linux-postinstall/

I suspect you copied this URL from somewhere and accidentally copied some output together with it, because the parts after that (in the URL you posted) is;

```
sudo groupadd docker sudo
usermod -aG docker $USER
```


Based on the above, I _think_ this was a copy/paste mistake, so I'll close, but let me know if you did arrive at that URL through a link somewhere in our docs.
