### ISSUE TITLE
Python image doesn't create

### ISSUE THREAD

**Issue by dmitrybabanovforreal** [docker/docker.github.io#13279]
I'm following the official tutorial described here: https://docs.docker.com/language/python/build-images/

At the end of that page, they say I should have two images: the app itself and python:3.9-slim-buster.

However, I run `docker build`, it executes with no errors but after that, I only see an image for my app created and no python image.

Below is my `Dockerfile`

```
# syntax=docker/dockerfile:1

FROM python:3.9-slim-buster

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

# Setting up a cron job
RUN apt-get update && apt-get -y install cron
COPY cron-file /etc/cron.d/cron-file
RUN chmod 0644 /etc/cron.d/cron-file
RUN crontab /etc/cron.d/cron-file
RUN touch /var/log/cron.log
CMD cron && tail -f /var/log/cron.log
```

I run Docker Desktop on Windows

**Comment by crydotsnake** [comment]
What errors do you get? A screenshot of the error message would be helpful.

**Comment by thaJeztah** [comment]
I think this is the same / related to https://github.com/docker/docker.github.io/pull/13203#discussion_r674785513

When using BuildKit as builder, the base image is pulled in the build-cache, but does not appear in the list of images. This is the expected behavior when using BuildKit, and allows for the build-cache to be pruned, but the docs should probably be updated to not explicitly mention that _two_ images will appear (only describe the image that was built)

/cc @usha-mandya

**Comment by dmitrybabanovforreal** [comment]
@thaJeztah Thank you! I assumed it might be an expected behavior since my container works correctly nevertheless. Searched for other similar issues here but couldn't find it.

**Comment by dmitrybabanovforreal** [comment]
@crydotsnake Thanks, the question is resolved already!
