### ISSUE TITLE
404 at /docker-for-windows/wsl/for%20details

### ISSUE THREAD

**Issue by Thawatchaisri** [docker/docker.github.io#13355]
I found a broken link : https://docs.docker.com/docker-for-windows/wsl/for%20details

**Comment by thaJeztah** [comment]
Where did you find the link? Looking at that URL, it may be that you copied it including some text after the actual link (it corresponds with `https://docs.docker.com/docker-for-windows/wsl/ for details`). The URL itself is https://docs.docker.com/docker-for-windows/wsl/ (which should redirect to https://docs.docker.com/desktop/windows/wsl/, because the page moved).

**Comment by thaJeztah** [comment]
Ah, I think I found it; I see there's an error message in Docker Desktop that prints:


```
We recommend to activate the WSL integration in Docker Desktop settings.

See https://docs.docker.com/desktop/windows/wsl/ for details.
```

Also adding an easier to use URL in https://github.com/docker/docker.github.io/pull/13382


I'm opening a PR to change it, and to put the actual URL on a separate line for easier copying;

```
We recommend to activate the WSL integration in Docker Desktop settings.

For details about using Docker Desktop with WSL 2, visit:

https://docs.docker.com/desktop/windows/wsl/
```

**Comment by thaJeztah** [comment]
Let me close this ticket, because the broken link is not in the docs itself, and will be fixed in Docker Desktop.
