### ISSUE TITLE
Feedback for: docker-cloud/builds/automated-testing.md

### ISSUE THREAD

**Issue by TylerHelmuth** [docker/docker.github.io#1336]
File: [docker-cloud/builds/automated-testing.md](https://docs.docker.com/docker-cloud/builds/automated-testing/)

Is there any way to separate tests into separate Dockerfiles and build/run them all under one sut service?  Or do I have to make a different .test.yml file for each Dockerfile associated with a suite of tests?

**Comment by sanscontext** [comment]
Hey @TylerHelmuth, you have have multiple `test.yml` files, as described in the doc. Also, check out the [Advanced topic on Custom Build Hooks](https://docs.docker.com/docker-cloud/builds/advanced/#/custom-build-phase-hooks) - it includes more information about customizing the test behavior. 

Normally this repo is only for docs bugs, but since the info was there and you couldn't find it, I'll take this as a call to provide better cross-linking here.
