### ISSUE TITLE
IRC quickstart guide link is broken

### ISSUE THREAD

**Issue by sankee168** [docker/docker.github.io#135]
IRC quickstart guide link in README is broken.
https://docs.docker.com/project/get-help/irc-quickstart

**Comment by johndmulhausen** [comment]
@sankee168 -- Thanks for the report! Can you tell us where this link appears?

**Comment by sankee168** [comment]
@johndmulhausen  
Link is in README -> How the project is run -> Internet Relay Chat

refer https://github.com/docker/docker#how-the-project-is-run

**Comment by mstanleyjones** [comment]
Hi there, thanks for the report. The good news is that I don't think that problem exists anymore.  I think @johndmulhausen actually fixed it in commit https://github.com/docker/docker/commit/29f08cf49bede9bcaf4f06e643988d30be008c0b.

If you are still experiencing problems with the link, please file an issue in the https://github.com/docker/docker project, since the file is maintained in that repository.
