### ISSUE TITLE
not getting started

### ISSUE THREAD

**Issue by TraversingAU** [docker/docker.github.io#13806]
File: [get-started/index.md](https://docs.docker.com/get-started/)

I think we missed some steps to get started....
download docker...
open docker, we are now here
![image](https://user-images.githubusercontent.com/54008079/140689174-5192abd2-2d63-4711-959d-3a2600425dfb.png)
no buttons do anything... ok switch to the getting started tutorial,

now he is here:
https://youtu.be/iqqDU2crIEQ

"start with a base image," he says
" we will start with a node application"
and we are here:
![image](https://user-images.githubusercontent.com/54008079/140689481-8af03873-8f5a-4e3e-9fa4-7cb009ed48d4.png)

ok, is that VS Code ?
what steps are missing here?

open VSCode, open a terminal, ?
run this line: ?
 docker run -d -p 80:80 docker/getting-started
opps that does not work.

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS c:\users\machine\documents\Test1>  docker run -d -p 80:80 docker/getting-started
docker : The term 'docker' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2
+  docker run -d -p 80:80 docker/getting-started
+  ~~~~~~
    + CategoryInfo          : ObjectNotFound: (docker:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

so please fill in the gaps in your getting started...

what do I do before I run this line ?
I have restarted the machine once. should I do it twice ?

**Comment by TraversingAU** [comment]
Still not getting started:

"To run the Quick Start Guide on demand, right-click the Docker icon in the Notifications area (or System tray) to open the Docker Desktop menu and then select Quick Start Guide. "

this doesn't work either

**Comment by TraversingAU** [comment]
I tried to do a factory reset and it crashed:

![image](https://user-images.githubusercontent.com/54008079/140698223-41281667-0546-474c-8f47-60ce057f56f7.png)

now I have uninstalled and reinstalled and it still crashes the same way

**Comment by craig-osterhout** [comment]
Hi @TraversingAU, thanks for sharing the issue.
It seems the Docker UI-based quickstart guide may have not started because of the error.
From the error, it appears that you may need to enable a setting in your device's BIOS. The documentation link will lead you to https://docs.docker.com/desktop/troubleshoot/topics/#virtualization
In step 3, follow the link to https://bce.berkeley.edu/enabling-virtualization-in-your-pc-bios.html
If after following the steps, the error still occurs, please help file a bug report at https://github.com/docker/for-win
You may also seek support at:
- [Docker Community Forums](https://forums.docker.com/)
- [Docker Community Slack](https://dockercommunity.slack.com/)
- If you have a paid Docker subscription, you can use [Docker support](https://hub.docker.com/support/contact/).

After the error is resolved, you can manually initiate the UI-based quickstart guide. To manually start the quickstart, please see https://docs.docker.com/desktop/get-started/
You must run the steps in the UI-based guide before running the command, `docker run -d -p 80:80 docker/getting-started`.
I'll look in to incorporating this information into https://docs.docker.com/get-started/
