### ISSUE TITLE
Progress on docker push command

### ISSUE THREAD

**Issue by nroose** [docker/docker.github.io#13820]
File: [engine/reference/commandline/push.md](https://docs.docker.com/engine/reference/commandline/push/)

Can you please provide a plain progress option for the push command? Or something like that? Or tell us how to make it not do the default progress stuff? It's currently pretty poorly behaved for me. Please make it work for more environments.

**Comment by thaJeztah** [comment]
This issue tracker is for reporting issues with the docker documentation; for feature requests for the docker cli, consider using the https://github.com/docker/cli issue tracker, or docker's public roadmap https://github.com/docker/roadmap.

That said, to suppress the progress output, you can use the `--quiet` option on `docker push`, which will suppress the progress output, and print a message after pushing.

Let me close this ticket because of the above, but feel free to continue the conversation
