### ISSUE TITLE
SSH agent instructions for WSL2 and Docker Dev Environments

### ISSUE THREAD

**Issue by felipecruz91** [docker/docker.github.io#13905]
### Problem description

As part of the Docker Desktop 4.2.0 release, we should have added the following text:

---

When cloning a private Git repository by SSH from WSL2, you must have an SSH agent running in WSL2. In case you haven't, you could append the following content to your `~/.profile`:

```bash
SSH_ENV="$HOME/.ssh/agent-environment"
function start_agent {
    echo "Initialising new SSH agent..."
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
}
# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi
```

After that, re-open a WSL2 terminal and type `ssh-add <path to your private ssh key>` to add your private SSH key to the SSH agent.

---

### Problem location

https://docs.docker.com/desktop/dev-environments/

### Project version(s) affected

The text should appear in the documentation for Docker Desktop 4.2.0 and onwards.

/cc @gtardif @rumpl @glours

**Comment by rumpl** [comment]
Cool, we shoud open a PR for the docs

**Comment by usha-mandya** [comment]
Updates are live - https://docs.docker.com/desktop/dev-environments/#start-a-single-container-dev-environment.

**Comment by samdidos** [comment]
Hi, I have a question regarding the location where to put this script

> When cloning a private Git repository by SSH from WSL2, you must have an SSH agent running in WSL2. In case you haven't, you could append the following content to your ~/.profile

When you say ` you must have an SSH agent running in WSL2`, do you mean in the WLS2 docker-agent distro? When connecting into it (`wsl -d docker-agent`) I haven't found any ssh-agent installed, I guess that's not where you meant to put it.

Otherwise I've been trying with Windows Git Bash running `eval $(ssh-agent) && ssh-add ./ssh/id_rsa`, but I still got this message when trying to clone my private repo from Docker Dev Environment wizard setup :

![image](https://user-images.githubusercontent.com/7490081/200077799-e9708e36-96db-4854-a906-31523554a5f2.png)

Please could you add more precision? Thank you, this feature seems great :)

**Comment by usha-mandya** [comment]
@felipecruz91 Can we clarify this in the docs, please? CC @aevesdocker
