### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by Dulingxiao** [docker/docker.github.io#14029]
**error log**
/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:235: starting container process caused "container init exited prematurely".

**startup script**
docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:ro \
  --volume=/sys:/sys:ro \
  --volume=/data/docker/lib/docker:/var/lib/docker:ro \
  --volume=/dev/disk:/dev/disk:ro \
  --publish=4194:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest

**docker version**
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-208.git7d71120.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Mon Jun  7 15:36:09 2021
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-208.git7d71120.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Mon Jun  7 15:36:09 2021
 OS/Arch:         linux/amd64
 Experimental:    false

**system version**
3.10.0-1127.19.1.el7.x86_64

**different**
changed the root directory and disk path. According to the script：https://blog.csdn.net/weixin_32820767/article/details/81196250

**Comment by thaJeztah** [comment]
Docker 1.13.1 is a [really old version](https://github.com/moby/moby/releases/tag/v1.13.1) that reached EOL (and is no longer maintained) since 2017; from the package version output, I suspect you're running the Red Hat fork of Docker, which is not maintained by us (and is known to have many modifications in the source code, which _could_ be related); the `container init exited prematurely` does not seem to exist in our own source code, but could come from the container itself, or from Red Hat's fork source code. If you're not able to install the official Docker packages, perhaps you're able to get support through Red Hat's support.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests for the docs. For other type of questions, consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- the Docker Support Forums - https://forums.docker.com
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)

I'm closing this issue because of the above, but feel free to continue the conversation

**Comment by Dulingxiao** [comment]
通过对于docker启动脚本路径映射的排查，发现--volume=/sys:/sys:ro存在问题，然后将路径拆解发现
--volume=/sys/fs/cgroup/devices:/sys/fs/cgroup/devices:ro \ 
是这个路径导致了
/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:235: starting container process caused "container init exited prematurely".

修改后脚本 启动成功

docker run \
            --volume=/:/rootfs:ro \
            --volume=/var/lib/docker/:/var/lib/docker:ro \
            --volume=/dev/disk/:/dev/disk:ro \
            --volume=/sys/bus:/sys/bus:ro \
            --volume=/sys/dev:/sys/dev:ro \
            --volume=/sys/devices:/sys/devices:ro \
            --volume=/sys/block:/sys/block:ro \
            --volume=/sys/class:/sys/class:ro \
            --volume=/sys/power:/sys/power:ro \
            --volume=/sys/firmware:/sys/firmware:ro \
            --volume=/sys/kernel:/sys/kernel:ro \
            --volume=/sys/module:/sys/module:ro \
            --volume=/sys/hypervisor:/sys/hypervisor:ro \
            --volume=/sys/fs/bpf:/sys/fs/bpf:ro \
            --volume=/sys/fs/ext4:/sys/fs/ext4:ro \
            --volume=/var/run:/var/run:ro \
            --volume=/sys/fs/cgroup/cpu,cpuacct:/sys/fs/cgroup/cpuacct,cpu:ro \
            --volume=/sys/fs/cgroup/cpuset:/sys/fs/cgroup/cpuset:ro \
            --volume=/sys/fs/pstore:/sys/fs/pstore:ro \
            --volume=/sys/fs/cgroup/blkio:/sys/fs/cgroup/blkio:ro \
            --volume=/sys/fs/cgroup/memory:/sys/fs/cgroup/memory:ro \
            --volume=/sys/fs/cgroup/pids:/sys/fs/cgroup/pids:ro \
            --volume=/sys/fs/cgroup/freezer:/sys/fs/cgroup/freezer:ro \
            --volume=/sys/fs/cgroup/net_prio:/sys/fs/cgroup/net_prio:ro \
            --volume=/sys/fs/cgroup/hugetlb:/sys/fs/cgroup/hugetlb:ro \
            --volume=/sys/fs/cgroup/perf_event:/sys/fs/cgroup/perf_event:ro \
            --net=host	\
            --detach=true \
            --name=cadvisor \
    google/cadvisor:latest
