### ISSUE TITLE
spring-petclinic demo application is not working propelry 

### ISSUE THREAD

**Issue by asfor94** [docker/docker.github.io#14055]
### Problem description
When you follow the tutorial for build java projects with docker and you get to the point when you want to build the image an error appears while docker work to execute the commands in the Dockerfile as below:

` ERROR [5/6] RUN ./mvnw dependency:go-offline                                                                  
[5/6] RUN ./mvnw dependency:go-offline:
#15 3.797 /bin/sh: ./mvnw: not found
executor failed running [/bin/sh -c ./mvnw dependency:go-offline]: exit code: 127`

### Problem location

- I saw a problem at the following URL: (https://docs.docker.com/language/java/build-images/)

**Comment by MatthewR216** [comment]
+1 I am also experiencing this. I am on Windows 11.

**Comment by hawada96** [comment]
Piggybacking on this too. Not sure what the problem is. I am also on Windows 11.

**Comment by amerixan** [comment]
Try replacing `mvnw` with `mvnw.cmd` in your Dockerfile.

**Comment by rkleee** [comment]
I had the same problem, I have to use Windows, too. 
Using mvnw.cmd didn't fix anything and I'm not sure what the itention behind this. Docker can only run the bash file mvnw, not the windows comand thing files mvnw.cmd.

I found this thread https://stackoverflow.com/questions/61226664/build-docker-error-bin-sh-1-mvnw-not-found and it said the problem were the windows line breaks. 
As I already had Atom installed and in use for this tutorial, I've done the convertion of the line breaks here by simply changing "CRLF" to "LF" and saving the file. I guess, a lot of other IDEs must be capable of this, too.
After this, the build worked as intended.

**Comment by hawada96** [comment]
Thanks @rkleee, I tried the suggestion in the thread and it was just the ticket. Now I can finally make progress as a Java and Maven noob. Much appreciated.

**Comment by hawada96** [comment]
So I actually just ended up switching CRLF to LF on the mvnw file which gets copied into the container but you will also need to somehow apply this process for the contents of the src/ directory or else you will get this error in the docker runtime.

`
[ERROR] Failed to execute goal io.spring.javaformat:spring-javaformat-maven-plugin:0.0.27:validate (default) on project spring-petclinic: Formatting violations found in the following files:
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/system/WelcomeController.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/system/CrashController.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/system/CacheConfiguration.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/owner/PetController.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/owner/OwnerRepository.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/owner/Visit.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/owner/PetValidator.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/owner/VisitController.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/owner/OwnerController.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/owner/PetType.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/owner/Pet.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/owner/PetTypeFormatter.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/owner/Owner.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/model/Person.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/model/NamedEntity.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/model/BaseEntity.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/model/package-info.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/PetClinicApplication.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/vet/VetRepository.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/vet/Vets.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/vet/VetController.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/vet/Specialty.java
[ERROR]  * /app/src/main/java/org/springframework/samples/petclinic/vet/Vet.java
[ERROR]  * /app/src/test/java/org/springframework/samples/petclinic/PetclinicIntegrationTests.java
[ERROR]  * /app/src/test/java/org/springframework/samples/petclinic/system/CrashControllerTests.java
[ERROR]  * /app/src/test/java/org/springframework/samples/petclinic/service/ClinicServiceTests.java
[ERROR]  * /app/src/test/java/org/springframework/samples/petclinic/service/EntityUtils.java
[ERROR]  * /app/src/test/java/org/springframework/samples/petclinic/owner/PetControllerTests.java
[ERROR]  * /app/src/test/java/org/springframework/samples/petclinic/owner/PetTypeFormatterTests.java
[ERROR]  * /app/src/test/java/org/springframework/samples/petclinic/owner/VisitControllerTests.java
[ERROR]  * /app/src/test/java/org/springframework/samples/petclinic/owner/OwnerControllerTests.java
[ERROR]  * /app/src/test/java/org/springframework/samples/petclinic/model/ValidatorTests.java
[ERROR]  * /app/src/test/java/org/springframework/samples/petclinic/vet/VetTests.java
[ERROR]  * /app/src/test/java/org/springframework/samples/petclinic/vet/VetControllerTests.java
[ERROR]
[ERROR] Run `spring-javaformat:apply` to fix.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

What I did was insert another command in the last CMD directive of the Dockerfile and that seems to do the trick rather than going in and changing the files from CRLF to LF manually or using a tool like dos2unix.

**If you are on windows you will likely want to do the following to that tutorial Dockerfile:**
`
CMD ["./mvnw", "spring-javaformat:apply", "spring-boot:run"]
`
It should run fine after that.

**Comment by asfor94** [comment]
The issue is solved by referring to @rkleee comment above.
Many Thanks guys.
