### ISSUE TITLE
Invalid response code for exec resize in the API reference

### ISSUE THREAD

**Issue by th0m4s** [docker/docker.github.io#14063]
### Problem description

The engine API reference indicates that the correct response code for a successful exec resize operation is 201, which in reality is 200.
As an example, the container resize operation returns 200 in case of success, which seems correct because the HTTP code 201 indicates a "created" object, not a modified one.

I wanted to edit the API reference myself but I didn't find which page to edit, hence my issue here.

### Problem location
We can see the response codes for this operation here: https://docs.docker.com/engine/api/v1.41/#operation/ExecResize

### Suggestions for a fix
Update the documentation and use the 200 status code.

**Comment by sudo-bmitch** [comment]
That may be handled over in the [swagger def on moby/moby](https://github.com/moby/moby/blob/10aecb0e652d346130a37e5b4383eca28f594c21/api/swagger.yaml#L8785). @thaJeztah may know more.

**Comment by th0m4s** [comment]
Thanks a lot, this is the file I was looking for in this repository.
I'll fork the moby repository and open a pull request there, but let this issue opened if @thaJeztah has something to say here.

**Comment by thaJeztah** [comment]
Thanks for reporting; yes, I suspect that must've been a copy/pasta error and the wrong status code has been used there; https://github.com/moby/moby/blob/10aecb0e652d346130a37e5b4383eca28f594c21/api/swagger.yaml#L8785-L8786. There's also probably some other status codes that could be added (`400` - which is returned if an invalid parameter was passed, and `500` for internal server errors) (probably fine to take care of those separately).

Note that the documentation itself is using the versioned swagger files in the `docs` directory in that repository; https://github.com/moby/moby/tree/master/docs/api, so those would need to be updated as well, but ideally in a separate commit, so that those changes can be cherry-picked into the release branch (which is where the docs gets them from)

> I'll fork the moby repository and open a pull request there, but let this issue opened if @thaJeztah has something to say here.

Let me know if you need help (also happy to open e pull request myself); when opening a pull request in the moby repository, make sure that your commit message contains a DCO (Signed-Off-By) line with your real name and e-mail as outlined in https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by th0m4s** [comment]
Thanks for your response, here is the pull request: https://github.com/moby/moby/pull/43122
I hope it's what required, let me know if something is missing or needs to be fixed.

**Comment by thaJeztah** [comment]
Thanks! Looks good 👍
