### ISSUE TITLE
404 at /machine/driver

### ISSUE THREAD

**Issue by jackade2022** [docker/docker.github.io#14356]
I found a broken link : https://docs.docker.com/machine/driver

**Comment by jerae-duffin** [comment]
hey @jackade2022 
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by thaJeztah** [comment]
docker machine has been deprecated, and the documentation has been removed; https://docs.docker.com/machine/
(possibly we missed a redirect for an old page). I'm wondering if it was a typo though, because there _was_ a https://docs.docker.com/machine/drivers/ (plural) page.

If you have more details on where you found that URL, perhaps we can fix the link, but otherwise, I don't think there's anything actionable here. Let me go ahead and close this ticket, but feel free to continue the conversation.
