### ISSUE TITLE
Include install instructions without Docker Desktop

### ISSUE THREAD

**Issue by scorbin-shq** [docker/docker.github.io#14404]
File: [desktop/mac/install.md](https://docs.docker.com/desktop/mac/install/)

Since Docker Desktop is now a paid product, I believe your install instructions should include an option for those who do not wish to use it.

**Comment by Sigmarul** [comment]
> File: [desktop/mac/install.md](https://docs.docker.com/desktop/mac/install/)
> 
> Since Docker Desktop is now a paid product, I believe your install instructions should include an option for those who do not wish to use it.

super

**Comment by thaJeztah** [comment]
Docker Desktop is still free to use, unless you are using it for commercial use for larger companies;

> Commercial use of Docker Desktop in larger enterprises (more than 250 employees OR more than $10 million USD in annual revenue) now requires a paid subscription. 

(details in [the blog post](https://www.docker.com/blog/the-grace-period-for-the-docker-subscription-service-agreement-ends-soon-heres-what-you-need-to-know/))


For macOS, there are no install instructions without Docker Desktop; while you can install the docker _cli_ on macOS (see instructions in the [Install client binaries on macOS](https://docs.docker.com/engine/install/binaries/#install-client-binaries-on-macos) section), the Docker Engine (which runs the containers) requires a Linux kernel, so cannot be installed on macOS without additional setup (which is what Docker Desktop provides, among others).

closing this because of the above, but feel free to continue the conversation
