### ISSUE TITLE
Add additional information regarding Overlay(2) to documentation

### ISSUE THREAD

**Issue by sybrandy** [docker/docker.github.io#1444]
### Problem description

During the investigation of an issue that I reported, it was noted that we are using a non-standard configuration.  In particular, we were running Overlay 2 on a non-standard file system configuration.  Nothing in the documentation indicated that there may be issues.  Therefore, it is suggested that some notes be added to make it clear that there may be some quirks.  The link to the original issue is below.

https://github.com/docker/docker/issues/30531

### Problem location

https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/

### Suggestions for a fix

If there are known configurations that may cause issues or are recommended, such as those mentioned in the comments of the referenced bugs, please list them here.  If there would be a minimal list of Linux distros that should be documented, I'd suggest the following:

* RedHat/CentOS
* Debian
* Ubuntu
* Slackware

Any details should be referenced and not embedded in the documentation as we don't want to bloat the documentation too much or have extra maintenance work.

Suggested text:

> For RedHat/CentOS systems, it is recommended that Overlay (2) is used on top of an XFS filesystem.  See the [RedHat documentation](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html) for more information.  Also, see [this thread](https://github.com/docker/docker/issues/27358#issuecomment-254066211) for additional information to ensure the partition is properly formatted.

**Comment by dmcgowan** [comment]
We don't need to have special documentation for most distros. RedHat/CentOS is just a special case since they have backported overlayfs to an older kernel. I agree it would be a good idea to link directly to the RedHat documentation related to using overlay on RedHat/CentOS. For every other distro, our recommendation is more related to kernel version than distro-specific configuration. I am always in favor of documenting known issues and pointing to related discussions, however that can be hard to keep up with in documentation. It is easier to stick to recommendations (such as kernel version, dtype configuration, etc) and have all issues go through the issue tracker.

@sybrandy do you mind turning your suggested text into a PR here?

**Comment by sybrandy** [comment]
@dmcgowan Understood.  I only mentioned the others in case there were some known quirks as a minimum set of distros.

As for creating a PR, I'll try.  It depends on how much free time I have outside of work.

Thanks.

**Comment by mstanleyjones** [comment]
Please see https://success.docker.com/Policies/Compatibility_Matrix and #3276. Thanks!
