### ISSUE TITLE
404 at /get-docker/%5D

### ISSUE THREAD

**Issue by diegoes99** [docker/docker.github.io#14499]
I found a broken link : https://docs.docker.com/get-docker/%5D
I arrived on this page through: https://docs.permit.io/

**Comment by thaJeztah** [comment]
Thanks for reporting; this looks to be a broken link on the  https://docs.permit.io/ website (the `%5D` is a stray `]` after the URL that shouldn't be there); it's best to report this to the owner of that website, as this is not something we can fix in our docs.

I'm closing this because of the above, but feel free to continue the conversation
