### ISSUE TITLE
404 at /engine/installtion/linux/ubuntuinux/

### ISSUE THREAD

**Issue by nhutb1812291** [docker/docker.github.io#14565]
I found a broken link : https://docs.docker.com/engine/installtion/linux/ubuntuinux/

**Comment by thaJeztah** [comment]
Looks like there's a couple of typos in that URL; (`installtion` instead of `installation`, `ubuntuinux` instead of `ubuntulinux`); the correct URL is https://docs.docker.com/engine/installation/linux/ubuntulinux/ (which is an old URL, but should now redirect to https://docs.docker.com/engine/install/ubuntu/)

I suspect you tried to manually enter that URL and made a typo, but if you found that link on one of our websites, please leave a comment 👍
