### ISSUE TITLE
Language-specific guides request Myanmar

### ISSUE THREAD

**Issue by MrHtetNaingSoe** [docker/docker.github.io#14637]
### Problem location

- I saw a problem at the following URL: <Add URL>

- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>

**Comment by craig-osterhout** [comment]
Thanks for sharing this request. We currently do not have the capability to translate the documentation in to any other languages. In order to not keep this request hanging indefinitely, I'll close it as can't fix. 

We encourage community members to get involved and help each other. If it interests you to help the Myanmar developer community, a good and easy place to start might be creating some language-specific resources at https://github.com/docker/code-of-conduct or start a community group at https://www.meetup.com/pro/docker
