### ISSUE TITLE
$ curl -L https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine && chmod +x /tmp/docker-machine && sudo cp /tmp/docker-machine /usr/local/bin/docker-machine

### ISSUE THREAD

**Issue by Tahsinygt** [docker/docker.github.io#14657]

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. I assume this is to report a broken link. If it's to report another issue, please provide more details.

Can you share which page is the command is located on, or more details about the issue?


You can find the files in the Assets section of https://github.com/docker/machine/releases/tag/v0.16.2
You may try explicitly using the file name rather than using `uname`.
For example:
`curl -L https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-Linux-x86_64 >/tmp/docker-machine && chmod +x /tmp/docker-machine && sudo cp /tmp/docker-machine /usr/local/bin/docker-machine`

**Comment by craig-osterhout** [comment]
Closing this issue as stale. If the issue still persists in the documentation, please share more details with us.
