### ISSUE TITLE
Can't copy-paste Ubuntu install instructions

### ISSUE THREAD

**Issue by marcinkubica** [docker/docker.github.io#14787]
### Problem description
![image](https://user-images.githubusercontent.com/1593987/169503809-87d0c519-062f-47be-909a-33e6ce33e3e0.png)

### Problem location

- I saw a problem at the following URL:  https://docs.docker.com/engine/install/ubuntu/

- Can't copy the gray-colored text.

**Comment by DBBrowne** [comment]
^^ +1

On Firefox and Chrome:
![image](https://user-images.githubusercontent.com/72463218/169510785-4d8cde52-3696-46ed-bdcd-6d4f5707e1f2.png)

Appears to be an issue with whatever is interpreting the .md  being over aggressive about interpreting $ as line starts. 
GH is behaving well enough to allow the copy.
https://github.com/docker/docker.github.io/blob/master/engine/install/ubuntu.md
![image](https://user-images.githubusercontent.com/72463218/169511172-85be28f2-b215-43d8-b222-c8526e999ec4.png)

For anyone discovering this issue here's the consolidated command:
```
echo   "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] {{ download-url-base }} $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
```

**Comment by tropicbliss** [comment]
Since they're supposedly using a templating engine, obviously remove the {{ download-url-base }} part and replace it with the actual url

**Comment by DBBrowne** [comment]
Ty @tropicbliss , fixed.  Sorry, I should have checked that pasted in correctly.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This seems related to https://github.com/docker/docker.github.io/issues/14788 and appears fixed. Closing this ticket, but please let us know if the issue still persists.
