### ISSUE TITLE
Improvements to "network create" reference

### ISSUE THREAD

**Issue by Nils-Magnus** [docker/docker.github.io#1481]
File: [engine/reference/commandline/network_create.md](https://docs.docker.com/engine/reference/commandline/network_create/)

1. The options of `docker create network` are listed, but not documented. Especially the arguments to the options and their requirements and constraints are not completely described.
2. The structure of the page is confusing: It starts with some general stuff, goes into great detail for the overlay driver, and briefly returns to the bridge driver again.
3. The section "specifying advanced options" is verbatimly duplicated in the section "Examples".
4. The example with `--aux-address` is at least misleading, the mentioned option never shows up in the actual example. In no part of this page it is explained what `--aux-address` is actual for.
5. I am looking for some information about how the engine ties the *host* to these newly created networks, especially if I have more than a single interface on my host.

**Comment by mstanleyjones** [comment]
1.  The extended examples are back.

2.  This could be improved.

3.  No longer an issue.

4.  I find some examples with --aux-address in them: https://docs.docker.com/engine/reference/commandline/network_create/#specify-advanced-options

5.  This could also be enhanced.

The file is in the `docker/docker` repo if anyone wants to tackle this.

**Comment by surajnarwade** [comment]
claiming this :)

**Comment by mstanleyjones** [comment]
Sorry, but this is not a file you should be editing in our repo. It is a generated file. The original content is in moby/moby. Please replicate your edits to https://github.com/moby/moby/blob/master/docs/reference/commandline/network_create.md. You will need to clone that repo and you will need to do your commit in the command line so that you can sign your commit (add the -s switch to git commit. Please add the link to the moby/moby pull request to #1481.

**Comment by surajnarwade** [comment]
@mstanleyjones , am onto moby then

**Comment by mstanleyjones** [comment]
@surajnarwade let me know if you need help creating a `moby/moby` issue for this. Closing here for now.

**Comment by surajnarwade** [comment]
@mstanleyjones sure :)
