### ISSUE TITLE
Does  "s3:ListBucket" is really required for registry/storage-drivers/s3 ?

### ISSUE THREAD

**Issue by peleduri** [docker/docker.github.io#14818]
### Problem description

Does  "s3:ListBucket" is really required for registry/storage-drivers/s3 ?

### Problem location

 https://docs.docker.com/registry/storage-drivers/s3/#:~:text=Effect%22%3A%20%22Allow%22%2C%0A%20%20%20%20%20%20%22Action%22%3A%20%5B-,%22s3%3AListBucket%22%2C,-%22s3%3AGetBucketLocation%22%2C%0A%20%20%20%20%20%20%20%20%22s3

### Suggestions for a fix

If it is required, explain why?
if it is not required, remove it ...

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the source repo at https://github.com/distribution/distribution/tree/main/docs/storage-drivers
The permissions were added in https://github.com/distribution/distribution/pull/1590
You can also try to catch the maintainers in Slack, https://docs.docker.com/registry/help/
