### ISSUE TITLE
404 at /compos

### ISSUE THREAD

**Issue by AliHasan-Scientist** [docker/docker.github.io#14982]
I found a broken link : https://docs.docker.com/compos

**Comment by AliHasan-Scientist** [comment]
### ISSUE:
 Either specify a supported version (e.g "2.2" or "3.3") and place your servi
ce definitions under the `services` key, or omit the `version` key and place you
r service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compos
e/compose-file/

**Comment by thaJeztah** [comment]
I suspect you got that error message when using the legacy v1 compose version; https://github.com/docker/compose/blob/1.28.x/compose/config/errors.py#L1-L7

Likely your terminal was not large enough to print the message as-is,  and the URL was wrapped; the rest of the URL is on the next line in your example; the URL you're looking for is;

https://docs.docker.com/compose/compose-file/


Given that this is not a broken link in the docs itself, but likely caused because of the above, I don't think there's something that can be fixed in the documentation itself, so I'm closing this ticket, but hope that the above helps you further. I would also highly recommend upgrading to compose v2; if you're running Docker Desktop, it should already be available (and most linux installation should also include it), but otherwise;  https://docs.docker.com/compose/install/compose-plugin/
