### ISSUE TITLE
Document TaskTemplate > ContainerSpec > Hosts for /services/create and /services/update

### ISSUE THREAD

**Issue by sbrattla** [docker/docker.github.io#1530]
The following is (part of a) valid JSON when creating or updating a service :

```
{
  "Name": "testservice",
  "TaskTemplate": {
    "ContainerSpec": {
      "Hosts": ["192.168.132.103 api"],
```

The `Hosts` element is not documented in the [v1.25 API Reference](https://docs.docker.com/engine/api/v1.25/#operation/ServiceCreate).

**Comment by mstanleyjones** [comment]
@aaronlehmann did you mean to make a PR for this?

**Comment by aaronlehmann** [comment]
It's the first time I've seen this issue. The mention of my name above is because I have a fork of this repository, and it includes a commit by @joaofnfernandes that references this issue. It's a GitHub misfeature, IMHO. I generally avoid including issue numbers in commit messages because it pollutes the issue when other people push that commit to a fork.

**Comment by mstanleyjones** [comment]
@thaJeztah can you shed any light on this issue?

**Comment by thaJeztah** [comment]
The 'Hosts' field was added in Docker 1.13 through https://github.com/moby/moby/pull/28031,
which corresponds with API version 1.26; https://docs.docker.com/engine/api/v1.26/#operation/ServiceCreate, so I think the documentation is correct
