### ISSUE TITLE
404 at /docker-for-mac/dashboard/

### ISSUE THREAD

**Issue by emmakuen** [docker/docker.github.io#15387]
I found a broken link: https://docs.docker.com/docker-for-mac/dashboard/
I arrived at this page through: http://localhost/tutorial

**Comment by thaJeztah** [comment]
Thanks for reporting! This will be fixed by https://github.com/docker/docker.github.io/pull/15498, which adds a missing redirect for the page that was moved.

As a workaround until that fix is published on docs.docker.com, you can use;

- https://docs.docker.com/desktop/#overview-of-docker-dashboard for an overview of the dashboard
- https://docs.docker.com/desktop/use-desktop/container/ and other pages in that same section, which describe the different view within the Dashboard
- use the navigation on the left-hand side to discover other documentation for Docker Desktop features.
