### ISSUE TITLE
404 at /docker-for-mac/dashboard/

### ISSUE THREAD

**Issue by LinuxDevOps0** [docker/docker.github.io#15391]
I found a broken link : https://docs.docker.com/docker-for-mac/dashboard/
I arrived on this page through: http://127.0.0.1/

**Comment by craig-osterhout** [comment]
Hi @LinuxDevOps0, thanks for sharing the issue.  It looks like this link is in the getting started repo (https://github.com/docker/getting-started/blob/master/docs/tutorial/index.md). I'll close this issue and create a PR there. 

The page you're probably looking for is https://docs.docker.com/desktop/.
For a more updated version of the getting started tutorial, please see https://docs.docker.com/get-started/

**Comment by thaJeztah** [comment]
Thanks for reporting! This will be fixed by https://github.com/docker/docker.github.io/pull/15498, which adds a missing redirect for the page that was moved.

As a workaround until that fix is published on docs.docker.com, you can use;

- https://docs.docker.com/desktop/#overview-of-docker-dashboard for an overview of the dashboard
- https://docs.docker.com/desktop/use-desktop/container/ and other pages in that same section, which describe the different view within the Dashboard
- use the navigation on the left-hand side to discover other documentation for Docker Desktop features.
