### ISSUE TITLE
Feedback for: engine/tutorials/dockervolumes.md

### ISSUE THREAD

**Issue by antsy** [docker/docker.github.io#1540]
File: [engine/tutorials/dockervolumes.md](https://docs.docker.com/engine/tutorials/dockervolumes/)

What's the volume "Propagation" setting? I can't find _any_ explanation of it from the Docker documentation.

**Comment by mstanleyjones** [comment]
Hi @antsy, this content is coming (back). For 1.13, we started automatically generating the CLI reference docs from the actual Docker code, instead of maintaining manually-generated content files. We realize that a lot of the manual content that was in the old files is valuable and we are working on a way to get it back. In the meantime, you can still see the propagation settings for volumes at https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md#bind-propagation.
