### ISSUE TITLE
Unclear wording in 'Sharing the application'

### ISSUE THREAD

**Issue by NitishKumar06** [docker/docker.github.io#15614]
**Problem:**

The following link (https://docs.docker.com/get-started/04_sharing_app/#push-the-image) contains information on how to push your docker image to docker hub. I personally find the text confusing since the command ` docker tag getting-started YOUR-USER-NAME/getting-started` do not give more information on what  is `getting-started`. Is it the image name? or is it a tag name?

Apart from this , the 4th point could mention a little more about `docker push YOUR-USER-NAME/getting-started` . Is `YOUR-USER-NAME/getting-started` the name of the repository we just created in [here](docker push YOUR-USER-NAME/getting-started) or is `getting-started` the image name?

**Solution:**

Enhance the documentation to understand the command more better.

**Comment by Lchris22** [comment]
Hey @NitishKumar06, I'd like to work on this!

**Comment by NitishKumar06** [comment]
@Lchris22 Please raise a PR for this issue.

**Comment by craig-osterhout** [comment]
Hi @NitishKumar06, thanks for sharing the issue. Lchriss22 has updated the docs to include a link to the reference documentation for the `docker tag` command. The information about the tag command can be found in that topic, so I'll close this.

In regards to your questions about this particular case, you can think of a tag as a version number. Every image has a name (also called repository) and a tag.
You can view this information in the `Images` section of Docker Desktop, or by using `docker image ls`.
In this particular case, `getting-started` is the image name you created in parts 2 and 3 with the `docker build` command. `your-username/getting-started` is a new image name that is being created by the `docker tag` command. As step 4 notes, since no tag is specified, the default `latest` tag is used for both images.

Here's a quick screenshot showing the image list before and after running the `docker tag` command.
![image](https://user-images.githubusercontent.com/103533812/190281638-79d6c103-5aeb-490e-9c99-c48e97a0af83.png)

If you need more support, please try the Docker Community Slack.
https://join.slack.com/t/dockercommunity/shared_invite/zt-1fukl8thi-Iq2rTGyJGMAkCeQKuyfWIA
