### ISSUE TITLE
GETTING STARTED app doesn't work (NEVER worked) - why is this ABSOLUTELY-CRITICAL demo always ABSOLUTELY GARBAGE ??? 

### ISSUE THREAD

**Issue by markvogt** [docker/docker.github.io#15617]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

I've followed this tutorial for building my own Docker image "from scratch" TO-THE-LETTER. 
I've:
CLONED the getting-started repo to a Win7 laptop running latest VSC
OBSERVED that the Sample Application documentation DOESN'T agree with what's ACTUALLY in the repo
(note: even after YEARS and YEARS and YEARS Docker simply CAN'T get this RIGHT, yet you want us to consider your product CREDIBLE -you all must have come from JAVA development backgrounds, yes? <they're the same way> ) 
The DOCUMENTATION says "MAKE a Dockerfile and use these few lines of code in it
I DO that, and attempt to build an image and GET an image, but spawning a CONTAINER from it yields an APP THAT DOESN'T WORK (throws errors) 

So next I decided to use the ORIGINAL (larger, more complex, still GARBAGE) Dockerfile... 
I CAN build an image
I CAN spawn a container from it... 
... and I STILL GET NOTHING when I browse to http://localhost:3000 

AMAZING how these magical, portable oh-so-simple "containerized" applications NEVER SEEM TO WORK. 

I honestly don't know WHY Docker continues to fascinate people so much. 

It certainly has NOTHING TO DO with the DOCKER DOCUMENTATION STAFF'S EFFORTS. 
IF anything their butchered efforts to make a "Getting Started" application has only made me want to go back to BUILDING APPLICATIONS FROM SCRATCH.

Luckily I'm not bitter. 

And I'm certainly NOT convinced ANYONE at Docker is EVER going to bother to read THIS issue for - oh - about 200 years... 

Data Scientist Mark in North Aurora IL

**Comment by vladdoster** [comment]
I 100% agree that your frustration regarding incorrect documentation (especially since it is the get started example) is warranted. However, I don't think your blanket statements disparaging the organization are not helpful.

I value strong documentation and this oversight reflects poorly on Docker.

I've fixed the documentation.

https://github.com/docker/docker.github.io/pull/15620

**Comment by NitishKumar06** [comment]
@markvogt What's the issue that you're facing in documentation? Do let me know about the stuff you're unable to understand.

**Comment by NitishKumar06** [comment]
@markvogt You've to make a Dockerfile in `/app/src` directory and build the image using `docker build -t getting-started .` . Once the image has been built , please make sure you don't have any other container running on the same host you would like your application to run. Run a container using `docker run -dp 3000:3000 <image name>`

**Comment by craig-osterhout** [comment]
Hi @markvogt, 
I think the issue is that the getting-started repo contains 2 apps. The getting-started app that displays the tutorial, and the sample app in the `app` subfolder.

In step 1 of [Get the app](https://docs.docker.com/get-started/02_our_app/#get-the-app), you pull the entire repo.
In step 2, we should make it more clear that you only need the `app` subfolder from that repo. 

Your working directory will only be the `app` directory from the repository. Ignore everything outside of the `app` directory.
![image](https://user-images.githubusercontent.com/103533812/189723881-1d9dfd30-70e2-4f3c-b14a-845bfd6d2478.png)

In the `app` directory, create a Dockerfile.
![image](https://user-images.githubusercontent.com/103533812/189724246-6dd37ce8-8718-44e4-a581-6fc7a45e94db.png)

Open the Command Prompt and change directory to the `app` directory and then run the `build` command to build the image.
![image](https://user-images.githubusercontent.com/103533812/189724512-87aed856-cbd5-4c55-961d-77b0ea9bb49b.png)

Now, run the `run` command to start the container
![image](https://user-images.githubusercontent.com/103533812/189725360-3485ba60-64b3-4f27-b721-122b15770137.png)


You can use Docker Desktop to verify the container is running or in the Command Prompt.
`docker container ls`
![image](https://user-images.githubusercontent.com/103533812/189725437-e4640a2f-4ee0-4e9a-a40a-fae9a1d448a5.png)

At this point, you can open a browser and go to http://localhost:3000
![image](https://user-images.githubusercontent.com/103533812/189726027-c148ef34-036f-445e-8f3f-43ea2a4b2e37.png)


If any of those steps does not work, please help take a screenshot of what you have done up to that point and the error you received.

For more support, please try the community Slack.
https://join.slack.com/t/dockercommunity/shared_invite/zt-1fukl8thi-Iq2rTGyJGMAkCeQKuyfWIA

**Comment by craig-osterhout** [comment]
Closing as stale. If the issue still exists, please provide more details.
