### ISSUE TITLE
Re: Entrypoint

### ISSUE THREAD

**Issue by xerosugar** [docker/docker.github.io#15699]
File: [develop/develop-images/dockerfile_best-practices.md](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

One of the examples says: `docker run postgres postgres --help`, is this right, or should there only be one "postgres"?

**Comment by craig-osterhout** [comment]
Hi @xerosugar, thanks for sharing the issue.
It appears to be correct.
The first `postgres` is the image name, and the second `postgres` is the command/binary to run.

If you're wondering why just passing `--help` without the second `postgres` works, it's explained in the previous example of that topic, around the following sentence:
`This is useful because the image name can double as a reference to the binary ...`
