### ISSUE TITLE
--filter not supported for docker container prune <1.13

### ISSUE THREAD

**Issue by NewtonLiuNVIDIA** [docker/docker.github.io#1634]
File: [engine/reference/commandline/container_prune.md](https://docs.docker.com/engine/reference/commandline/container_prune/)

FYI - The --filter option does not work with docker version 1.13.0:

lab@newton-dgxstation:~$ sudo docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

lab@newton-dgxstation:~$ sudo docker container prune --filter "until=7d"
unknown flag: --filter
See 'docker container prune --help'.

**Comment by mstanleyjones** [comment]
This is actually an upstream issue.

**Comment by mstanleyjones** [comment]
We need to regenerate the CLI YAML for 1.13. We had just started using the YAML to reuse the same information about the CLI that is in the Docker code, and there were some bugs. Fingers crossed that I can do this. Otherwise, I will pull out the `--filter` reference here manually as it slipped in by accident.

**Comment by mstanleyjones** [comment]
Closed via #2789
