### ISSUE TITLE
host_integration: request to add script examples for Windows

### ISSUE THREAD

**Issue by Utkarsh-vishnoi** [docker/docker.github.io#1673]
File: [engine/admin/host_integration.md](https://docs.docker.com/engine/admin/host_integration/)
Add script examples for windows host also

**Comment by clocklear** [comment]
Claimed.

**Comment by mstanleyjones** [comment]
@thaJeztah do you have any thoughts on this?

**Comment by PatrickLang** [comment]
Here's a few approaches:

1. Create a scheduled task that runs at system boot
2. Create a scheduled task that runs at login. This could be nice if you wanted something like Jekyll running when you're logged in
3. Create a Windows service wrapper that translates service control manager requests to `docker run` and `docker stop` commands

1 & 2 are easy with https://msdn.microsoft.com/en-us/library/windows/desktop/bb736357(v=vs.85).aspx , but it lacks a proper `docker stop` when you reboot the system. I'm worried that `docker run --rm` won't actually delete a container automatically launched this way

3 is probably the best option but I haven't found an existing service wrapper that can run a command at system shutdown rather than stopping a process

**Comment by clocklear** [comment]
IMO, scheduled tasks are not the solution here.  The closest analog to `systemd`, `upstart`, or `supervisor` in the Windows world is a service, but without the ability to run separate commands for startup/shutdown in native services (read: non third-party assisted services), this isn't really a solution either.  It could be possible to do create a system service by using a third-party wrapper, but I hesitate to suggest a third-party solution (IMO that comes with its own challenges).

**Comment by mstanleyjones** [comment]
I suspect that this is outside the scope of Docker docs for now. :( Thanks for doing the research, @clocklear, you will get the points!
