### ISSUE TITLE
Docs were not supposed to take over specs

### ISSUE THREAD

**Issue by stevvooe** [docker/docker.github.io#182]
This spec still needs to be managed in the constituent project. Do not move it over.

https://github.com/docker/docker.github.io/tree/master/registry/spec

I was assured these would not be moved over. Not sure how this mistake was made.

**Comment by joaofnfernandes** [comment]
From what I can see, the `docs` directory was not removed yet from the `distribution` tree https://github.com/docker/distribution/tree/master/docs/spec.

PR docker/distribution#1985 deletes some content in the `docs` directory, but doesn't seem to delete the spec.
If we decide to delete the spec files from docker/docker.gihub.io, we will break links that have ~8000 monthly page views and are currently indexed by search engines.

**Comment by mstanleyjones** [comment]
So, the reference material that is maintained in the projects should get periodically refreshed in docs.github.io, by means of some kind of CI. @johndmulhausen knows about this requirement. The files will live in both places, but will only be maintained in the upstream projects.

I am carrying the PR in the `distribution` repo so that we can get it done even while John is on vacation. There's no other work to be done on this issue, so I'll close it.

**Comment by stevvooe** [comment]
Do we have a manifest of which documents are locally maintained versus which are upstreamed?

**Comment by mstanleyjones** [comment]
That's a great idea. We don't yet, but we will. Let us have a few days to figure out the right location and format for that manifest.
