### ISSUE TITLE
404 at: /compose/compose-file/compose-file/

### ISSUE THREAD

**Issue by mehdimahmoud** [docker/docker.github.io#1823]
Hi,

URL: https://docs.docker.com/compose/compose-file/ (Compose file version 3 reference)
issue : 
When I click on the "variable substitution" link (= https://docs.docker.com/compose/compose-file/compose-file/#variable-substitution) within Service configuration reference section, the appropriate page is missing. 
The link in Docker Compose Version 2 (= https://docs.docker.com/compose/compose-file/compose-file-v2/#variable-substitution) is working, not in version 3.

Thank you.

Mehdi.

**Comment by londoncalling** [comment]
Closing this issue now, as link to `variable substitution` is now fixed in https://docs.docker.com/compose/compose-file/ (it goes [here](https://docs.docker.com/compose/compose-file/#variable-substitution)) .

We are having some glitches with the new web design in that the links are going to a little below the headings, but we will work on that as a global issue. 

Thanks for the feedback.
