### ISSUE TITLE
github markdown not processed the same as docker.github.io markdown

### ISSUE THREAD

**Issue by andrewhsu** [docker/docker.github.io#189]
The way github processes markdown and shows the final rendered HTML is not the same as how the markdown is processed to show HTML on the final docker.github.io site.

For example, if you see the items in the section titled "Task 2" the ordered list is numbered correctly and the blocks of code are in their own grey background box:
https://github.com/docker/docker.github.io/blob/d53c6798c9f6b7046ae04277eb4d25ccffc1f0af/opensource/project/set-up-dev-env.md

However, the markdown is rendered on the final website with grey boxes behind each line. I think the problem starts at ordered list item number 2 in the section titled "Task 2":
https://docker.github.io/opensource/project/set-up-dev-env/

**Comment by sanscontext** [comment]
Hey @andrewhsu, thanks for the report. It looks like there's a set of code-block gates that's improperly closed, and that's causing the renderer some pain. This should be a quick fix.

**Comment by andrewhsu** [comment]
Is there a way to have the docker.github.io markdown processed the same way that github processes the markdown? It would make it convenient for people submitting PRs to preview the changes before it is actually rendered on the public web site.

Or...is there a way to preview the changes of a PR before it is pushed to production?

**Comment by mstanleyjones** [comment]
Github.com uses a totally different stylesheet to preview Markdown and it is very simplistic. To output docs.docker.com (and docker.github.io, since they are currently one and the same), we use Jekyll, which is a little more picky about indentation in lists. You can preview the docs by using `docker compose up` in the root of the docker.github.io repo. There are a couple of other ways to do it too. See the README at the top level of this repo for more details about them.

**Comment by sanscontext** [comment]
Hey @andrewhsu , I'll close this out, since it's fixed. (It took a second shot on my account - it turns out the new renderer is picky in ways I hadn't anticipated.) The page is a *lot* more readable now, and I suspect there are other pages with similar issues. Please keep reporting these if you see them!
