### ISSUE TITLE
Feedback for: engine/getstarted/last_page.md

### ISSUE THREAD

**Issue by skcodes** [docker/docker.github.io#1917]
File: [engine/getstarted/last_page.md](https://docs.docker.com/engine/getstarted/last_page/), CC: @mstanleyjones 
I hope I'm doing this correctly! The Learn More page looks really organized, but when you really try to determine where to go next, I feel it could really be improved. It needs to be more clear about what *order* you should do the tutorials in. I know web pages like to avoid implying order, but learning has prerequisites (dependencies) that require that you learn things in a certain order for them to make sense. So for example, Getting Started with Docker (for Mac or for Windows) should be first (or maybe the Information about the Docker product line). Beyond that, my suggestions may not be valid because I'm not sure what the order should be. Learn by example is described as "more advanced." "More advanced" than what? the Getting Started sections? everything else on the page? Also, there is a Docker Toolbox Overview. It is my understanding that this is a legacy tool that is no longer needed in many situations. That should be clear on this page. If that's not true, then there is other documentation somewhere that is misleading. Thanks for the work you do--hope this is helpful.

**Comment by mstanleyjones** [comment]
@londoncalling are you interested in tackling this one? @johndmulhausen does this dovetail with your Getting Started work?

**Comment by londoncalling** [comment]
@mstanleyjones yes, I'll do this right now, thanks

**Comment by londoncalling** [comment]
@skcodes @mstanleyjones I've updated "Learn more" per feedback, and hopefully clarified a suggested order to approach the tutorials and samples. 

It doesn't make sense to entirely put topics in order in the table because the ideal (and inferred) scenario is that by the time someone gets to this page, they have already 
a) installed Docker on their platform
b) walked through the Docker for Mac or Windows guides (and/or looked over at the Toolbox guide if referred to because they are on an older platform-it's  linked to from those guides)
c) have worked through the basics tutorial
d) are ready for the Swarm mode, multi-container tutorial. That's why that Swarm mode/multi-container tutorial is at the top of the table.

However, we can't assume that they've done all this, which is why I do want to provide links to the platform specific guides as well. It just doesn't make sense to put them first.

**Comment by londoncalling** [comment]
This is now addressed per #2615 . Thanks for the feedback @skcodes. Feel free to follow up on this thread or open a new issue if you have more comments.
