### ISSUE TITLE
Open source workflow: bring up-to-date, design proposal not a `docker/docker` label anymore

### ISSUE THREAD

**Issue by dsheets** [docker/docker.github.io#205]
At https://docs.docker.com/opensource/workflow/advanced-contributing/#/design-proposal, the design proposal PR link is broken (extra `%20`s) and no label `kind/proposal` exists in [docker/docker](https://github.com/docker/docker). This text is out-of-date or wrong.

**Comment by shubheksha** [comment]
I'll take this up!

**Comment by londoncalling** [comment]
@shubheksha , yeah this is a little confusing, but I do see something that needs fixing here. 

- Under the topic "Design Proposal" below the diagram, find step 2 ("Review existing issues and proposals to make sure no other user is proposing a similar idea.") Just below that step, there is this sentence with a link: "The design proposals are [all online in our GitHub pull requests](https://github.com/docker/docker/pulls?q=is%3Aopen+is%3Apr+label%3Akind%2Fproposal)."

Note that goes to `docker/docker` repo and is empty of PR's. That's because we moved the docs to a new repo. So both that link should be changed to link to the PR's in our new docs repo (`docker.github.io`): https://github.com/docker/docker.github.io/pulls

Does that make sense? The text for the link can probably stay the same. The URL should change. And maybe read through the page and check links to see if the rest of them make sense and work, but I think they do.

**Comment by shubheksha** [comment]
So we link it to all the PRs and not just one particular label?

**Comment by londoncalling** [comment]
I don't think we have to label the PRs at all. That was mistake. The issues
all have a label and then I would mention / link to the issue in your PR,
as you are already doing. Then you are good to go.

**Comment by shubheksha** [comment]
Updated the PR, PTAL :)

**Comment by londoncalling** [comment]
@shubheksha changes look great, just waiting for Netlify build .. not sure why it's slow. Will kick it soon, if it doesn't complete.
