### ISSUE TITLE
Feedback for: compose/bundles.md

### ISSUE THREAD

**Issue by chaynika** [docker/docker.github.io#2071]
File: [compose/bundles.md](https://docs.docker.com/compose/bundles/) 
When I opened the man page for docker using Google Chrome, I found that I was not able to scroll sideways to see right side of text. However, when I used Safari, sideways scrolling was working fine.

Following is a screenshot from my Google Chrome browser and I am not able to scroll sideways to see right side of text:
<img width="1269" alt="screen shot 2017-03-02 at 2 22 39 pm" src="https://cloud.githubusercontent.com/assets/18140730/23527786/8c24cea8-ff54-11e6-944b-c571e91c1e35.png">

Meanwhile, below is a screenshot from my Safari browser where sideways scrolling is working fine:
<img width="1280" alt="screen shot 2017-03-02 at 2 24 18 pm" src="https://cloud.githubusercontent.com/assets/18140730/23527847/bb61cbc6-ff54-11e6-8805-4642d3bac6b0.png">

I am assuming this might be the issue with other documentation pages also on Google Chrome.

**Comment by londoncalling** [comment]
@chaynika thanks for the feedback. We are working on bugs in the new design. You should find this improved from a few days ago. Please try again. Rather than scrolling sideways, the page contents should adjust to the size of your frame. 

Closing this issue for now, but if you don't detect improvement, please re-open.

@jsouth @johndmulhausen
