### ISSUE TITLE
404 at: /engine/installation/linux/repo_files/centos/docker.repo/

### ISSUE THREAD

**Issue by daniel-ng** [docker/docker.github.io#2080]
URL: /engine/installation/linux/repo_files/centos/docker.repo/

Using old documentation to install Docker Engine from 1.13 repo fails with 404.

Related to https://github.com/docker/docker.github.io/issues/2081

**Comment by mstanleyjones** [comment]
Hi @daniel-ng  , sorry you are running into this 404. The installation instructions have changed in the `master` docs and these files are no longer used. In fact, they are only used for Docker 1.13.0 and Docker 1.13.1. If you want to install 1.13, you can use the archived installation instructions at https://docs.docker.com/v1.13/engine/installation/linux/rhel/. The URL to the `docker.repo` in that file is currently incorrect too, because #2133 has not yet been published (expected it within half an hour). In the meantime, the correct URL to the `docker.repo` is:

```
https://docs.docker.com/v1.13/engine/installation/linux/repo_files/centos/docker.repo
```

I'm going to go ahead and close this because the fix has already been pushed.
