### ISSUE TITLE
Feedback for: engine/installation/linux/rhel.md

### ISSUE THREAD

**Issue by daniel-ng** [docker/docker.github.io#2081]
File: [engine/installation/linux/rhel.md](https://docs.docker.com/engine/installation/linux/rhel/), CC: @mstanleyjones 

URL for adding the yum repo states https://docs.docker.com/engine/installation/linux/repo_files/centos/docker.repo, but that doesn't exist. It leads to a 404. Is there a new URL that contains the 1.13 repo information?

**Comment by mstanleyjones** [comment]
Hi @daniel-ng  , sorry you are running into this 404. The installation instructions have changed in the `master` docs and these files are no longer used. In fact, they are only used for Docker 1.13.0 and Docker 1.13.1. If you want to install 1.13, you can use the archived installation instructions at https://docs.docker.com/v1.13/engine/installation/linux/rhel/. The URL to the `docker.repo` in that file is currently incorrect too, because #2133 has not yet been published (expected it within half an hour). In the meantime, the correct URL to the `docker.repo` is:

```
https://docs.docker.com/v1.13/engine/installation/linux/repo_files/centos/docker.repo
```

I'm going to go ahead and close this because the fix has already been pushed.
