### ISSUE TITLE
Remove unnecessary step in Linux post-install

### ISSUE THREAD

**Issue by roipoussiere** [docker/docker.github.io#2109]
File: [engine/installation/linux/linux-postinstall.md](https://docs.docker.com/engine/installation/linux/linux-postinstall/)

> Create the docker group.
> 
>     sudo groupadd docker

This step is not required since the `docker` group has already been created.

**Comment by mstanleyjones** [comment]
That's not true in every Linux distribution. It's better to tell people to install it, just in case they need to.

**Comment by bermudezmt** [comment]
@roipoussiere thank you for reporting this issue. I'm reopening it so we can get it addressed.

**Comment by rolfedh** [comment]
@bermudezmt @mistyhacks: It looks like @shampabh is inactive. I'd like to resolve this issue. Are we certain that installing docker always creates a docker group? If so, I'll remove the extra step. Otherwise, if we're not sure, let's keep the extra step (harmless) and close this issue. What do you think?

**Comment by roipoussiere** [comment]
> Are we certain that installing docker always creates a docker group?

Docker did it each time I installed it, but I'm not sure it's the case on every OS.

**Comment by craig-osterhout** [comment]
Closing this issue as stale. If you feel this is worth revisiting, please let us know.
