### ISSUE TITLE
Feedback for: engine/tutorials/dockerizing.md

### ISSUE THREAD

**Issue by droa** [docker/docker.github.io#211]
URL: [https://docs.docker.com/engine/tutorials/dockerizing.md](https://docs.docker.com/engine/tutorials/dockerizing/)

The name "insane_babbage" was never assigned to the container, was it?...

**Comment by joaofnfernandes** [comment]
If you run `docker run` without specifying the `--name` flag, a random name is assigned to the container, to make it easier to refer to id, instead of it's hash. The example in the docs has that name, but since this is random, your container will be assigned a different name.

Closing this issue, since there's nothing to improve.
