### ISSUE TITLE
Why is there no UI?

### ISSUE THREAD

**Issue by 030** [docker/docker.github.io#2124]
The registry:2 container is started, but no UI is shown when one navigates to localhost:5000

**Comment by joaofnfernandes** [comment]
Docker Registry is a backend service and doesn't have any web UI.

You can continue learning about Docker Registry [here](https://docs.docker.com/registry/deploying/). If you're looking for a registry with a management UI, maybe take a look into [Docker Trusted Registry](https://docs.docker.com/datacenter/dtr/2.2/guides/user/manage-images/).

I'm closing this issue since it doesn't report anything we can improve on docs.docker.com. Feel free to open more issues if you find anything wrong with docs.docker.com 🐳
