### ISSUE TITLE
Feedback for: docker-for-mac/index.md

### ISSUE THREAD

**Issue by s0nny78** [docker/docker.github.io#2128]
File: [docker-for-mac/index.md](https://docs.docker.com/docker-for-mac/)

docker rmi followed by an image ID or image name. For example, docker rmi nginx
=>
docker rmi followed by an image ID or image name. For example, docker rmi 77af4d6b9913

**Comment by londoncalling** [comment]
@s0nny78 the example is providing an image name, since we gave a name to it in the previous steps with:

`docker run -d -p 80:80 --name webserver nginx`

then, `docker rmi nginx` should work. I didn't want to use the ID as an example, since everyone's ID will be different.

Closing this for now, but let me know if this doesn't make sense to you or if the example, as given didn't work for you.
