### ISSUE TITLE
Open Source: verify and update "Work with development container" topic

### ISSUE THREAD

**Issue by jamiethermo** [docker/docker.github.io#218]
URL: [https://docs.docker.com/opensource/project/set-up-dev-env.md](https://docs.docker.com/opensource/project/set-up-dev-env/)

I followed these instructions and it appears to suggest that I can edit the source tree on my host machine, and the changes will be reflected in the "running development container". This was not the case. Only the docker/bundles directory was mapped. Did I do something wrong?

> Running the make shell command mounted your local Docker repository source into your Docker container. 

I notice that when I run make shell, I see this line:

`Step 48 : COPY . /go/src/github.com/docker/docker
`
Which suggests that I should not be able to see changes reflected in the development container.

**Comment by jamiethermo** [comment]
The next page ("Run tests") provides this command, which worked as expected:
```
docker run --privileged --rm -ti -v `pwd`:/go/src/github.com/docker/docker dry-run-test /bin/bash
```

**Comment by londoncalling** [comment]
### Hints for Hackathon

Let's test whether there is any problem with running the commands as mentioned in the first comment on this issue. And, at the same time, let's bring this topic up-to-date. The tasks are still valid, but some things have changed with Docker products since this was written.

1. Work through the procedures in the topic: [Work with a development container](url). (You will need to start with [Configure Git for contributing](https://docs.docker.com/opensource/project/set-up-git/), as referenced in the intro.)

2. Under [Task 1: Remove images and containers](https://docs.docker.com/opensource/project/set-up-dev-env/#task-1-remove-images-and-containers), in the intro there is a reference to Docker Machine and macOS that isn't really relevant anymore. You can work through this task the same way on Docker for Mac, Docker for Windows, and Docker for Linux. Make the appropriate text updates so that this makes sense now.

3. Under [Task 2: Start a development container](https://docs.docker.com/opensource/project/set-up-dev-env/#task-2-start-a-development-container), step 4, there is a line that says `The command returns informational messages as it runs. The first build may take a few minutes to create an image. ` The build takes quite a while (around 5 or more minutes). If you think this needs to be more fully clarified so that people don't think it isn't working, add some text here.

4. Under that same section, steps 9-12 require that you hit return to get your prompt back. You might want to add a mention of this in the docs so people aren't thrown by this.

5. Under Task 3: Make a code change, everything should work but you might get an error message `Text file busy` when you copy the bundles again. If you think this will throw someone off, mention this in the procedure.

```
root@170c7dc8625b:/go/src/github.com/docker/docker# hack/make.sh binary

bundles/17.05.0-dev already exists. Removing.

---> Making bundle: binary (in bundles/17.05.0-dev/binary)
Building: bundles/17.05.0-dev/binary-client/docker-17.05.0-dev
Created binary: bundles/17.05.0-dev/binary-client/docker-17.05.0-dev
Building: bundles/17.05.0-dev/binary-daemon/dockerd-17.05.0-dev
Created binary: bundles/17.05.0-dev/binary-daemon/dockerd-17.05.0-dev
Copying nested executables into bundles/17.05.0-dev/binary-daemon

root@170c7dc8625b:/go/src/github.com/docker/docker# cp bundles/17.05.0-dev/binary-client/docker* /usr/bin/
root@170c7dc8625b:/go/src/github.com/docker/docker# cp bundles/17.05.0-dev/binary-daemon/docker* /usr/bin/
cp: cannot create regular file '/usr/bin/dockerd': Text file busy
```

6. When you run the next step, they should see the change they made to they made to `attach.go` as expected (so you don't want users giving up when they see that `text file busy` error message):

```
root@170c7dc8625b:/go/src/github.com/docker/docker# docker attach --help
DEBU[0785] Calling GET /_ping                           

Usage:	docker attach [OPTIONS] CONTAINER

Attach local standard input, output, and error streams to a running container

Options:
      --detach-keys string   Override the key sequence for detaching a container
      --help                 Print usage
      --no-stdin             Do not attach STDIN (standard in)
      --sig-proxy            Proxy all received signals to the process (default true)
```

7. You might want to add some text at the end to tell people to exit from the container. (You can type `exit` or `Control-D` to exit the container.)

**Comment by johnharris85** [comment]
I'll take a look / claim this one :)

**Comment by londoncalling** [comment]
@johnharris85 , great! thanks!

**Comment by johnharris85** [comment]
OK, so not sure if these were edited since the original issue log, but there are a couple of things at work here which can be kind of confusing. It says the local code will be 'mounted' however the Dockerfile shows a `COPY`. This is a little bit of a red herring, as in the actual `make BIND_DIR=. shell` _will_ mount the local directory into the development container. So in future instructions where it says that changes on the host will be reflected in the container, that's actually correct. Will make edits to the other pieces and maybe a line to clarify this just in case.
