### ISSUE TITLE
Minor typo causing image not to display

### ISSUE THREAD

**Issue by gdvalderrama** [docker/docker.github.io#2221]
### Problem description

In the docker-for-mac install page, a missing closing parenthesis (")") results in an image not being displayed.

### Problem location

The URL: https://docs.docker.com/docker-for-mac/install/#install-and-run-docker-for-mac

### Suggestions for a fix

Simply fix the typo by adding the closing parenthesis, such that the original:

`![Docker app in Hockeyapp](/docker-for-mac/images/docker-app-in-apps.png`

is changed by:

`![Docker app in Hockeyapp](/docker-for-mac/images/docker-app-in-apps.png)`

**Comment by joaofnfernandes** [comment]
Thanks for letting us know about this 🐳
For small things like this, the time it takes to create the issue is the same time it takes to fix it. So let me show you how to fix issues like this

![example](https://cloud.githubusercontent.com/assets/1525937/23807483/bcd0e95c-057a-11e7-96f9-773dbe98d85c.gif)

**Comment by gdvalderrama** [comment]
Right thanks!
On clicking the "Edit this page" button I got the message:

> You need to fork this repository to propose changes.
> Sorry, you’re not able to edit this repository directly— you need to fork it and propose your changes from there instead.

Which seemed more of a hassle than creating the issue.
I'll keep it in mind though ;)
