### ISSUE TITLE
Error running nginx container on macOS

### ISSUE THREAD

**Issue by geoidesic** [docker/docker.github.io#2223]
File: [docker-for-mac/index.md](https://docs.docker.com/docker-for-mac/)

`docker run -d -p 80:80 --name webserver nginx`

This command does not work. gives error:
`docker: Error response from daemon: driver failed programming external connectivity on endpoint webserver (b88a3fa7eccd56ae3a688927c8295e3e23916a3c70d40e8a2160912c6602082a): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE).`

**Comment by unbreakableIce** [comment]
#dibs for hackathon

**Comment by vishnu-narayanan** [comment]
This might happen mainly due to two reason.
1. There is a container/process using port 80.
Run `netstat -ntlp` to see if port 80 is used.
2. The Docker was not invoked in privileged mode which prevents docker daemon to have networking privileges. Follow the instructions, in [documentation](https://docs.docker.com/docker-for-mac/install/#install-and-run-docker-for-mac) to invoke docker in privileged mode.

     Ref: https://docs.docker.com/docker-for-mac/install/#install-and-run-docker-for-mac

**Comment by vishnu-narayanan** [comment]
Requesting to close the issue @JimGalasyn @geoidesic @mstanleyjones @unbreakableIce

**Comment by unbreakableIce** [comment]
I agree with @vishnu-narayanan  to close this issue . This seems to be an local to the user. I was able to successfully run the command and get the webserver response shown in the documentation .

**Comment by mstanleyjones** [comment]
Thanks @vishnu-narayanan !

**Comment by londoncalling** [comment]
Points to @vishnu-narayanan on this one for verifying.
