### ISSUE TITLE
Many commits for Docker Machine docs are lost

### ISSUE THREAD

**Issue by twang2218** [docker/docker.github.io#229]
I just realized my commit docker/machine@9375573 at Aug 8 is lost,  it might because the docs migration. 

And I checked a few others' commits, such as docker/machine@703f6d9c7 at Aug 6, docker/machine@8b5e7536 at Aug 22, they are missing too.

Could you have look? is there anything wrong?

**Comment by mstanleyjones** [comment]
@twang2218 please take a look at #416. I think that has everything. The problem was that the tag we imported was missing 79 commits, 29 of which affected docs. Some of those commits were from well before Sep 29, so however the tag was created, it just missed them. This means they never would have even been published before the migration either.

**Comment by twang2218** [comment]
As #416 and #423 have been merged, I'm going to close this one.
