### ISSUE TITLE
Feedback for: datacenter/ucp/1.1/installation/uninstall.md

### ISSUE THREAD

**Issue by ekitagawa** [docker/docker.github.io#2315]
File: [datacenter/ucp/1.1/installation/uninstall.md](https://docs.docker.com/datacenter/ucp/1.1/installation/uninstall/)

I get errors below with the example on this page.  Maybe, this page needs to be updated?
 
> FATA[0000] The uninstall command is **no longer used**. **Use the 'uninstall-ucp'
> command to uninstall UCP**, or the 'docker swarm leave' and 'docker node rm' commands to
> remove nodes from the swarm.

**Comment by joaofnfernandes** [comment]
You're looking at the uninstall page for UCP 1.1, but I think you're running a more recent version like`docker/ucp:2.0.0`.

Try checking out:
* [The docs for 2.1](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/install/uninstall/)
* [The docs for 2.0](https://docs.docker.com/datacenter/ucp/2.0/guides/installation/uninstall/)

I'm going to close this issue since there doesn't seem to be a problem with the docs, but feel free to comment here if you find something wrong and I'll reopen it, or create a new one.

Thanks for spotting problems with our docs 🐳🎖

**Comment by ekitagawa** [comment]
Thank you Joao!  I should have double check the contents before commenting to the wrong version.

**Comment by joaofnfernandes** [comment]
Nops, this is also on us. When you're looking at a page it's not obvious if you're reading docs for UCP 1.1, 2.0, or 2.1.
