### ISSUE TITLE
Docker for Azure: Need help setting up Cloudstor

### ISSUE THREAD

**Issue by joostvdg** [docker/docker.github.io#2346]
File: [docker-for-azure/persistent-data-volumes.md](https://docs.docker.com/docker-for-azure/persistent-data-volumes/)

What if it isn't preinstalled? 
- How to install it?
- How to configure it?

"Err": "create sharedvol1: Post http://%2Frun%2Fdocker%2Fplugins%2Fa8ee0bc7705ce425d5577538214b6b07fbf52b4210ca5f9df5223e8b13ddcaa6%2Fcloudstor.sock/VolumeDriver.Create: dial unix /run/docker/plugins/a8ee0bc7705ce425d5577538214b6b07fbf52b4210ca5f9df5223e8b13ddcaa6/cloudstor.sock: connect: no such file or directory",

**Comment by vovimayhem** [comment]
Also, I'd wish to know how can I configure it, and specifically, how to configure - if allowed - the ownership of the volume.

I tried to use it for the rabbitmq image, but it blew up on my face because the ownership of the files stored on it must be changed to the rabbitmq user, but they just won't change.

**Comment by mstanleyjones** [comment]
This was fixed in #3708
