### ISSUE TITLE
Post install, desktop Linux users need to completely log out of their x-window session

### ISSUE THREAD

**Issue by nickjj** [docker/docker.github.io#2427]
File: [engine/installation/linux/linux-postinstall.md](https://docs.docker.com/engine/installation/linux/linux-postinstall/)

####  Manage Docker as a non-root user

Step 3 mentions that you need to log out and log back in which is technically correct but it can be confusing to new users because if they are running a desktop version of Linux they will need to completely log out of their x-window session (not just reload or close their terminal) for it to take effect.

Can step 3 be re-worded to make that more clear?

Alternatively, according to a [stackoverflow answer I read](https://superuser.com/a/354475), you can get around step 3 entirely by running `su - $USER`. Maybe that could replace step 3 with its own description?

**Comment by shubheksha** [comment]
I'll take this one up!
@johndmulhausen & @mstanleyjones -- Do I need to incorporate both the suggestions mentioned in the description or only the second one?

**Comment by londoncalling** [comment]
Hey @shubheksha I just chatted with @mstanleyjones and she wants to leave the instructions more or less as is since it's the safest way and theoretically there are numerous ways you can do this. So let's use his first suggestion (not the second). Here is what I'd suggest for a PR on this:

1. On step 3, add a second sentence as a  parenthetical remark or an indented tip or paragraph. (On a desktop version of Linux, log out of your X Window session completely and then log back in.)

2. Fix the typo in step 4 that I happened to see, it's missing the word "run". (Change: Verify that you can docker commands without sudo. --> Verify that you can **_run_** docker commands without sudo.)

Let me know if you need help regarding formatting of `1.` (adding the tip or clarification)

**Comment by shubheksha** [comment]
@londoncalling, updated the PR :)

**Comment by nickjj** [comment]
Looks good, thanks.

I don't know what your formatting rules are for documentation but you might want to re-consider the parenthesis so it matches the remark on virtual machines. In this case, the VM tip doesn't have parenthesis and the desktop Linux tip does.

**Comment by londoncalling** [comment]
@nickjj thanks, I'll make this tweak now

**Comment by londoncalling** [comment]
@nickjj done in new PR ^^ , thanks much

**Comment by nickjj** [comment]
Awesome, good job everyone.
