### ISSUE TITLE
Compose install instructions for Linux are unclear

### ISSUE THREAD

**Issue by wotanii** [docker/docker.github.io#2435]
File: [compose/install.md](https://docs.docker.com/compose/install/)

it should be mentioned, that docker-compose can be installed with `sudo apt install docker-compose` on ubuntu. 

After reading this article (and several other) I assumed you always had to build it from source, because for some reason it isn't in the official repositories.

**Comment by johndmulhausen** [comment]
You're supposed to get the binaries from GitHub using the command there https://github.com/docker/compose/releases

The docs should make this more clear

**Comment by londoncalling** [comment]
### Hackathon Hints

Update the Compose install doc to make it flow better, and to clarify that:

- Docker for Mac, Docker for Windows, _and_ Docker Toolbox (the only one mentioned in step 2) installs Compose as part of those suites (along with Docker Engine and Docker Machine). 

- Integrate the comments above ^^ from @johndmulhausen and @wotanii 

This is really an update of the doc to incorporate the new product offerings and paradigm, where the task to "install Docker Engine" is only a prerequisite on Linux, since for Docker for Mac/Windows, and Toolbox, Engine, Compose, and Machine are all installed automatically.

**Comment by shubheksha** [comment]
I'll take this up!

**Comment by joaofnfernandes** [comment]
Currently `apt-get install` installs compose 1.5, which is pretty hold. So we should not be recommending people do get compose that way. @wotanii the docs are sending to github, but you don't need to build compose from source. You [can go to the releases page](https://github.com/docker/compose/releases) and download the binary.

**Comment by johndmulhausen** [comment]
Points to @shubheksha -- thanks for being responsive to the review feedback. 👍
