### ISSUE TITLE
Feedback for: docker-for-windows/install.md

### ISSUE THREAD

**Issue by damienwebdev** [docker/docker.github.io#2451]
File: [docker-for-windows/install.md](https://docs.docker.com/docker-for-windows/install/)

It would be nice if we could get checksums for the the InstallDocker.msi. My IT team won't let me install without it,

**Comment by damienwebdev** [comment]
#2245 #2178

 I think this seems like a major step backwards from a security perspective. Checksums should be mandatory, not something that's just removed lightly. Granted, from looking at the PR and issue, this seems like they were outdated and most likely causing some confusion, but that doesn't indicate that they should be removed. 

In a perfect world, the checksums being out of date causes everyone's builds to fail, and this gets noticed as a bigger problem than "lets hide them from the docs and hope no one notices". This is a security issue first and foremost and should be an automated part of your internal build process and ideally involve literally no human intervention.

I still see that the links are up, just no longer in the docs:

https://download.docker.com/mac/stable/Docker.dmg.sha256sum
https://download.docker.com/win/stable/InstallDocker.msi.sha256sum

**Comment by londoncalling** [comment]
@JimGalasyn @FrenchBen @jeanlaurent @friism @nandhini

 We temporarily removed the SHA checksums from the d4mac , d4win installer downloads in the docs because they were stale. Do you guys want to recreate these and start using them? 

The issue will be that:

- we are _not_ using them anywhere on Docker Store that I can see (e.g., https://store.docker.com/editions/community/docker-ce-desktop-windows and https://store.docker.com/editions/community/docker-ce-desktop-mac), so we probably would want to be consistent and use them everywhere we provide downloads

- we would need to rev them

**Comment by FrenchBen** [comment]
@londoncalling the links provided by @damienwebdev are correct and will always be updated with the latest release:
https://download.docker.com/mac/stable/Docker.dmg.sha256sum
https://download.docker.com/win/stable/InstallDocker.msi.sha256sum

The links along with the text should remain in the docs.

**Comment by londoncalling** [comment]
@FrenchBen Thanks I'll add them back in

**Comment by johndmulhausen** [comment]
Checksums have been added back; closing issue
