### ISSUE TITLE
Documentation pages are blank

### ISSUE THREAD

**Issue by hlandau** [docker/docker.github.io#247]
### Problem description

Most documentation pages on [docs.docker.com](https://docs.docker.com/) are blank pages, containing no content.

### Reproduction

1. Navigate to https://docs.docker.com/.
2. Follow a link, e.g. "Write a Dockerfile" to https://docs.docker.com/engine/getstarted/step_four.md.
3. The loaded page is blank.

Browser: links2.

![screen-20161018062516](https://cloud.githubusercontent.com/assets/2270010/19465395/c636f1e8-94fb-11e6-8a03-55e81e16cf61.png)

**Comment by johndmulhausen** [comment]
@hlandau Can't reproduce; can you tell me what browser you're using?

**Comment by hlandau** [comment]
links2.

**Comment by danix800** [comment]
@hlandau This is really uncommon since links is not that widely used. 

You might check this [SSL/TLS error with links and lynx](http://askubuntu.com/questions/776315/ssl-tls-error-with-links-and-lynx-possibly-due-to-cloudflare). I have 2.8 version installed. It says "SSL error", as the above link pointed out.

If updated to 2.13, it works, so if this is the only browser you can use, update it and good luck!

**Comment by danix800** [comment]
Try `https://docs.docker.com/engine/getstarted/step_four/`, not `https://docs.docker.com/engine/getstarted/step_four.md`.

**Comment by hlandau** [comment]
That works, but everything links to `.md`, not `/`.

**Comment by johndmulhausen** [comment]
If you are in a non-links browser, we actually catch links to `.md` and change them to `/`

Regardless of that, I've added logic to 404.md that catches attempts to use a `.md` URL and forwards you to the equivalent `/` URL with forwarding logic. Can you try clicking on https://docs.docker.com/engine/getstarted/step_four.md in links and let me know if you get forwarded?

**Comment by hlandau** [comment]
Nope, still blank.

**Comment by johndmulhausen** [comment]
Well, we've done all we can. Any redirect solution we have available to us is going to use <meta refresh> or window.location.replace, and currently we're doing both just so that as many browsers as possible get redirected. I'm afraid we have to say that Links is not supported. In fact I'd suspect that there are many things are are broken besides this issue in text-only browsers that have no JS support. If you need to use a text-based browser, here is a Stack Overflow topic on text-based browsers that have JavaScript support: 

http://askubuntu.com/questions/34687/is-there-a-text-mode-browser-which-supports-javascript
