### ISSUE TITLE
carry Content Trust guide from ucp 2.0 to latest version

### ISSUE THREAD

**Issue by riyazdf** [docker/docker.github.io#2626]
### Problem description

We should have the UCP 2.0.x [Content Trust docs](https://docs.docker.com/datacenter/ucp/2.0/guides/content-trust) that detail signing policy carried forward to the latest docs location.

### Problem location

https://docs.docker.com/datacenter/ucp/2.0/guides/content-trust should also be on the "User Guides" section of latest UCP (ex: https://docs.docker.com/datacenter/ucp/2.1/guides/user/secrets/)

### Project version(s) affected

UCP Latest (2.1.x)

### Suggestions for a fix

Should be able to copy the guide verbatim into the new user guides directory; the flow and instructions are the same.

**Comment by joaofnfernandes** [comment]
For the latest releases of UCP and DTR we revamped these articles, so while the content exists it is now spread across multiple places.

* [Run only images you trust](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/configure/run-only-the-images-you-trust/)
* [Configure your Docker engine](https://docs.docker.com/datacenter/dtr/2.2/guides/user/access-dtr/)
* [Configure your Notary client](https://docs.docker.com/datacenter/dtr/2.2/guides/user/access-dtr/configure-your-notary-client/)
* [Sign an image](https://docs.docker.com/datacenter/dtr/2.2/guides/user/manage-images/sign-images/)
* [Delegate image signing](https://docs.docker.com/datacenter/dtr/2.2/guides/user/manage-images/sign-images/delegate-image-signing/)
* [Manage trusted repositories](https://docs.docker.com/datacenter/dtr/2.2/guides/user/manage-images/sign-images/manage-trusted-repositories/#where-to-go-next)

Since the content exists, I'm closing this issue. Feel free to open a new one if you notice that we're missing content or that the content we have is difficult to find.

**Comment by joaofnfernandes** [comment]
It looks like #2656 had already tried to address this, so I'll take a look and check if we should revert it.
