### ISSUE TITLE
UCP architecture - a bit confusing UCP Worker/Manager/Nodes

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#2637]
File: [datacenter/ucp/2.1/guides/architecture.md](https://docs.docker.com/datacenter/ucp/2.1/guides/architecture/), CC @joaofnfernandes

I feel that there is some confusing terminology in the ucp system architecture documentation
In the first diagram you say that its a UCP is a container based application running on top of docker engine which makes sense.
https://docs.docker.com/datacenter/ucp/2.1/guides/images/architecture-1.svg

The next diagram is very confusing.
What i know a swarm is a set of docker engines running in swarm mode. Some or managers some are workers. Then they say a bit vauge that the "node" is a manager / worker.

UCP Agent has two modes of operation as i understand:
   - Worker Mode
      - Serves docker commands to other ucp services only authorized users.
   - Manager Mode
      - Serves all UCP components including the UCP Web UI and data stores.
    
UCP Worker orange box:
   Is it a representation of the UCP agent working in "UCP Worker" mode ?
UCP Manager green box:
   Is it a representation of the UCP agent working in "UCP Manager" mode ? 
 
I'm tried before to look for the actual "UCP Worker or Manager" component in the container table.... 

// Marten

**Comment by joaofnfernandes** [comment]
We can definitely improve that article, but here's a lightweight explanation to clarify things a bit

* `Node` is physical or virtual machine that is running Docker. In this case Docker CS Engine. The diagram needs to be updated to say Docker Enterprise Edition instead of CS Engine.
* `Swarm` is a collection of `nodes` that are in the same Docker swarm. These machines form a cluster
* Nodes that are part of a swarm can either be `managers` or `workers`. [Learn more here](https://docs.docker.com/engine/swarm/how-swarm-mode-works/nodes/#manager-nodes)
* You install UCP on a swarm of Docker nodes. If you're not running a swam, when installing UCP it will configure that node to be running in swarm mode
* When you install UCP on a swarm it starts a `ucp agent` service on all nodes of that swarm. that service monitors the node and ensures it is running other UCP components. If the node is a manager, the UCP agent [deploys several containers](https://docs.docker.com/datacenter/ucp/2.1/guides/architecture/#ucp-components-in-manager-nodes). If the node is a worker, the agent will only deploy a [subset of them](https://docs.docker.com/datacenter/ucp/2.1/guides/architecture/#ucp-components-in-worker-nodes).

Let me know if this still didn't help you understand the architecture of UCP.

**Comment by wcgcoder** [comment]
#dibs I'd like to claim this bug.

**Comment by mstanleyjones** [comment]
@wcgcoder please don't use issue numbers in the commit messages themselves, but reference it when you open the PR, as `Fixes #2637`. Please make sure to amend your commit messages before creating the PR.

**Comment by wcgcoder** [comment]
@mstanleyjones I've already submitted the PR and have been working with @joaofnfernandes on the issue. At first glance, it looks like I'd need to recreate the PR as I can't find a way of editing the messages within github, and I don't know how a force push with the modified messages would look in github. 

What do you think I should do?

Also, if you could be so kind as to explain why you don't what the issue numbers in commit message, I'd be quite thankful. I haven't had much guidance on working on larger projects with many contributors.

**Comment by martencassel** [comment]
The new diagram and UCP cluster definition is much more brief and less overwhelming. 
Its also better aligned with the other terminology and description of UCP and its architecture in the reference architecture docs.

If the goal of a person who wants to setup UCP this brief overview of the system is good.. but i assume at first glans one would skim the list of internal containers... and then jump into the next section of installation. Before this update the initial architecture overview felt a bit too overwhelming.

I still think the detailed zoom in on the ucp topology of component containers is a bit too much. Maybe a functional decomposition description would help if one would like to understand the functionality and get a brief understanding on what components does what in a not too detailed way.
This list of containers could be useful later for reference after one learn more about the system.

Just recently i setup UCP and DTR with the docs by my side and i got confused for a moment what with DTR installer terminology not being consistent with the architectural terminiology. Especially the ucp-node option in the DTR installer.

I sense that the intent of UCP and DTR installation design is to be able to deploy the system from a POC or non-production state... (self signed certs, simplified storage etc) and then later extend to it to a production state.  I found this earlier article: https://docs.docker.com/datacenter/ucp/1.1/install-sandbox/

It would be good you had a "story" about how to transition from non-prod state to production and explain this... strategy for deployment.

**Comment by londoncalling** [comment]
cc'ing @joaofnfernandes @JimGalasyn per the last comments by @martencassel above, in case you want to open a new issue or address this further.
