### ISSUE TITLE
group_add option doesn't work as described

### ISSUE THREAD

**Issue by psoares** [docker/docker.github.io#2679]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/#groupadd), CC @londoncalling

The group_add option is described as being a second level property, right under "services". This option doesn't work. Please note I also tried to put it nested under a service, and it didn't work either, so for now I don't really know what the documentation should read.

See my comment on ticket [#3328](https://github.com/docker/compose/issues/3328)

**Comment by londoncalling** [comment]
@dnephin @shin- @nathanleclaire @ManoMarks Can you all take a look at the above comment, and also the referenced issue [#3328](https://github.com/docker/compose/issues/3328). It sounds like from the discussions that `group_add` is not working in Compose?

**Comment by shin-** [comment]
`group_add` works fine in Compose, but that example snippet is indeed wrong. It should be something like:

```yaml
version: '2'
services:
  myservice:
    image: alpine
    group_add:
      - mail
```

**Comment by shin-** [comment]
@londoncalling If you're working on this change, it might be a good occasion to remove `group_add` from the v3 docs as well, since it's only a valid option in v2.

**Comment by londoncalling** [comment]
@shin- oh!? okay, thanks

**Comment by londoncalling** [comment]
@shin- on issue [#3328](https://github.com/docker/compose/issues/3328) psoare's seems to have tried this format as a [second try](https://github.com/docker/compose/issues/3328#issuecomment-292347600) and says it didn't work ...?

**Comment by psoares** [comment]
I confirm this works on version 2 and not on version 3.

**Comment by londoncalling** [comment]
@psoares thanks for the feedback, the docs updates are published now, so I'm going to close this issue. Feel free to re-open the discussion or a new issue if you find something else. 
-  [`group_add` example](https://docs.docker.com/compose/compose-file/compose-file-v2/#groupadd) should be correct now for Compose v2
- it's been removed from [Compose v3](https://docs.docker.com/compose/compose-file/) (since it's a v2 only thing)
- [Versioning details](https://docs.docker.com/compose/compose-file/compose-versioning/#version-3) have been updated
- More details are in the referenced PR #2684

**Comment by Toilal** [comment]
What's the alternative if user need `group_add` in a version 3 compose file ? Should it be handled manually in Dockerfile ?
