### ISSUE TITLE
Feedback for: engine/userguide/networking/default_network/build-bridges.md

### ISSUE THREAD

**Issue by buildshiprun** [docker/docker.github.io#268]
URL: [https://docs.docker.com/engine/userguide/networking/default_network/build-bridges.md](https://docs.docker.com/engine/userguide/networking/default_network/build-bridges/)

I couldn't get it working as the instruction tells, is the documentation obsoleted?

**Comment by mstanleyjones** [comment]
Hi @buildshiprun, can you give me some more info about what step went wrong and what happened? What version of Docker are you running? Thanks for the details.

**Comment by fengzhimei** [comment]
hi @mstanleyjones, the issue is after running this cmd - `sudo service docker start`, the docker0 will come back again, and `sudo iptables -t nat -L -n` still shows the ip range assigned by docker0.

I'm running version 1.12.3 of docker on Ubuntu 16.04, I also tried to edit /lib/systemd/system/docker.service with this change `EnvironmentFile=-/etc/default/docker`, but doesn't seem to work either.

**Comment by buildshiprun** [comment]
hi @mstanleyjones, the issue is after running this cmd - sudo service docker start, the docker0 will come back again, and sudo iptables -t nat -L -n still shows the ip range assigned by docker0.

I'm running version 1.12.3 of docker on Ubuntu 16.04, I also tried to edit /lib/systemd/system/docker.service with this change EnvironmentFile=-/etc/default/docker, but doesn't seem to work either.

**Comment by buildshiprun** [comment]
hi @mstanleyjones, the issue is after running this cmd - `sudo service docker start`, the `docker0` will come back again, and `sudo iptables -t nat -L -n` still shows the ip range assigned by `docker0`.

I'm running version 1.12.3 of docker on Ubuntu 16.04, I also tried to edit `/lib/systemd/system/docker.service` with this change `EnvironmentFile=-/etc/default/docker`, but doesn't seem to work either.

**Comment by buildshiprun** [comment]
Hi @mstanleyjones, I figured it out, as what explained in https://docs.docker.com/engine/admin/systemd/, since I am using Ubuntu 16.04, I have to use the following to make custom options,

    ExecStart=
    ExecStart=/usr/bin/dockerd $CUSTOM_OPTIONS

But I think the documentation still need to be updated, because 1) the documentation is not quite applicable to systemd; 2) `docker0` will be created when docker daemon starts, so there is no necessary to remove docker0 interface.

Please correct me if I was wrong.

**Comment by mstanleyjones** [comment]
Hi, the `$DOCKER_OPTS` is not the recommended way to configure the Docker daemon in Ubuntu anymore, because there are so many inconsistencies between `upstart` and `systemd`. See https://github.com/docker/docker.github.io/pull/640/files#diff-61f63d6ae2b5703de532b1175c11099cR493 or wait a few more minutes for the changes to be live on https://docs.docker.com/engine/installation/linux/ubuntulinux/, and let me know if this solves your problem more cleanly. Thanks for your patience!
