### ISSUE TITLE
Feedback for: engine/reference/commandline/logs.md

### ISSUE THREAD

**Issue by drduke1** [docker/docker.github.io#293]
URL: [https://docs.docker.com/engine/reference/commandline/logs.md](https://docs.docker.com/engine/reference/commandline/logs/)

Can we get an example log or the format of the log?

**Comment by mstanleyjones** [comment]
`docker logs` reads the STDERR and STDOUT for the container's final process, by default. So the answer to your question is highly dependent on the process being run. If you are using a custom logging driver, it may bypass `docker logs` entirely and send its output to a different host, a volume, a database, or a log aggregation server.

Some images use tricks to manipulate the output of `docker logs`. Have a look at [the official `nginx` image](https://github.com/nginxinc/docker-nginx/blob/8921999083def7ba43a06fabd5f80e4406651353/mainline/jessie/Dockerfile#L21-L23). It uses symbolic links to be sure that the web server logs are shown as the output of `docker logs`.

The [official Apache web server image](https://github.com/docker-library/httpd/blob/b13054c7de5c74bbaa6d595dbe38969e6d4f860c/2.2/Dockerfile#L72-L75) does a similar thing, but instead of symbolic linking, it writes directly to the file descriptors for STDOUT and STDERR.

I hope this answers your question. I'll try to distill this into the documentation, though it does not belong in the command-line reference. that you linked to. That's just for the command flags, options, and syntax. In the future, if you have questions about the command-line reference or API reference, please log them in `docker/docker`, where those files are maintained.

Stay tuned for a PR where I capture some of the above information.

**Comment by drduke1** [comment]
That answers my question very well.
