### ISSUE TITLE
503 at /swarm/discovery/https://docs.docker.com/swarm/discovery/

### ISSUE THREAD

**Issue by chandruk1991** [docker/docker.github.io#2984]
URL: https://discovery.hub.docker.com/

**Comment by joaofnfernandes** [comment]
It seems that the old Swarm service discovery functionality has been having problems. I've reported this internally, and maybe @vieux can provide an update on this.

@chandruk1991 in the meantime you can deploy a key-value store, or use a file for service discovery, as mentioned [in the docs](https://docs.docker.com/swarm/discovery/).
Since there's nothing to be fixed in the docs, I'm closing this issue.
