### ISSUE TITLE
Documentation of repository "Full Description" editor.

### ISSUE THREAD

**Issue by Grimeton** [docker/docker.github.io#3085]
Hello,

I was going over the docs back and forth and I can't seem to find a link to the docs regarding the text editor that is used to add the "Full Description" of a repository.

I'm talking about tab, code references, links, bold and so on. 

Maybe you could add a link there somewhere?

Thanks!

KR,

G.

File: [docker-hub/index.md](https://docs.docker.com/docker-hub/), CC @johndmulhausen

**Comment by joaofnfernandes** [comment]
I'm not sure I understand your question, so sorry if I missed the point.
If you want to add some formatting to the description field of your Docker hub repositories, you don't really need a text editor. You just need to use the Markdown syntax. Here's a [cheat sheet you can use that explains Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

I'm closing this issue since there's nothing to do in the docs. But feel free to comment if you think there's something we can improve.

**Comment by Grimeton** [comment]
Hi,

yeah the thing is you don't see anywhere that it uses markdown. Here on github you have the small button on the lower left of the editor. That's not visible on hub.docker.com. So it would be nice to have it mentioned somewhere. 

cu
