### ISSUE TITLE
Should explain why host='redis' in docker-compose getting started

### ISSUE THREAD

**Issue by robertf224** [docker/docker.github.io#3128]
File: [compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/), CC @londoncalling

**Comment by londoncalling** [comment]
@shin- @nathanleclaire @dnephin Can you help with this question in reference to the `app.py` file in [Step 1: Setup](https://docs.docker.com/compose/gettingstarted/#step-1-setup) , why is `host` set to `redis` instead of, e.g., `localhost`? 

I started trying to sort it out, e.g.,  I would assume we want to reference `redis` in a container? But need help with a better explanation.

```
from flask import Flask
from redis import Redis

app = Flask(__name__)
redis = Redis(host='redis', port=6379)

@app.route('/')
def hello():
    count = redis.incr('hits')
    return 'Hello World! I have been seen {} times.\n'.format(count)

if __name__ == "__main__":
    app.run(host="0.0.0.0", debug=True)
```

**Comment by shin-** [comment]
`redis` is the hostname of the redis container on the application's network.

**Comment by londoncalling** [comment]
Thanks Joffrey!!
