### ISSUE TITLE
Don't understand what happend 

### ISSUE THREAD

**Issue by Zirconiumirish** [docker/docker.github.io#3176]
I try to install 5 times mastodon with docker and nothing is working always the same problems.

This appear what I m supposed to do with that ???

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

Thanks for your help

**Comment by joaofnfernandes** [comment]
I don't what how you're deploying Mastodon, but it seems you're using an invalid `docker-compose.yml` file. Maybe try using the one that's on the [official project repo](https://github.com/tootsuite/mastodon/blob/master/docker-compose.yml).

I'm closing this issue, since this isn't docs related. @Zirconiumirish if you have questions like this, try posting on [forums.docker.com](https://forums.docker.com/). There's a lot of people there eager to help you out!
