### ISSUE TITLE
Last bullet in filtering list isn't displaying correctly

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#3219]
File: [engine/reference/commandline/ps.md](https://docs.docker.com/engine/reference/commandline/ps/), CC @mstanleyjones 

<img width="906" alt="screenshot 2017-05-10 at 7 31 46 am" src="https://cloud.githubusercontent.com/assets/414445/25896585/c8fcb334-3552-11e7-930d-d8b02484e60b.png">

**Comment by mbentley** [comment]
Looks like this is still a problem today:

![screenshot 2017-07-12 at 2 15 04 pm](https://user-images.githubusercontent.com/414445/28133005-89e38f10-670c-11e7-99ac-4799aa689bf0.png)

**Comment by mstanleyjones** [comment]
This needs to be fixed in the `docker/cli` repository and cherry-picked to the currently-published branch there. The problem is that the pipes in the line are making Jekyll try to display it as a table. Can you please file it there? Maybe @johndmulhausen will look into it. I'm on vacation right now.
