### ISSUE TITLE
More obvious Edge integration

### ISSUE THREAD

**Issue by dsheets** [docker/docker.github.io#3324]
### Problem description

When I go to https://docs.docker.com/engine/reference/run/ to look up information about `--mount` in 17.05 (CE Edge), I see 17.03 is the latest version (in upper right), and it's not obvious how to get to 17.05 documentation (or if any exists). The left sidebar is different from <https://docs.docker.com/edge/>. If I search in the page for 'edge', I find a link in the left sidebar but it is 404 (#3323).

### Suggestions for a fix

My immediate reaction was to interact with the version selector in the upper right to get to an edge version of the reference page. I don't expect a full set of docs for each edge release but it would be fantastic if there was a link in the version selector that went to the general edge docs intro page or something. @mstanleyjones suggested that putting all edge releases in the upper right would not work as it would confuse stable/enterprise users and would be a lot of versions in the drop-down. Some kind of hint in the drop-down would be very helpful, though.

**Comment by johndmulhausen** [comment]
After some experimentation and discussion, we decided that what we want to do with regards to Edge is basically link to the PR/changelog activity so that people know what is in the release. This is what you'll find in https://docs.docker.com/edge/

I'm guessing this issue was filed during the brief period where we had an entirely different build with a full "Edge" docset.

**Comment by dsheets** [comment]
The original issue as reported still exists. The version drop-down mentions nothing of edge which is confusing. In this particular case, I am viewing https://docs.docker.com/engine/reference/run/ but my intent is to view https://docs.docker.com/edge/engine/reference/commandline/run/ (without knowing that URL which also contains `commandline`) and there is no obvious path from the stable doc page to the edge doc page. An in-page search does yield a working sidebar link but this is not an obvious action. As a user, I already know that I can use the version drop-down in the upper right to navigate between doc versions but it does not mention 'edge'.

**Comment by johndmulhausen** [comment]
They will continue not to mention anything of Edge; this is intentional. The Edge docs provided are a small subset of docs, not an entire docset that you can "switch into."

**Comment by dsheets** [comment]
Right, as a user that is confusing. It seems to be intentional, though, so I'll let it alone. Thanks for considering a change.

**Comment by mstanleyjones** [comment]
@dsheets we do have admontions on every CLI reference page when you're in the Edge version, to let you know about the Stable version of the same reference. We don't do it the other way because that seems to be pushing Edge a little too aggressively. Remember that Edge is only for CE, and we have to make sure our EE customers are never confused about which features, options, and flags are available to them.
