### ISSUE TITLE
Hedvig Docker Volume plugin

### ISSUE THREAD

**Issue by ercarter** [docker/docker.github.io#3407]
File: [engine/extend/legacy_plugins.md](https://docs.docker.com/engine/extend/legacy_plugins/), CC @mstanleyjones 

Hi! I'd like to request that the Hedvig Docker Volume plugin be added to this page as it is now complete, a part of the Docker Store and the GitHub posting is complete. The post is here:
https://github.com/hedvig/docker-volume-hedvig

Here are some words to fill out the table if you approve:

Hedvig plugin

A volume plugin that integrates the Hedvig Distributed Storage Platform with Docker for persistent, portable storage volumes with stateful containers.

Thanks!
Eric (eric@hedviginc.com)

**Comment by thaJeztah** [comment]
That page in the documentation is for legacy (V1) plugins. For V2 (managed) plugins, the recommended installation method should be to distribute the plugins through Docker Store, and use `docker plugin install`, instead of requiring the user to manually build the plugin.

The listing of legacy plugins will probably be phased out in future, after plugin authors have migrated their plugins to V2 plugins

**Comment by mstanleyjones** [comment]
Also this should be raised in `moby/moby` as that is where the page you want to edit actually lives. https://github.com/moby/moby/tree/master/docs/extend

**Comment by ercarter** [comment]
Got it - thank you. I'll check that out. I get now that this is legacy. What we're doing is thru the Docker store now so I'll be sure the details and links are all there.

**Comment by mstanleyjones** [comment]
Sounds great!

**Comment by thaJeztah** [comment]
@ercarter correct; the listing in the documentation pre-dates managed plugins, and was added as a stop-gap solution to give plugins some exposure. Now that Docker Store features plugins, we'll move away from this listing.

@mstanleyjones possibly we should add some more docs around plugins, and have a link to docker store, with the "plugins" filters set?
