### ISSUE TITLE
dockerd: typo with 'specify'

### ISSUE THREAD

**Issue by neomantra** [docker/docker.github.io#3423]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/), CC @mstanleyjones 

Note the redundant `specify` in this line in the "Options for the runtime" section:
```
You can specify only specify cgroupfs or systemd
```

**Comment by Ruwbin** [comment]
Hi, I am new to open sources. May I take this one?

**Comment by mstanleyjones** [comment]
@Ruwbin you absolutely can! The one caveat is that the problem really isn't in the docs repo, but the upstream `moby/moby` repo. https://github.com/moby/moby/blob/master/docs/reference/commandline/dockerd.md

See the contribution guidelines for that repo at https://github.com/moby/moby/blob/master/CONTRIBUTING.md.

I marked this one `newbie` without realizing that it had the wrinkle of the source of the problem being in a different repo.

**Comment by neomantra** [comment]
@mstanleyjones Ah, it looks like this was fixed in [this `moby/moby` changeset](https://github.com/moby/moby/commit/62cc802f6160b7fbb506f5307d96a564cbfb5f1f) from December.

I created this issue via the Docker Documentation website link in the upper right corner ("Edit This Page").  So are those docs just out-of-date?

**Comment by mstanleyjones** [comment]
No, the way we generate that content is a little tricky! We actually generate those pages from YAML files which get generated straight from the code in `moby/moby`. It's a little complicated, but we want to get the options and flags and sub-commands straight from the code so that they don't go out of sync. It creates a situation where there are a few parts of the docset where the source doesn't actually live in our repo.
