### ISSUE TITLE
Can docker build with gpu device enabled in temp containers while building docker images 

### ISSUE THREAD

**Issue by backyes** [docker/docker.github.io#3425]
If the processes running in tmp containers need to access gpu device while using 'docker build'  to create new docker images, it will fail because 'docker build ' does not set GPU devices visible for tmp containers. 

try 'nvidia-docker build ' also failed to do it. 

'docker build --help ' show no property setting to set GPU device visible for the container.  

From compiling/building docker images aspect, the REAL GPU devices should not be visible in container, but some projects will try to access REAL GPU device while using 'docker build'...  

Can 'docker build ' create tmp container for building images with GPU device visible?

**Comment by joaofnfernandes** [comment]
Maybe @thaJeztah can help here?

**Comment by mstanleyjones** [comment]
@cpuguy83 PTAL

**Comment by cpuguy83** [comment]
Why does the build require access to the GPU?

**Comment by mpekalski** [comment]
@cpuguy83 I think it can be as simple as compiling Tensorflow with CUDA support.

**Comment by ahh-docker** [comment]
Hello! Thanks for filing an issue with the Docker documentation team. Unfortunately, it looks like your issue is more of a support issue than a documentation issue.

For the Docker Community Edition (CE), please visit https://forums.docker.com/, and post your issue there.

For Docker Enterprise Edition (EE) subscribers, please visit https://success.docker.com/support, and contact Docker Support directly.

If this is a documentation issue, please reopen the issue, along with more detailed comments on what needs a review and possible edit. Thanks!
