### ISSUE TITLE
Release note strategy for Docker CE and EE

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker.github.io#3434]
### Problem description

We need to decide where release notes live now, who writes them, who hosts them, etc. We need to try to keep this as low maintenance as possible. A possible approach is a "highlights reel" curated by product management, coupled with a Github query showing the full list of PRs that went into a release, per affected repo.

Writing full, proper release notes is very time-consuming, and if the Docs team is going to take this on, we need more resources. This is not my first release notes rodeo.

cc/ @thaJeztah @friism @dmp42 @johndmulhausen

**Comment by thaJeztah** [comment]
> coupled with a Github query showing the full list of PRs that went into a release, per affected repo.

This is gonna be more tricky with the new release procedure, because pull requests will no longer be tied to a milestone, so even if we set `impact/changelog` on pull requests, there's no easy way to get a lost  of all of those that went into the release.

Possibly with some git magic; finding the commits, and relating that to pull requests

**Comment by mstanleyjones** [comment]
This was already fixed. :) 🎉 🌮
