### ISSUE TITLE
Improve/expand info on volumes, `docker volume` and related concepts

### ISSUE THREAD

**Issue by chamunks** [docker/docker.github.io#344]
URL: [https://docs.docker.com/engine/tutorials/dockervolumes.md](https://docs.docker.com/engine/tutorials/dockervolumes/)

Can someone expand on `docker volume` and write a separate section on how to manage those since that's the new preferred method of volume management?  I would contribute some edits myself but I'm only getting to know it now.  

Specifically information regarding **backup/restore** and **backups/restores** with **labels** and things like that.

I've managed to sort out this information on my own but someone coming to this guide for the first time might get confused with the focus mainly being on the `docker create -v` and `docker create --name data busybox` and `docker volume create` all of these methods are great and important to keep documented but ideally we should have something set to be the primary / recommended vs deprecated methods.

**Comment by mstanleyjones** [comment]
This was already on my radar, but thanks for the request. Keep watching this issue for the related PR on this one, in the next few weeks. I'd love to have your review and collaboration as I develop the sections you're requesting.

**Comment by surajnarwade** [comment]
I will pick this up

**Comment by surajnarwade** [comment]
@londoncalling suggestions

**Comment by mstanleyjones** [comment]
So, while PR #2961 does expand on the info about volumes, this issue had a very high points value because there was a lot of potential information that could have been added. We really need to modernize and rewrite the whole storage area of the docs, and that's what this issue was supposed to be tackling. For that reason, I am bumping the potential points down to 250. Thanks @surajnarwade for your contribution!
