### ISSUE TITLE
--details no more available as an option

### ISSUE THREAD

**Issue by mims92** [docker/docker.github.io#3471]
File: [engine/reference/commandline/service_logs.md](https://docs.docker.com/engine/reference/commandline/service_logs/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
Hi, the option is actually listed in the URL that you posted, which is the correct URL for the Docker 17.03 Stable release. The URL for the 17.05 Edge release CLI reference is missing the option, but that is due to a bug in the CLI reference generator, and the option actually still exists in Docker. Please try `docker service logs --help` to verify that you see the option listed. If you do NOT see it listed, please run `docker version` and share the output.

cc/ @tiborvass

**Comment by mstanleyjones** [comment]
With more digging, the option should not be listed in the stable or edge version right now as it is coming for 17.06. :angel: We will get it fixed by regenerating the CLI reference files. Thanks for the report!
