### ISSUE TITLE
Add information about how to mitigate OOME

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker.github.io#3535]
### Problem description

Memory exhaustion on a host can lead to OOME and killing of important system processes, containers, or the Docker daemon. Document some mitigation and troubleshooting info.

**Comment by joaofnfernandes** [comment]
We already have this https://docs.docker.com/engine/admin/resource_constraints/
but I'm not sure it's representative of a real workflow since few people will be running a single container and enforcing resource constraints on them.

I think the real workflow is something like a developer writes a compose file and hands it over to IT Ops for deployment. IT Ops will understand the requirements of the application and customize the compute resources that are allocated the the app. This includes defining networks, volumes, but also constraints.

If that's the case, the article should teach me how to do these configs on the compose file. Of course we can still mention the CLI flags, but that can be given less emphasis.
