### ISSUE TITLE
Self-signed certificates setup on Windows

### ISSUE THREAD

**Issue by TomHart** [docker/docker.github.io#357]
URL: [https://docs.docker.com/registry/insecure.md](https://docs.docker.com/registry/insecure/)

I've follow the "Using self-signed certificates" on a remote Ubuntu server, which works great, however, of course on Windows I don't have a "/etc/docker/certs.d/myregistrydomain.com:5000/ca.crt." folder.

Where about do I need to place the certificate to pacify the error message "Get https://my.registry.com:5000/v1/_ping: x509: certificate signed by unknown authority"?

**Comment by joaofnfernandes** [comment]
From my initial research it seems that you need to add the certs to `%programdata%\docker\certs.d`.
Probably configuring Windows to trust those certificates ([as described here](https://technet.microsoft.com/en-us/library/cc754841(v=ws.11).aspx)) will also work.

But I need to research this a bit more. Please update this issue if you find more info in the meantime.

**Comment by TomHart** [comment]
I've had to drop the project where this was an issue temporarily, but I did get around it, however, I'm not sure which one was the actual fix, or if I needed both, but I added the cert nativley to Windows so it trusted it, and I also installed it in my Docker VM.

**Comment by mstanleyjones** [comment]
@joaofnfernandes I think this was addressed as part of the new content trust docs.

**Comment by joaofnfernandes** [comment]
Yup. Instead of configuring docker, you should configure Windows to trust that CA. That way, other client tools will also trust it.

[Check here how to do that](https://docs.docker.com/datacenter/dtr/2.2/guides/user/access-dtr/#windows)

I'm leaving this issue open since the registry docs need a review to have a page that's essentially a copy of that one.

**Comment by londoncalling** [comment]
Assigning `hackathon` label. 

The goal for the Hackathon is to figure out if there is useful information we can add to the first pages the user mentions ([Test an insecure registry](https://docs.docker.com/registry/insecure/)) to make it more intuitive so that he could have gotten to the right place on his own.

**Comment by tippexs** [comment]
claimed

**Comment by joaofnfernandes** [comment]
#2909 is related to this

**Comment by joaofnfernandes** [comment]
Fixed by #2909 and #2911
