### ISSUE TITLE
compose file version 3.2 is only supported by docker 17.04 and later

### ISSUE THREAD

**Issue by linusguan** [docker/docker.github.io#3714]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @londoncalling 

The doc indicates that v3.2 is supported by 1.13.0+

**Comment by londoncalling** [comment]
@linusguan I might be missing something, but looking at the table on https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix, I see that it indicates only that Compose file version 3.2 is supported by `17.04` and above.

This matrix, though, on the Compose releases page, does indicate that v3.0-3.2 are supported by 1.13.0+: https://github.com/docker/compose/releases/

@shin- which is right?

**Comment by shin-** [comment]
Oddly enough, they both are.

Since nothing in v3.0 - 3.2 depends on any **engine** feature introduced after 1.13.0, *`docker-compose`* is able to use all three formats with Engine 1.13.0 or newer. 
On the other hand, the *Docker CLI* introduced those formats progressively in 1.13.0, 1.13.1, and 17.04.0, and as such, you will need to use the corresponding version with `docker stack deploy` for the format to be recognized as valid.

**Comment by linusguan** [comment]
The table has been updated recently so I am closing the issue.
@shin- thanks, the Docker CLI is the use case of mine.
