### ISSUE TITLE
Error Step 4/7  returned a non-zero code

### ISSUE THREAD

**Issue by bkarpe** [docker/docker.github.io#3784]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/), CC @johndmulhausen

I got the following error:
Step 4/7 : RUN pip install -r requirements.txt
 ---> Running in 310b4d86b169
standard_init_linux.go:187: exec user process caused "exec format error"
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1

I am running this on Raspbian Jesse (Raspberry Pi 3). I will check for a possible conflict here.

**Comment by joaofnfernandes** [comment]
I can't reproduce this since I don't have a Raspberry Pi. @bkarpe Basically Docker failed when trying to process the Docker file. More specifically it failed on the instruction `RUN pip install -r requirements.txt`, which fetches and installs python packages.

One possible scenario for this error to happen is that your Raspberry is not connected to the internet. But if that were the case you would get something like

```
Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff005774850>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/flask/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff005774f10>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/flask/
```
not an `exec format error`. So I'm clueless here.

**Comment by kgrosvenor** [comment]
Are you running out of memory on the docker whilst they are installing?
