### ISSUE TITLE
Please, document when the volume is available for the container

### ISSUE THREAD

**Issue by imaia** [docker/docker.github.io#3841]
### Problem description

I cannot find when a volume becames available for writing to a container. Is it only after the build? Does anon containers and named containers behave differently? How/When to handle permissions?

**Comment by mstanleyjones** [comment]
Fixed in #4018 
Volumes are orthogonal to containers. You can run a container with or without a volume mounted into it. If there is no volume, the container just writes to its writable layer. You can create a volume ahead of time, or a volume will be created the first time a container tries to mount it.
