### ISSUE TITLE
What properties can appear more than once?

### ISSUE THREAD

**Issue by MihaMarkic** [docker/docker.github.io#3886]
File: [engine/reference/commandline/build.md](https://docs.docker.com/engine/reference/commandline/build/), CC @mstanleyjones

The classic example is tag argument:

> docker build -t one -t two

The recent docs don't mention what properties can appear more than once.
Example: 
before: -t, --tag=**[]** 
now: --tag, -t

This is not good.

**Comment by RehanSaeed** [comment]
This is stopping code being generated to wrap execution of Docker commands.

**Comment by mstanleyjones** [comment]
@tiborvass @FrenchBen can we modify our YAML generator to somehow capture that a value can be listed more than once?

@RehanSaeed I don't understand your second comment.

**Comment by MihaMarkic** [comment]
@mstanleyjones If there was a column like int or int[], bool, bool[], string or string[] it'd be perfect.
Also, if you have the docs in another format (i.e. yaml) I'd be more than happy to use it (rather than generated human readable docs).
I'm using it for wrapping docker commands as a Cake plugin.

**Comment by mstanleyjones** [comment]
We generate it directly from Docker code itself and some docs in the `docker/cli` repository. What you see here should not be edited directly.

**Comment by MihaMarkic** [comment]
Guys, any news on this?

**Comment by mstanleyjones** [comment]
@tiborvass do you have any thoughts on this?

**Comment by gitfool** [comment]
👍

**Comment by MihaMarkic** [comment]
Guys!

**Comment by mstanleyjones** [comment]
I'm sorry, but this is not an issue that can be addressed in **this** repository.  Currently, I do not think there is a programmatic way to even figure out this info. If it does exist or needs to be created, that will be in some combination of `moby/moby` or `docker/cli`. We are still waiting on technical review to find out whether it's feasible and where the work should be done. @thaJeztah @tiborvass @FrenchBen if you would like to weigh in, that would be great.

**Comment by thaJeztah** [comment]
No, there's currently no easy way to add this information to the generated YAML, other than manually adding an annotation to each flag to indicate if the flag can be used multiple times.

The packages used to create the command-line (https://github.com/spf13/cobra, and the https://github.com/spf13/pflag) will always accept a flag to be specified multiple times, but if only a single value is expected, later flags override earlier flags (which complicates things a bit).

To automate docker, instead of scraping the docs, I would really recommend using the remote API instead, which is designed for this, and is documented here: https://docs.docker.com/engine/api/v1.30/

While looking at this, I noticed some information was not included in the YAML files used to generate the documentation, and opened a pull request https://github.com/docker/cli/pull/523. That pull request may be useful as well as it shows how the YAML is generated, and perhaps could be used as a starting point if you don't want to use the API and automate generating code to use the CLI.

**Comment by mstanleyjones** [comment]
Closing this for now, since we can't actually do what you asked for, and you can use the remote API directly instead. I'm looking forward to the improvements in https://github.com/docker/cli/pull/523!

**Comment by MihaMarkic** [comment]
But even as a CLI user, how can I know?

**Comment by MihaMarkic** [comment]
Never mind, I'll parse sources myself. After an effort of something like six hours, I'm able to produce more metadata than your tools.

**Comment by thaJeztah** [comment]
Contributions are welcome to that script :innocent:

**Comment by MihaMarkic** [comment]
@thaJeztah The thing is, that I hacked a C# console app that _parses_ go code. Do you think you could benefit from it? Besides, CLI is really not very friendly written when it comes to documentation. Perhaps a limit of Go, I don't know.
