### ISSUE TITLE
Installation of Docker-Machine on windows using chmod ?

### ISSUE THREAD

**Issue by AesonDev** [docker/docker.github.io#3898]
File: [machine/install-machine.md](https://docs.docker.com/machine/install-machine/), CC @londoncalling

**Comment by joaofnfernandes** [comment]
@AesonDev I can't seem to tell what is the problem, or if you find something confusing.
As far as I can tell that article tells you how to download the `docker-machine` binary, and if you're on a Linux system, you first need to make the file executable by using the `chmod` command, otherwise you won't be able to run it.

**Comment by AesonDev** [comment]
chmod does no exist on windows. But the documentation said to run chmod and a linux command on windows.

Adapting the doc could maybe making it less confusing 😊

**Comment by joaofnfernandes** [comment]
Now I get it... Duhhhhh 🙈

**Comment by londoncalling** [comment]
@AesonDev , sorry for the confusion .. the Docker Machine install will work as documented (with the Linux `chmod` commands) if you use [Git Bash](https://git-for-windows.github.io/), as mentioned in the instructions. I just installed Git Bash on my Windows laptop and the Machine install worked as described (see below). I'll update those docs to make this caveat clearer, and link the pull request to this issue.

![machine-install-on-git-bash](https://user-images.githubusercontent.com/11660803/29588702-5f38fa06-8747-11e7-8082-b7d9da8cf51e.PNG)

**Comment by AesonDev** [comment]
I love you
