### ISSUE TITLE
Some links do not work at the bottom of https://github.com/docker/docker.github.io/blob/master/registry/deploying.md

### ISSUE THREAD

**Issue by 030** [docker/docker.github.io#3901]
https://github.com/docker/docker.github.io/blob/master/registry/deploying.md

**Comment by joaofnfernandes** [comment]
Some of these articles are not tracked in this repository and live with to the [source code](https://github.com/docker/distribution). When we build the docs, we fetch these articles and put them in the right directories, so that the links work.

If you read the page in the docs site, you'll notice that the links are OK.
https://docs.docker.com/registry/deploying/

I'm going to close this issue, since we want to continue tracking these articles on their upstream repository, but feel free to comment.
