### ISSUE TITLE
Docker Restart Options

### ISSUE THREAD

**Issue by MarkDucommun** [docker/docker.github.io#3903]
File: [compose/reference/restart.md](https://docs.docker.com/compose/reference/restart/), CC @londoncalling 

What are the options?  It feels like this is the place where they would be enumerated.

**Comment by londoncalling** [comment]
Hi @MarkDucommun , There is only one flag with a short and a long form (`-t` or `--timeout`), as documented in [compose/reference/restart.md](https://docs.docker.com/compose/reference/restart/)

However, in looking at the current Help on the command, I'm wondering whether `--timeout` has changed to `--time`? 

```
victoriabialas at snapair in ~/repos/docker.github.io on master
$ docker restart --help

Usage:	docker restart [OPTIONS] CONTAINER [CONTAINER...]

Restart one or more containers

Options:
      --help       Print usage
  -t, --time int   Seconds to wait for stop before killing the container (default 10)
```

Can you verify, @shin- and/or @dnephin ? The `--help` on the command ^^ doesn't quite seem to match the docs. (I'm running `17.06.0-ce` and `docker-compose version 1.14.0, build c7bdf9e`.)

cc: @mstanleyjones

**Comment by dnephin** [comment]
@londoncalling you ran `docker restart` not `docker-compose restart`. The docs are correct.

**Comment by londoncalling** [comment]
@dnephin , right you are!

```
$ docker-compose restart --help
Restart running containers.

Usage: restart [options] [SERVICE...]

Options:
  -t, --timeout TIMEOUT      Specify a shutdown timeout in seconds.
                             (default: 10)
```
@MarkDucommun  closing this issue, as the docs already include the options you were looking for.

**Comment by amelvill** [comment]
Just wanted to throw this out there,

I notice that the [docker-compose restart](https://docs.docker.com/compose/reference/restart/) command docs page has a rather low score at the time I'm writing this, (+36/-207) and I can't leave comments on the page directly, so I figured I'd just leave an idea here,

It's not really Docker's fault on this, but when you google something like "docker-compose restart", the first page that comes up is this: [docker-compose restart](https://docs.docker.com/compose/reference/restart/), when I searched for that I was looking for the version 2 docker-compose.yml config file field [restart](https://docs.docker.com/compose/compose-file/compose-file-v2/#restart). If I would've searched for "docker-compose.yml restart" it would've came up with the right page, but I didn't know docker-compose (the CLI utility) had a restart command at the time.

Now I know that the docker-compose restart page is referring to the docker-compose utility, not a field within docker-compose.yml, but it wasn't super clear at first and I was tempted to hit that dislike button at first because the page didn't seem to make any sense as its relation to docker-compose.yml.

My suggestion is, maybe add some kind of docker-compose restart disambiguation page, or make some kind of way for the user to navigate between configuration files and cli commands, because there's some name collision issues between docker-compose commands and docker-compose.yml fields (fields/commands named the same but with different parameters).

(FWIW, note that the v3 docker-compose.yml file format improved upon this significantly by calling the field "restart_policy" instead of "restart")
