### ISSUE TITLE
Review readme.md to be able to test changes to docs site locally

### ISSUE THREAD

**Issue by InteXX** [docker/docker.github.io#4006]
### Problem description

The reference documentation for `Dockerfile` is omitted in an offline repository.

### Problem location

The local repository is made available for browsing via Jekyll, as described [here](https://github.com/docker/docker.github.io#staging-the-docs).

This link fails:
http://localhost:81/engine/reference/builder/

While this one works:
https://docs.docker.com/engine/reference/builder/

### Project version(s) affected

All versions are affected.

### Suggestions for a fix

The content could be made to be the same between the public repository and private repositories.

**Comment by joaofnfernandes** [comment]
I've updated the title of the issue to be a bit more descriptive of the real issue.

**Comment by InteXX** [comment]
@joaofnfernandes — Actually, for me at least this makes it more unclear. But I may not be understanding the architecture of the repo correctly. Could you help me by clarifying your reasoning?

**Comment by joaofnfernandes** [comment]
Sorry for not providing all the context. This repo tracks almost all the docs, but there are a few files that are tracked on upstream repositories, so that documentation lives closer to the code. You can [check here](https://github.com/docker/docker.github.io/blob/master/_data/not_edited_here.yaml) which files are tracked in other repos.

It happens that all the files under `/engine/reference` are tracked in the [docker/cli repository](https://github.com/docker/cli/tree/master/docs/reference/).

This means that if you follow what the readme file says and clone this repo and run `jekyll serve`, the source file doesn't exist, so Jekyll won't be able to serve it.

Given that we fetch some of these files at build time, if you want to use the docs site in its entirety, you need to do build an image from the `Dockerfile` that lives on this repo, and then run it:

```
docker build -t docs .
docker run  -p 4000:4000 docs
```
This is not documented in the readme. Also, the readme also says that you can use a `docker-compose.yml` file that's on this repo. But this option also won't give you the full docs site.

**Comment by johndmulhausen** [comment]
@InteXX What you get when you build the repo locally is everything we have in this repo. If you want the whole docs site, including everything from the upstream, the secret password is to run _scripts/fetch_upstream_resources.sh first. Don't send us any PRs that try to add these files to our repo, but do feel free to grab them if you want to see them.

Another option is just to run the built docs directly:

`docker run -ti -p 4000:4000 docs/docker.github.io`

**Comment by InteXX** [comment]
@johndmulhausen — Got it, thanks. Was meaning to get to this by now, but time goes by very quickly around here.
