### ISSUE TITLE
Links to markdown files not working

### ISSUE THREAD

**Issue by pierlon** [docker/docker.github.io#4165]
Links referring markdown files don't seem to work; removing the '.md' from the link works however.

**Comment by londoncalling** [comment]
@pierlon we purposely include `.md` so that the links will work both on GitHub and after Jekyll processing on GitHub pages on the site (when they are converted to HTML files). 

For example, if you [go here](https://docs.docker.com/docker-cloud/cloud-swarm/) and take any of the links in the list (e.g., Using Swarm Mode with Docker Cloud, Swarm Mode and organizations, and so on), they will work on the docs website.

Then go here on GitHub: https://github.com/docker/docker.github.io/blob/master/docker-cloud/cloud-swarm/index.md, and notice the same links work within GitHub to the pre-processed `.md` files.

Can you point me to the links you are having trouble with?

**Comment by pierlon** [comment]
@londoncalling thanks for the clarification. It appears the issue may have been only been affecting me. 

The links on the doc site were in this format, for example:

https://docs.docker.com/docker-cloud/cloud-swarm.md instead of https://docs.docker.com/docker-cloud/cloud-swarm/

No longer seeing that issue anymore however.

**Comment by londoncalling** [comment]
@pierlon great, thanks. We have had some issues on certain platforms. Let me know if you have any other problems. 

Also, your issue helped me notice one place where we did not have the `.md` and the GitHub link was breaking so I fixed it and linked that PR to this issue. Thanks!

**Comment by pierlon** [comment]
Glad to help :smile:
