### ISSUE TITLE
Duplicate titles

### ISSUE THREAD

**Issue by scjane** [docker/docker.github.io#4190]
File: [engine/deprecated.md](https://docs.docker.com/engine/deprecated/), CC @mstanleyjones 
There are two duplicate titles on this page.

![titles](https://user-images.githubusercontent.com/25146885/29255677-1ff55726-80d6-11e7-8d1c-2907eabad223.jpg)

**Comment by cameronthomas** [comment]
@scjane were you planning on creating a PR for this? If not, I can do it.

**Comment by scjane** [comment]
@cameronthomas I cannot find this page. Please do it. Thanks.

**Comment by mstanleyjones** [comment]
Y'all, the change for this is upstream, not in our repo. https://github.com/docker/cli/blob/master/docs/deprecated.md I believe you just need to remove the explicit H1 on that page. While you're there, you can restructure the page to have H2 headings per Docker version, rather than the bold paragraphs it has now, and to make sure that no heading levels are skipped.

cc/ @thaJeztah for heads up.

**Comment by cameronthomas** [comment]
Ok, sounds good.
