### ISSUE TITLE
more information on less space

### ISSUE THREAD

**Issue by harridu** [docker/docker.github.io#4192]
File: [index.md](https://docs.docker.com/), CC @johndmulhausen 
Hi folks,

I highly appreciate your work on docker, but I would like to suggest some improvements for the documentation (web and man pages):
- please increase contrast. white chars on a black background are *way* more easy to read than light blue chars on a white background.
- please reduce line gap. The documentation on the web wastes a *lot* of screen space. You always have to scroll, which makes it very hard to get a full picture.
- please provide *full man pages* with the docker installation. On Unix the man pages are the reference (traditionally), but the docker man pages don't tell the whole story. This is a big disadvantage. The web documentation is nice to have, but IMHO this GUI stuff is distracting when you are in the zone.

Thanx very much
Harri

**Comment by johndmulhausen** [comment]
We don't have any light blue characters on a white background nor are we likely to switch to white characters on a black background.

We are also considering what to do about manpages in separate internal discussions but that work won't be tracked here. 

The line height is also not likely to be reduced, especially for the reason stated. The scroll length would not be impacted strongly by line height reduction. We provide the right-navigation in order to orient you on the full picture, and it even automatically highlights the sub section that you are currently viewing. 

If you'd like to customize the appearance of the docs to be white characters on a black background or scrunch the text, I would recommend a browser extension such as Stylish. You can permanently override styles with it to your liking. Additionally you can also feel free to fork our docs, which are open source, and run them locally using the instructions in readme.md. You can make whatever changes you like in the _scss folder. 

cc @jsouth (the design lead) so he's aware of this feedback and can comment if he sees fit. Closing bug.
