### ISSUE TITLE
Problem with windows installation documentation

### ISSUE THREAD

**Issue by cowlinator** [docker/docker.github.io#4196]
File: [docker-for-windows/install.md](https://docs.docker.com/docker-for-windows/install/), CC @londoncalling 

In the documentation page "Install Docker for Windows", under "Install Docker for Windows", it depicts a toggle labeled "Launch Docker".  This does not exist in the latest stable release of the installer.

Under "Start Docker for Windows", it states that once the installer completes, docker starts automatically.  This does not appear to be true.

**Comment by londoncalling** [comment]
@friism @jeanlaurent @simon.ferquel @dsheets 

I’m seeing some problems with Windows installer per @cowlinator's issue , and not sure if these are already known issues:

1. Both the Stable or Edge installers that I get from here https://docs.docker.com/docker-for-windows/install/#download-docker-for-windows fail to start Docker automatically after install. Apparently we used to have a toggle on the setup wizard that gave you the option to launch Docker, but this is now gone. I thought that one time when I tried the install with the Edge installer, Docker started automatically but I can’t recreate that again with any of the 3 installers.

2. When I start Docker stable manually (with a search for Docker and clicking on it), it takes a long time to start. (Edge seems faster.)

3. When I originally opened up the Windows laptop and started Docker, the popup window that tells you a newer version is available was positioned with the bottom of the window off screen, so that I couldn’t click OK to confirm I wanted the new version. I had to figure out how to move the window up (which took me a while to figure out that I had to press and drag with two fingers on the correct area on the window to move it)
