### ISSUE TITLE
Env var issue on docker CE installation instructions

### ISSUE THREAD

**Issue by arthur-feral** [docker/docker.github.io#4239]
File: [engine/installation/linux/docker-ee/ubuntu.md](https://docs.docker.com/engine/installation/linux/docker-ee/ubuntu/), CC @mstanleyjones 

Hi,

There must be an issue with the documentation page on Docker CE ubuntu.
In the apt repository add section,  instead of seeing a proper URI we see a bad formated environment variable
`DOCKER-EE-URL` instead of `DOCKER_EE_URL` i guess. So urls for docker CE aren't formated properly.

**Comment by mstanleyjones** [comment]
A few things:

1.  If you are trying to install Docker CE, you need the CE URL, not the EE URL: https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/

2.  If you're installing Docker CE, the `DOCKER-EE-URL` placeholder text is not relevant to you and is not mentioned in the topic. This is for customers of Docker EE, which has special per-customer repository URLs rather than the generic repository URL for Docker CE. In the Docker EE installation instructions, you are told about this placeholder text and what it means in the [prerequisites](https://docs.docker.com/engine/installation/linux/docker-ee/ubuntu/#prerequisites).

Thanks!
