### ISSUE TITLE
docker-compose ps with custom project name

### ISSUE THREAD

**Issue by zainengineer** [docker/docker.github.io#4320]
File: [compose/reference/ps.md](https://docs.docker.com/compose/reference/ps/), CC @londoncalling 

docker-compose ps does not work with custom project name.
Any documentation on how to work around that ?
is there a work around which is not documented?

**Comment by joaofnfernandes** [comment]
Can you provide an example of the `docker-compose` command you're trying to run?

**Comment by zainengineer** [comment]
```docker-compose -f /var/www/vhosts/bbq/bbq-docker/LAMP-docker/docker-compose.yml -f /var/www/vhosts/bbq/bbq-docker/docker-compose.override.yml --project-directory /var/www/vhosts/bbq/bbq-docker --project-name bbq up
p```
this is the docker-compose command LAMP-docker is a generic LAMP docker, where as overrides are in a separate folder.

**Comment by joaofnfernandes** [comment]
I think there are 2 things at play here:
1. It seems that docker-compose only take a single `-f` flag. You give it two files, but only the last is used
2. When you deploy your file with `docker-compose -f <file> up`, to check the containers you need to also do `docker-compose -f <f> ps`

This was also confusing for me, since I expected to be able to refer to the project by it's name, not it's compose file. So I expected `docker-compose --project-name <name> ps` to work, but it doesn't.
The reason why it doesn't work, is that `docker-compose` is basically a client that makes requests to the Docker daemon, and doesn't have a lot of internal state. So it always needs access to the compose-file to be able to understand the details of your stack. The project name alone is not enough.

@zainengineer Given that this repo only tracks the documentation I'm going to close this issue. Feel free to comment if this is still not clear.
Also, feel free to open an issue at [docker/compose](https://github.com/docker/compose) if you think the product could be improved.

**Comment by zainengineer** [comment]
@joaofnfernandes docker-compose accepts multiple -f (I use it all the time)
`docker-compose ps` does not accept `-f` argument. 
if it can, should it be part of documentation?

**Comment by joaofnfernandes** [comment]
I took the time to test this more thoroughly, and it seems that I was wrong about `-f`. Here's my setup: 

(docker-compose-original.yml)
```
version: "3"
services:
  sleep:
    image: alpine
    command: sleep 500000
    environment:
      COMPOSE_FILE: "original"
```

(docker-compose-override.yml)
```
version: "3"
services:
  sleep:
    image: ubuntu
    command: sleep 500000
```

If you do
```
docker-compose -f docker-compose-original.yml -f docker-compose-override.yml --project-name bbq up
```
This deploy the service using the `ubuntu` image, but the `COMPOSE_FILE` environment variable is set. So you clearly can use multiple `-f`.

But since you are using a custom file name and custom project name, to use `docker-compose ps`, you need to do it like this

```
docker-compose -f docker-compose-original.yml -f docker-compose-override.yml --project-name bbq ps

    Name         Command      State   Ports
-------------------------------------------
bbq_alpine_1   sleep 500000   Up
```

Does this answer your question?

**Comment by zainengineer** [comment]
thanks that answers my question. I am on vacations will try it soon.
