### ISSUE TITLE
Feedback for: engine/reference/commandline/ps.md

### ISSUE THREAD

**Issue by sixcorners** [docker/docker.github.io#44]
URL: engine/reference/commandline/ps.md

Actions are missing from the format parameters of examples on docs.docker.com.
I see `$ docker ps --format "table \t"` on the website and `$ docker ps --format "table {{.ID}}\t{{.Labels}}"` when looking the file being rendered by github. inspect.md has the same problem.

**Comment by iBobik** [comment]
It is probably because `{{ }}` is also syntax for Liquid, what is run by Jekyll, base of Github Pages.

Workaround:
```
{% raw %}
$ docker ps --format "table {{.ID}}\t{{.Labels}}"
{% endraw %}
```

**Comment by iBobik** [comment]
I asked in Jekyll forum for a better solution: https://talk.jekyllrb.com/t/how-to-turn-off-liquid-in-md/3078

**Comment by johndmulhausen** [comment]
Thanks for asking them for their thoughts, @iBobik . Looks like the only other option is crazy syntax such as {{ "string" }}}} which works in spite of intent/implementation rather than because of it. I tried {{ content | markdownify }} and it not only didn't solve the issue, it increased the build time by over 300%.

I think we're stuck using {% raw %}, which #48 applied. While that PR did have too wide of a scope on the pages, that's always something we can adjust if Liquid ever needs to be added to those 35 files. 

If you ever dig up a novel solution, let us know!
