### ISSUE TITLE
Cannot Understand Resource Limits

### ISSUE THREAD

**Issue by kolotyluk** [docker/docker.github.io#4451]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @londoncalling 

From the documentation I cannot understand how to set resource limits.

For example 

    $ vi kafka-stack.yml 
    ~ $ docker stack deploy --with-registry-auth -c kafka-stack.yml kafka
    memory-swap Additional property memory-swap is not allowed
    ~ $ vi kafka-stack.yml 
    ~ $ docker stack deploy --with-registry-auth -c kafka-stack.yml kafka
    memory_swap Additional property memory_swap is not allowed
    ~ $ vi kafka-stack.yml 
    ~ $ docker stack deploy --with-registry-auth -c kafka-stack.yml kafka
    memory_swappiness Additional property memory_swappiness is not allowed
    ~ $ vi kafka-stack.yml 
    ~ $ docker stack deploy --with-registry-auth -c kafka-stack.yml kafka
    memory_swappiness Additional property memory_swappiness is not allowed
    ~ $ vi kafka-stack.yml 
    ~ $ docker stack deploy --with-registry-auth -c kafka-stack.yml kafka
    mem_swappiness Additional property mem_swappiness is not allowed

> Each of these is a single value, analogous to its docker service create counterpart.

I cannot tell from this documentation the valid list of memory settings for deploy.resources.limits

**Comment by londoncalling** [comment]
Yes, [this section on resources needs work](https://docs.docker.com/compose/compose-file/#resources). I'll ping you when we've got a better draft.

**Comment by londoncalling** [comment]
@kolotyluk I've updated the Compose docs per the referenced PR with a little more information, including a note to clarify the differences between setting resource constraints in Compose file format v3 vs. v2. (Please see the PR.)

But beyond this, in answer to your questions, if you are setting resources on swarm mode services and containers, each of the available options is described in the subtopics to [Deploy Key "resources"](https://docs.docker.com/compose/compose-file/#resources), with links off of those topics to specifics for each setting. 

One example given is that setting `memory: 50M`under the `deploy` key resources limits for a service will limit the memory that service can use to no more than `50M`.

I'm not sure what other specifics you need, beyond what's already in those topics, or where you are having problems?

cc: @shin- @gbarr01

**Comment by kolotyluk** [comment]
I guess my previous frustration was with the error messages I was receiving with the settings (memory-swap, memory_swap, memory_swappiness, mem_swappiness, etc.) These were mentioned  in the documentation, but there seems to be no way to invoke them. If they are no longer supported, it would be clearer to start with "The settings (cpu_shares, cpu_quota, cpuset, mem_limit, memswap_limit, mem_swappiness) are no longer supported in Compose file version 3."

Is the section 'reservations' new, did you just add it? I don't remember seeing there before.

**Comment by londoncalling** [comment]
@kolotyluk I added some links and a note to clarify this a little more, in the referenced PR ^^

I checked back on the file history for Compose file version 3 (got to [/compose/compose-file-reference/index.md](https://github.com/docker/docker.github.io/blob/master/compose/compose-file/index.md) and click **History** in upper right to see the related PRs and commits), and the `reservations` section has been there since at least February of this year.

Regarding the error messages you get, I have less control over that. For that kind of thing in general, you'd want to log an issue directly on the repository for the codebase, e.g., in this case the [Compose codebase](https://github.com/docker/compose/) as opposed to `docker.github.io` which is more specific to docs.
