### ISSUE TITLE
Add detail about failure modes when swarm has 7 managers

### ISSUE THREAD

**Issue by JimGalasyn** [docker/docker.github.io#4546]
[Set up high availability](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/set-up-high-availability/#size-your-deployment) currently says:

"Adding many manager nodes to the cluster might lead to performance degradation, as changes to configurations need to be replicated across all manager nodes. The maximum advisable is 7 manager nodes."

We should add some details about this performance degradation. @vsaraswat

**Comment by joaofnfernandes** [comment]
The maximum advisable being 7 managers is kind of a rule of thumb (also used by other distributed systems), and I'm not sure if we have any data around the performance degradation that happens as you add more nodes.

But at a high level here's how things work. Let's imagine that you create a new docker service, so the service definition will (eventually) be persisted in all manager nodes:
* The client does `docker service create`
* The manager node currently serving as leader will store the service definition but this change is not committed yet, meaning that if this leader dies the service definition will be lost
* The leader will send the service definition to all other managers
* The leader waits until a majority (n/2+1) of managers acknowledge that they've got the service definition
* The leader commits the change, meaning that from a cluster perspective the new service is created, and if the current leader dies, enough nodes know about the service

All this is a bit of work, and the amount of work will grown linearly with the number of nodes.
There's also a bit of extra work that needs to happen if you don't have a client creating services:
* When a leader exists, the leader needs to frequently (~300ms) ping the other managers so that they know the leader is alive
* When the leader dies (nodes think the leader is dead because they didn't get pinged for a while so the leader can also be alive and its just a slow network), the manager will start a new election process to elect a new leader for the cluster.

This last task will also take time proportional to the number of nodes since a new leader only gets elected if a majority of nodes (n/2+1) votes for it.
