### ISSUE TITLE
Duplicate heading1

### ISSUE THREAD

**Issue by scjane** [docker/docker.github.io#4589]
File: [engine/extend/index.md](https://docs.docker.com/engine/extend/), CC @mstanleyjones

**Comment by scjane** [comment]
![2-titles](https://user-images.githubusercontent.com/25146885/30323360-8712f7f8-97ef-11e7-9db6-ab1ec0109708.jpg)

**Comment by scjane** [comment]
Some other pages under "Extended Engine" also have this problem.

**Comment by mstanleyjones** [comment]
This is because these files are sourced from upstream resources. Those upstream locations expect the files to be viewed directly on Github, so they need H1 headers there, but the H1 headers are superfluous in the docs. I'm not 100% sure the best way to fix this. cc/ @johndmulhausen (who is currently on vacation). This is a very low priority.

**Comment by johndmulhausen** [comment]
Fixed in https://github.com/docker/cli/pull/623

**Comment by joaofnfernandes** [comment]
This fix has made its way into the docs.
