### ISSUE TITLE
Feedback for: engine/installation/linux/debian.md

### ISSUE THREAD

**Issue by choralqiu** [docker/docker.github.io#500]
URL: [https://docs.docker.com/engine/installation/linux/debian.md](https://docs.docker.com/engine/installation/linux/debian/)
When I run sudo apt-get update, I have the error of 
> Err:10 https://apt.dockerproject.org/repo debian-xenial/main armhf Packages 403  Forbidden

I do have the "/etc/apt/sources.list.d/docker.list" edited with an entry. Any ideas? Thank you in advance

**Comment by mstanleyjones** [comment]
Hi, others have faced similar issues, as seen in https://github.com/docker/docker/issues/20192. One of the troubleshooting steps is to make sure the time is set correctly on your computer. Please have a look through those and also consider searching on forums.docker.org. Let me know if you find your specific problem so that we can determine whether it needs to be documented.
