### ISSUE TITLE
案例与代码不符合

### ISSUE THREAD

**Issue by mds1455975151** [docker/docker.github.io#5070]
File: [engine/admin/volumes/volumes.md](https://docs.docker.com/engine/admin/volumes/volumes/), CC @mstanleyjones

**Comment by mds1455975151** [comment]
修改案例代码，例如：
docker service create -d \
--replicas=4 \
--name devtest-service \
--mount source=myvol2,target=/app \
nginx:latest

**Comment by joaofnfernandes** [comment]
@mds1455975151 can you point me to the example that's wrong, and explain what is wrong about it?

**Comment by arush-sal** [comment]
@joaofnfernandes I guess what @mds1455975151 is trying to say here is, In the code sample mentioned in [here](https://docs.docker.com/engine/admin/volumes/volumes/#start-a-service-with-volumes) it says
>The following example starts a nginx service with four replicas, each of which uses a local volume called myvol2.

But `--replicas=4` is missing from the code sample which reads:
```
$ docker service create -d \
  --name devtest-service \
  --mount source=myvol2,target=/app \
  nginx:latest
```
Instead of this it rather should be:
```
$ docker service create -d \
--replicas=4 \
--name devtest-service \
--mount source=myvol2,target=/app \
nginx:latest
```
Let me know if that is correct/makes sense. I'll be more than happy to submit the repective PR :)

**Comment by joaofnfernandes** [comment]
@arun-gupta I get it now! Do you want to whip up that PR then? Don't forget to also update the snippet below with `docker service ps ...`.

p.s. That domain you've got is pretty sweet! Let me give a thumbs up to that 👍👍

**Comment by arush-sal** [comment]
@joaofnfernandes I guess you made a typo there :sweat_smile:. Anyway, I'll send the PR sometime later today with the updated docs. Thank you :)

**Comment by mds1455975151** [comment]
Arush-sal said yes, I asked questions, but probably didn't explain. Thank you arush-sal.
