### ISSUE TITLE
Creating Client Certificates

### ISSUE THREAD

**Issue by Luk3rson** [docker/docker.github.io#5144]
File: [engine/security/certificates.md](https://docs.docker.com/engine/security/certificates/), CC @mstanleyjones

Hi a quick question,
Is it possible to expand information in creating of Client Certificates also about **where** you need to create them?

Thank you
Lukas

**Comment by joaofnfernandes** [comment]
That article is a little bit confusing 😞 @Luk3rson can you explain what are you trying to achieve?

**Comment by Luk3rson** [comment]
Hey,
thank you.
I created certificate via StartCOM. I wanted to use that in docker, but as this Authority is also not trusted I need to include CA and client.crt to my docker installation.
To do that I tried to follow up this documentation.

But it is not for me clear where I need to create certificate for client.
Do I need to generate my private key from client, then create new certificate on client and just copy CA certificate from server to client?

Thank you,

**Comment by joaofnfernandes** [comment]
I'm still not 100% sure on what you want to achieve, but I'll assume that you want to configure the Docker daemon to listen on a TCP port, and secure it with mutual TLS, so that only authorized clients can make requests.

1. Make sure you have all the files needed for setting up a TLS server and client. If you are using a CA like StartCom, you need to ask them for these files.
    * For the server - CA's public key certificate, private key for the server, and public key certificate for the server
    * For the client - Ca's public key certificate, private key for the client, and public key certificate for the client.
2. Configure the Docker daemon to use these files. You can do this by passing flags when starting the Docker daemon, or by adding properties to the `daemon.json` file.

    Here's an example of the flags you need to use when starting Docker:
    ```
    /usr/local/bin/dockerd -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 \
    --tlsverify \
    --tlscacert=/certs/ca.pem \
    --tlscert=/certs/server.pem \
    --tlskey=/certs/server-key.pem
    ```

    [You can check the daemon.json equivalent here](https://docs.docker.com/engine/reference/commandline/dockerd/#on-linux).

3. Configure your Docker client to use the client certificates. There's a couple of options for this, but you can add the client certificate files to `~/.docker/`, and make sure they're named `ca.pem`, `cert.pem`, and `key.pem`.

---

If you're question is not about the Docker daemon, but about how to set up a Docker registry with TLS:

1. [Deploy the registry with TLS as explained here](https://docs.docker.com/registry/deploying/)
2. If your CA is trusted by your operating system (I believe that StartCom should be), then you should not have to do anything. Otherwise, you need to configure your Docker daemon or operating system to trust that CA. [Here's an example on how to do that](https://docs.docker.com/datacenter/dtr/2.3/guides/user/access-dtr/).

I'll close this issue, but I've created #5167 for us to improve the docs regarding TLS.
