### ISSUE TITLE
incorrect manual

### ISSUE THREAD

**Issue by zappbrannigan34** [docker/docker.github.io#5243]
**File: [engine/installation/linux/docker-ce/ubuntu.md](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/), CC @mistyhacks

root@docker-mobile:~# docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
root@docker-mobile:~# curl https://registry-1.docker.io/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}**

**Comment by mistyhacks** [comment]
Hi @zappbrannigan34, if this is an installation without access to hub.docker.com, you need to specify what registry to pull from and that registry needs to have a copy of the `hello` image, for this to work. This is an edge case, because the vast majority of users do have access to hub.docker.com. To specify your registry, use the `docker login` command, which takes the registry URL as a parameter. To see all the options, run `docker login --help` or see https://docs.docker.com/engine/reference/commandline/login/.
