### ISSUE TITLE
Docker cannot remove Directory..Because the directory is unempty...

### ISSUE THREAD

**Issue by LahariGuntha** [docker/docker.github.io#5253]
Hi,
My docker Info:
docker info:
```
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 15
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: false
 Native Overlay Diff: false
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: docker-init
containerd version: 50fad48c7bb0c4cfa14385bdb3f77da90739404d (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 50fad48c7bb0c4cfa14385bdb3f77da90739404d (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker-latest/seccomp.json
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: OpenShift
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 8
Total Memory: 15.67 GiB
Name: eclipseche
ID: 7TWM:RBJ5:ALMZ:5LAM:ZHJZ:YCGU:WNC5:LLHS:BGFG:UMCP:QYKN:4JZX
Docker Root Dir: /var/lib/docker-latest
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: registry.access.redhat.com (secure), docker.io (secure)
```

My Host:
RHEL 7.2

Output of command:uname -a
```
Linux eclipseche 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
```

I want to remove some directories in a docker container.Then it is throwing Error as below:

```
rm: cannot remove '/home/user/che/ws-agent/bin': Directory not empty
 rm: cannot remove '/home/user/che/ws-agent/conf/Catalina': Directory not empty
 rm: cannot remove '/home/user/che/ws-agent/lib': Directory not empty
 rm: cannot remove '/home/user/che/ws-agent/logs/archive/2017/11/06': Directory not empty
 rm: cannot remove '/home/user/che/ws-agent/logs/logs': Directory not empty
rm: cannot remove '/home/user/che/ws-agent/maven-server': Directory not empty
 rm: cannot remove '/home/user/che/ws-agent/temp/indexes': Directory not empty
 rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/META-INF/maven/org.eclipse.che.assembly-multiuser/assembly-wsagent-war': Directory not empty
 rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/WEB-INF/classes/codenvy': Directory not empty
 rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/WEB-INF/classes/org/eclipse/che/wsagent/server': Directory not empty
 rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/WEB-INF/lib': Directory not empty
 rm: cannot remove '/home/user/che/ws-agent/work/Catalina/localhost': Directory not empty
```

**Comment by londoncalling** [comment]
@LahariGuntha Can you give the full `rm` command you are trying to run, and the output?

**Comment by LahariGuntha** [comment]
[root@eclipseche ~]# docker exec -it 6d08256486ad bash
user@6d08256486ad:/projects$ cd /home/user/che/ws-agent/
user@6d08256486ad:~/che/ws-agent$ ls
bin   lib      LICENSE-logback.txt  LICENSE-slf4j.txt   logs          NOTICE         RUNNING.txt  webapps
conf  LICENSE  LICENSE-mit.txt      LICENSE-tomcat.txt  maven-server  RELEASE-NOTES  temp         work
user@6d08256486ad:~/che/ws-agent$ rm -rf /home/user/che/ws-agent/bin/
rm: cannot remove '/home/user/che/ws-agent/bin/': Directory not empty
user@6d08256486ad:~/che/ws-agent$

**Comment by LahariGuntha** [comment]
Hi,

I am entering into my container and trying to delete my Folder...But I cannot ...It is showing Error like:
Cannot remove directory..Directory is not empty..as shown below..

docker exec -it 6d08256486ad bash
user@6d08256486ad:/projects$ cd /home/user/che/ws-agent/
user@6d08256486ad:~/che/ws-agent$ ls
bin   lib      LICENSE-logback.txt  LICENSE-slf4j.txt   logs          NOTICE         RUNNING.txt  webapps
conf  LICENSE  LICENSE-mit.txt      LICENSE-tomcat.txt  maven-server  RELEASE-NOTES  temp         work
user@6d08256486ad:~/che/ws-agent$ rm -rf /home/user/che/ws-agent/bin/
rm: cannot remove '/home/user/che/ws-agent/bin/': Directory not empty

**Comment by LahariGuntha** [comment]
Is it something related to Kernel Version??

**Comment by LahariGuntha** [comment]
Is it something related to my Filesystem??
Storage Driver: overlay2
Backing Filesystem: xfs
Supports d_type: false

**Comment by thaJeztah** [comment]
I see quite a lot of things that are problematic in the output of `docker info`;


First of all; I see you're running the Red Hat fork of Docker, which is an unofficial version, and contains [_many_ changes to the source code](https://github.com/moby/moby/compare/v1.13.1...projectatomic:docker-1.13), some of which are known to cause issues.

Your installation is also running non-matching versions of `containerd`, `runc` and the `init` binary; you an see in the output that the versions that are installed do not match the expected versions;

```
containerd version: 50fad48c7bb0c4cfa14385bdb3f77da90739404d (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 50fad48c7bb0c4cfa14385bdb3f77da90739404d (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
```

Using incompatible versions will cause various problems.

The `seccomp` profile that's used is not the default profile; while this may be on purpose (i.e. you installed a custom profile), having an non-default profile can be a security risk, because it may be more permissive, and expose you to vulnerabilities that are blocked by the default profile;

```
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker-latest/seccomp.json
```

You're running `overlay2` with `xfs` as backing filesystem, but it doesn't have `d_type` support;

```
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: false
 Native Overlay Diff: false
```

Running overlay (or overlay2) on XFS without `d_type` is known to cause issues. Docker currently "allows" it for backward-compatibility, but will block it in future, you'll see a warning being logged about this as well when starting the daemon;

```
overlay: the backing xfs filesystem is formatted without d_type support,
which leads to incorrect behavior. Reformat the filesystem with ftype=1
to enable d_type support.
Running without d_type support will no longer be supported in Docker 17.12.
```

Also see these issues, which contain some information https://github.com/moby/moby/issues/10294, https://github.com/moby/moby/issues/29873.

The RHEL release notes mentions this; https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html

> Note that XFS file systems must be created with the `-n ftype=1` option enabled for use as an overlay. With the rootfs and any file systems created during system installation, set the `--mkfsoptions=-n ftype=1` parameters in the Anaconda kickstart. When creating a new file system after the installation, run the `# mkfs -t xfs -n ftype=1 /PATH/TO/DEVICE` command. To determine whether an existing file system is eligible for use as an overlay, run the `# xfs_info /PATH/TO/DEVICE | grep ftype` command to see if the `ftype=1` option is enabled.
> Note that OverlayFS provides a restricted set of the POSIX standards. Test your application thoroughly before deploying it with OverlayFS.

Support for `overlay2` is disabled by default on old (3.10) kernels, and not fully supported on RHEL 7.2 (it became [officially supported in RHEL 7.4](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/single/release_notes/#new_features_2), but requires a flag to override the kernel version check).


Last but not least; Docker 1.13.1 has reached End-of-life last April, and is no longer maintained (the "Enterprise Edition" of Docker 1.13.1 / Docker EE 17.03 is still supported if you have a subscription).

Although there may be different causes for your problem, I recommend to:

- Fix the issue with the XFS filesystem, or switch to a different storage driver ([devicemapper](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/) would be the alternative on RHEL and CentOS)
- Make sure to have a fully up-to-date system. Docker (and containers in general) use kernel features that are constantly improved; having an up-to-date kernel version is therefore important. The Red Hat kernels are several years old, but their kernel team backports fixes and features to those kernel versions, so try to keep on a current version of their kernel.
- Install the official [Docker EE for RHEL](https://docs.docker.com/engine/installation/linux/docker-ee/rhel/) package (alternatively, you can try installing the community edition [Docker CE for CentOS](https://docs.docker.com/engine/installation/linux/docker-ce/centos/) package, but it's not officially supported, and untested on RHEL)

We cannot provide support for the Red Hat fork of Docker, so if (for whatever reason) you cannot switch to the official packages, I'd recommend opening a ticket with Red Hat support.


I'm closing this issue because of the above, but feel free to comment after I closed
