### ISSUE TITLE
EE Upgrade path - Add New : Remove old

### ISSUE THREAD

**Issue by okrangerb3** [docker/docker.github.io#5255]
File: [enterprise/upgrade.md](https://docs.docker.com/enterprise/upgrade/), CC @johndmulhausen 

Upgrade path - Add New : Remove old

Upgrade Methods
 
Method 1)
With the intention to avoid potential issues during upgrade.  Where possible try to introduce a new updated node.  Once you are satisfied with the introduction and you are able to add workloads and all is well, drain an old node and proceed through the removal steps.
 
	1.	Introduce new upgraded node 
 
	2.	Drain the node - Docker node update drain 
 
	3.	Docker ps (if empty proceed) if not ensure process are killed off.
 
	4.	Swarm leave
 
	5.	Kill node
 
 
Method 2)
If logistically you are unable to introduce a new node and remove an old, the instructions for the in-place upgrade is below.   This method does not give you a clean os and a clean slate to work from unless you rebuild the os and then work up from there.
 
https://docs.docker.com/enterprise/upgrade/

**Comment by joaofnfernandes** [comment]
This upgrade path works in theory and the devil is in the details and order of operations, so before documenting this I would like us or the quality engineering team to really test this through.

There's also a couple of high-level things that users should be concerned about:
* You need to be careful when provisioning that new node to make sure it has enough resources (RAM, CPU, disk, …) to completely handle the new workloads
* You need to be careful with stateful apps. If you’re persisting state in the local filesystem you might not be able to evict that workload to other node
* In enterprise companies it's not easy for someone to just get new nodes. Usually you need to go through an approval and vetting process, so we still need to document the 2nd method explained here.

**Comment by okrangerb3** [comment]
There's also a couple of high-level things that users should be concerned about:
<--FYI this method is currently being used by one of our very large customers.--

You need to be careful when provisioning that new node to make sure it has enough resources (RAM, CPU, disk, …) to completely handle the new workloads.  <--Once an IT organization gets into this type of upgrade mentality I believe this will help them solve many challenges.--

You need to be careful with stateful apps. If you’re persisting state in the local filesystem you might not be able to evict that workload to other nodes. <-- In any special occasion this particular method does not work then yes they would have to revert back to a traditional in-place upgrade. --

In enterprise companies it's not easy for someone to just get new nodes. Usually you need to go through an approval and vetting process, so we still need to document the 2nd method explained here. <--So Most technology being used today either takes a backup or some type of snapshot.  The clear objective would be getting the os back to a freshly installed state or after configuration prior to installation.  So having a snap of all the vm's in the environment or a backup of the state in the prime condition plus one extra would make this possible in a circularly fluid way. --

Hope this gives you more Ideas, please let me know if there is anything I can assist with.  I do have 2 customers that really like this plan and would have saved them a lot of grief and time.

Thanks again,
Brent

**Comment by joaofnfernandes** [comment]
I also believe this upgrade path is way better since there's less chance for machines to be configured in different ways and medium-long term this prevents a lot of headaches. I just want for us to test this out and be aware of all the edge cases that might get in the way and cause users to lose data.

I'm specially concerned with the scenario where users have a full Docker EE deployment with UCP, DTR, and their own custom apps (some running as bare containers, some running as Docker services). In this scenario it's not obvious to me:
1. How to evict bare containers. It's not just a matter of doing a `docker node update --availability drain`, since that will only work for Docker services. Maybe adding a constraint to the container and redeploying it would do the trick.
2. Given that a DTR replica runs as a set of bare containers, and a DTR HA deployment also needs to maintain quorum, it's not obvious how DTR will behave during an upgrade like this. Even if you're running DTR with non-HA (a single replica), I'm not sure what the recommendation would be.

If you're seeing users doing this, maybe you have some insights into these issues and how we should advise users.

**Comment by okrangerb3** [comment]
Hi Joao, Just curious if there has been any update on this as we have had yet another large customer fall down due to the current upgrade path?

**Comment by ericsmalling** [comment]
Regardless of the two strategies, when upgrading the engine on DTR replicas we probably need to have a prescribed way to shut down all of the DTR containers before stoping the node.  Either that or we need to tell people to stand up and join the new node to the swarm, perform a DTR join on it and then do a DTR remove on the old one before stopping and removing the old node.

This is due to the the bugs in attachable overlay networks with unmanaged containers which all of the dtr-* containers are.

This is what bit us at GSK, the dtr-ol network was corrupted because of the shutdown of a dtr node while those containers were up.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by programmerq** [comment]
This is still something that comes up from time to time and would still be beneficial to touch on in a refactor.
