### ISSUE TITLE
Management commands has less documentation than deprecated ones

### ISSUE THREAD

**Issue by DamianFekete** [docker/docker.github.io#5303]
File: [engine/reference/commandline/container_run.md](https://docs.docker.com/engine/reference/commandline/container_run/), CC @mistyhacks

In comparison with the [`docker run`](https://docs.docker.com/engine/reference/commandline/run/) page the `docker container run` page is **missing**:
- the extended description
- the many examples

For a new comer to docker it's hard to see that `docker run` is **deprecated**. The only information I can find about this and what `Management commands` are under `Docker CLI` docs is 
```DOCKER_HIDE_LEGACY_COMMANDS When set, Docker hides “legacy” top-level commands (such as docker rm, and docker pull) in docker help output, and only Management commands per object-type (e.g., docker container) are printed. This may become the default in a future release, at which point this environment-variable is removed.```

Also there is an **asterisk** after `docker container *` in the navigation tree on the left, but I can't find where the `*` is explained.

Let me know if I need to split this ticket into multiple ones.

**Comment by mistyhacks** [comment]
This content is all managed upstream in `docker/cli` repo. The docs have a build process that takes the `## Description` and `## Examples` sections from files in https://github.com/docker/cli/tree/master/docs/reference/commandline files and adds them to the docs. If you feel like examples should be moved from, for example, `run` to `container run`, you can submit a PR to do that. 👍 Be careful about using terms like "deprecated" though, as the `docker run` command is certainly not deprecated.

In a perfect world, there would be the ability in the command parser (Cobra) to recognize command "aliases" and consolidate the docs for them all, but I do not believe this is currently possible.  cc/ @dnephin @thaJeztah for confirmation.

As for the `*`, it is just a placeholder that shows that if you expand that section, you will find all the sub-commands. So the `docker container *` section expands to show all of the sub-commands like `docker container run` and `docker container stop`.

As this specific issue is about content that is actually in a different repo, I'll close the issue here. Thanks for your feedback!
