### ISSUE TITLE
Practical guide to logging in to docker store and consuming images - please 

### ISSUE THREAD

**Issue by adrianblakey** [docker/docker.github.io#5307]
File: [docker-store/faq.md](https://docs.docker.com/docker-store/faq/), CC @johndmulhausen

Please could you spell out specifically how I consume a specific image, e.g. jre8?

I have tried various combinations of:

docker login -u adrianblakey -p xxxxxxx https://store.docker.com
docker pull store/oracle/serverjre:8
docker pull  https://store.docker.com/store/oracle/serverjre:8
docker pull  store.docker.com/store/oracle/serverjre:8

**Comment by adrianblakey** [comment]
TY - that works.

One more question - how do I make this a remote repo in Artifactory?
Artifactory is expecting the URL of a repo to which it can connect - so is
there a "hidden" , "default" URL that the docker client connects to when
you run docker login?

Adrian Blakey
adrianblakey@gmail.com
Skype: adrianblakey
(510) 747-8057

**Comment by joaofnfernandes** [comment]
Can you try using `docker.io/store/oracle/serverjre:8` and see if it works?

I've filed an internal issues against Docker Store so that we can improve the login/pull experience. I don't think there's any point in updating the docs, since no one will search there on how to overcome this problem.

For that, I'm closing this issue, but feel free to comment.
