### ISSUE TITLE
unable to browse Docker Windows Containers with transparent network 

### ISSUE THREAD

**Issue by vazkarvishal** [docker/docker.github.io#5342]
### Connectivity Issue using transparent networks

I am trying to build a POC using an ASP.Net app using MSSQL. However, Because of poor performance over NAT I have tried using transparent networks to see if it resolves the issue.

I have used the code below to create the new transparent network
`docker network create -d transparent --subnet=10.10.10.0/24 --gateway=10.10.10.1 tnet`

and then using it in my compose file as shown below:
![image](https://user-images.githubusercontent.com/13076513/33042588-39c95682-ce3a-11e7-9039-60baf2135c14.png)

However, when I try to connect to either:

1. The IIS instance using the stats OR 
2. The MSSQL instance using local SQL Server Management Studio

But none of them work. I have also tried adding the subnet which I created as a part of the transparent network to my local inbound firewall rules but it does not seem to make any difference.

Can anybody help me out with this?

I am using Docker version 17.09.0-ce, build afdb6d4 if that helps.

**Comment by gbarr01** [comment]
Hi, @vazkarvishal , this does not seem to be a Docker Docs issue. If it is, can you provide the page that is giving you trouble? 

- This seems more like an question for Docker Forums: https://forums.docker.com/
- Otherwise, maybe file it here? https://github.com/Microsoft/mssql-docker
- Does this issue resemble yours? https://github.com/Microsoft/mssql-docker/issues/78
- Another reference: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking

If this is indeed a Docker Docs issue, feel free to reopen with the problematic page. Thanks.
