### ISSUE TITLE
Missing basic info on base URL + auth

### ISSUE THREAD

**Issue by gsaslis** [docker/docker.github.io#5349]
File: [registry/spec/api.md](https://docs.docker.com/registry/spec/api/), CC @joaofnfernandes 

wanted to give the registry API a try. 
Couldn't easily find: 

a. the base URL that all documented endpoints live on (stackoverflow helped find it's `https://registry.hub.docker.com`)
b. a section on authentication, with a basic example (please! :) ) `An RFC7235 compliant authorization header.` does help, but you're just making my life harder ;)

**Comment by joaofnfernandes** [comment]
@gsaslis keep in mind that the docs you are pointing to are for Docker Registry, which you can deploy and manage yourself.
Docker Hub and Docker Store don't have an officially supported API. It's true that they use Docker Registry under the hood, so you might be able to infer some of the endpoints, but it also means those products can change their APIs and break your integrations.

Since there's no action item for docs, I'm going to close this issue, but feel free to comment.

**Comment by gsaslis** [comment]
@joaofnfernandes thanks for clarifying that. is there another doc I could reference to find the information I was looking for?

WDYT about adding docker hub examples, for the benefit of everyone else?

**Comment by joaofnfernandes** [comment]
Unfortunately the answer is no.
As much as I love seeing the community build cool things with Docker Hub, the reality is that Docker Hub doesn't have a public API, and we only document public APIs.

The rationale for this is that as a consumer of APIs you expect any API that is fully documented to not change, or at least implement some sort of versioning scheme if things change. It's a lot of work to build integrations, and having APIs changing under your feet is a real headache.

So while I understand your feedback, I think the right thing to do is to not document APIs that are private and that can change without notice.
