### ISSUE TITLE
It should remind developers the network's diffrence on Windows/MacOS in compose file reference's network_mode

### ISSUE THREAD

**Issue by SaekiRaku** [docker/docker.github.io#5455]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @gbarr01

I've create 6 containers with redis in it, and try to create a cluster based on MacOS Docker. So I need to use network_mode: "host" to let redis can bind IP on host machine. Then the redis print some error that redis can't bind ip:port.

I don't know what's going on, it take me whole afternoon to fix it, and I faild 😂. And this morning, I re-read the document on container's network, and I find out this:

<img width="789" alt="qq20171207-084827 2x" src="https://user-images.githubusercontent.com/12109558/33693636-e0b63fd6-db2e-11e7-9545-3caa78499518.png">

I think such as this special situation, it should remind developers on every where in the documents. Especially for some not good at English's developers in the world (like me, it take me a long time to read and understand the documents).

**Comment by joaofnfernandes** [comment]
You don't need to use `network_mode: host` to bind the Redis container to a port in your host. Also, if you are deploying 6 containers, it's possible that you are deploying all of them with the same port. Since only a single container can bind to a port at a time, you will see errors like `can't bind port` when you deploy your second container.

Also, there is no difference of behavior in Docker for Mac and Windows. That disclaimer is there to explain that if you run `ifconfig` you will see different results if you're running Docker in Linux or Docker for Mac/Win.

I'm going to close this issue because it mixes a couple of things, and I'm not sure what can we fix to make things simpler.
But try checking https://github.com/Grokzen/docker-redis-cluster. It seems to deploy a Redis cluster, so you can use it as an example to build what you want.

**Comment by SaekiRaku** [comment]
@joaofnfernandes My apologize, I didn't describe clearly, I mean it have different behavior between Linux and MacOS / Windows and it takes me a long time to find it out through the document. And I'm using different ports in the config, and then after I start the container MacOS come error, but on CentOS is successfully running the container with the same config. And I think it should remind others, in the docker-compose -> network_mode.

![qq20171208-143635](https://user-images.githubusercontent.com/12109558/33754038-7205b6dc-dc25-11e7-9144-1e660a8219b5.png)

**Comment by joaofnfernandes** [comment]
@thaJeztah any guesses on why there's inconsistent behavior between macOs and CentOS in this scenario?

**Comment by joaofnfernandes** [comment]
Yes, I think your diagram is correct, and that's why it's possible that `network_mode: host` is having different behaviors. In Docker for Mac/Windows, `network_mode: host` will make your containers  use the Docker VM network stack, not the host network stack.

As a workaround try removing `network_mode: host` from your compose file, and that should make the behavior consistent between Mac and CentOS.
