### ISSUE TITLE
Approach to mount temporary file while using docker build 

### ISSUE THREAD

**Issue by lcconly** [docker/docker.github.io#5483]
File: [index.md](https://docs.docker.com/), CC @johndmulhausen
Hello, I find docker 1.10.1 support using -v to mount local files while building a new image to access the image  to visit the files. While in the later version, this function has been removed. Is there any similar ways to add file temporarily to the image instead of using wget or curl? If I use COPY, ADD or VOLUMES in the dockerfiles, it may increase the size of image. So, I hope to find a way to add temporary files.

**Comment by joaofnfernandes** [comment]
Have you tried [multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/)? You can create a temporary image that has the files you need to compile/build your final output. The you can just copy that output to a new image, so that the final build image is really small.

Given that there's nothing to do here, I'll close this issue, but feel free to comment.
