### ISSUE TITLE
Demystify: directory layout

### ISSUE THREAD

**Issue by otzoran** [docker/docker.github.io#5521]
File: [engine/userguide/storagedriver/imagesandcontainers.md](https://docs.docker.com/engine/userguide/storagedriver/imagesandcontainers/), CC @mistyhacks
would be helpful to show this:
```bash
root@madock:~# ls -la /var/lib/docker/
total 52
drwx--x--x   13 root     root          4096 Dec 14 22:38 .
drwxr-xr-x    4 root     root          4096 Nov 19 15:15 ..
drwx------    5 root     root          4096 Nov 19 15:15 aufs
drwx------    2 root     root          4096 Nov 19 15:15 builder
drwx------   11 root     root          4096 Dec 11 21:39 containers
drwx------    4 root     root          4096 Nov 19 15:15 image
drwxr-x---    3 root     root          4096 Nov 19 15:15 network
drwx------    3 root     root          4096 Nov 19 15:15 overlay2
drwx------    4 root     root          4096 Nov 19 15:15 plugins
drwx------    2 root     root          4096 Nov 19 15:15 swarm
drwx------    2 root     root          4096 Dec 14 22:38 tmp
drwx------    2 root     root          4096 Nov 19 15:15 trust
drwx------   22 root     root          4096 Nov 25 23:06 volumes

```
and explain the purpose of each subdirrectory, what's covered in this page and what's not.

**Comment by mistyhacks** [comment]
We do explain the purposes of the directories in the relevant locations (such as when discussing the individual storage drivers). `/var/lib/docker/` is managed by Docker itself and its contents are an implementation detail. You shouldn't be interacting with them directly.

cc/ @thaJeztah for verification.

**Comment by thaJeztah** [comment]
Correct; even though the contents is not a "secret", the `/var/lib/docker` directory's content should be exclusively accessed by the docker daemon (and related binaries). The reason we don't document the contents of that directory is that its content and layout can change at any time, so should not be seen as a stable "contract" / "api".

One example is the migration to containerd 1.0, which is set in motion in the Docker 17.11 release; storage-drivers and location of storage for images will change in future when docker starts delegating these parts to containerd.

My suggestion would be to rewrite that page (where possible) to explain the general concept without referring to the (current) implementation.

For example;

  - Instead of `sudo du -sh /var/lib/docker/containers/*` to show the size of each container, use a combination of `docker system df` and `docker container ls --size` (which shows the same information)
  - Instead of `ls /var/lib/docker/aufs/layers`, use `docker image inspect` to show that an image references layers (we can show that inspecting images that "extend" each other share the same layers);

    ```bash
    $ docker image inspect --format '{{json .RootFS.Layers }}' 61a3569f8a4d | jq .
    [
      "sha256:a75caa09eb1f7d732568c5d54de42819973958589702d415202469a550ffd0ea",
      "sha256:10d2c145fb9412c93788cdd8a4bb4304753cfebb55f7c117a0b7d9178c919099",
      "sha256:4e37725cf3ca9887725b9ff6f6758b258645eb1254663682f6dd064a0bba00e2",
      "sha256:38f541b19697f704a546f038a6de806bb7fd744b917175e393617801143f6f80",
      "sha256:7130de150987145d64aab6d28d2f4818b14585a31ccbb1afc8852f999090e6c9",
      "sha256:08734d55553a5e86eedb73f9abe216a3a2247a87708177122940acd52fb92d2f",
      "sha256:11950fb5a910278005f99d9e01e541f1ba0d1a3151a4422a824d3796f2be2419",
      "sha256:03d2e06abeaa1c76ce32e46f2f5716fe5da17441ae4a624f245e877531dce476",
      "sha256:d99905722e372c32a4f9b8e211b14d26284bc6e6c1f26493b73757d47d8463de",
      "sha256:1f1c071b210122dbbdd112221d342f7d03c5dc3da6aaf8ec00e6ec033242e4cc",
      "sha256:8b74c8b62d173f0ad837c7e2e380eb1ae998300ff19c4cb4cad501ecba8186bd",
      "sha256:86e3dd157917f5012e97622e5a5357fe530a26854c2e5df9e59b1ab9eab29e83",
      "sha256:76eab301394ce4bc40fd6ab01cdef90b09ce261ef7e378e22431ef66a8e654ca",
      "sha256:05edfa74ea715669216622b8f2de765f5e67233d6f4c180b32f6b204d9d03242",
      "sha256:7c32f471ea7deb43ea934ba9b8d3be98d0f2913be9b6bb76b14cfa45fa1a57ea",
      "sha256:fa6601d21e417239356026865c5d50784d61fc59577617400ac44bb65f50c9b6",
      "sha256:8c9766a9f099357f9db1683ade98f77ddd66fb6d799e07e1b9207e7496ff751e",
      "sha256:672b5ac3b31709cd1d6cc782fc75b57ed2e40883a847a15138252a93d8075b62",
      "sha256:53b638d1bf47c5191bc73c2ab5e2abc21e174486b9211ce2190cabc5ef49a36c",
      "sha256:c8ebaed1936f96dca73671a251a793f946f44525a0124f058a304d7c8be4192c",
      "sha256:8a0c786035cd8a33b2e7f5bac5100178cec7765990d9645d21d8312c43c14dcf",
      "sha256:81648635e15fabc3bfad559b911c8594750cbb82b4c6f051a84d98f6f7524c9a",
      "sha256:9f97f534a178670e0ef05cfe96a58aa85c5dd3c750ea732b14719909e702ec3a",
      "sha256:77bf069ae938844e1634b4c27fa785f10d53bcfa01341acb5362adbadea1b775"
    ]
    ```

## Internals section

Not sure about this one; this is probably more something for the Moby project, but we _could_ add a "Docker internals" section to document the technical design, and working of Docker

**Comment by otzoran** [comment]
@thaJeztah , @mistyhacks 
First, thank you for the (surprisingly fast) response and detailed answer.  
I think that telling the newcomer what's the current state of the art (e.g. you'll encounter those subdirs, they correspond to [1] storage drivers [2] volumes [3] container work layer, etc) is a good clarification **before** hand. I'd also add a small `cat /proc/filesystems` to tie the obscure references to "drivers in your kernel". 

RE: "We do explain the purposes ..." 
yes, of course. But you have to read all the pages in "Store data within containers" twice to reconnect the dots: 1st pass to single out all the interactions without understanding them, 2nd pass to flash it to memory. 

RE: "The reason we don't document the contents ..." 
IMHO, given the number of abstractions one has to deal with, at this point in the doc, anchoring the reader to the actual filesystem layout is clarifying. Scarifying the abstraction for the sake of understanding isn't a crime (at least for K&R era C programmers :-)

Anyhow that's my 2 cents, thank you and keep up the good work

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
