### ISSUE TITLE
Documentation gives instructions that make all containers disappear

### ISSUE THREAD

**Issue by COLABORATI** [docker/docker.github.io#5592]
File: [engine/userguide/storagedriver/selectadriver.md](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/), CC @mistyhacks

I followed the instructions to change the default filesystem to overlay2 - after that all my containers have disappeared. Yes, I know how to restore (maybe) - but the documentation is inacceptable - first, there is NO WARNING given about the fact that changing the fs will destroy all containers. Second there is no information given how to transfer the old containers to the new filesystem. 

The documentation just describes a clear path to destroy all containers on a machine. It feels like the author had a good sadistic laugh writing this - the outcome seems very predictable.

**Comment by mistyhacks** [comment]
You are correct. We expect you to read the more detailed docs about each individual driver. For instance, the following topic does warn you about this: https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/#prerequisites

> Changing the storage driver will make any containers you have already created inaccessible on the local system. Use docker save to save containers, and push existing images to Docker Hub or a private repository, so that you not need to re-create them later.

I think the correct fix is to remove the generic instructions from the overview driver so that people will read the details for their driver.
