### ISSUE TITLE
how do I specify 'nocopy' in '--mount' syntax?

### ISSUE THREAD

**Issue by stheine** [docker/docker.github.io#5601]
File: [engine/admin/volumes/volumes.md](https://docs.docker.com/engine/admin/volumes/volumes/), CC @mistyhacks

How do I specify this `--volume` statement in `--mount` syntax?

```
--volume vmail:/home/vmail:nocopy
```

**Comment by kylejw1** [comment]
I am also wondering if this is possible.  I am mounting a cifs share via docker-volume-netshare and having issues I believe would be solved by nocopy

**Comment by ahh-docker** [comment]
Hello! Thanks for filing an issue with the Docker documentation team. Unfortunately, it looks like your issue is more of a support issue than a documentation issue.

For the Docker Community Edition (CE), please visit https://forums.docker.com/, and post your issue there.

For Docker Enterprise Edition (EE) subscribers, please visit https://success.docker.com/support, and contact Docker Support directly.

If this is a documentation issue, please reopen the issue, along with more detailed comments on what needs a review and possible edit. Thanks!
