### ISSUE TITLE
"docker top" does not show zombie processes

### ISSUE THREAD

**Issue by CrimsonGlory** [docker/docker.github.io#5637]
File: [engine/reference/commandline/top.md](https://docs.docker.com/engine/reference/commandline/top/), CC @mistyhacks 
Currently the command "docker top CONTAINER" does not show zombie processes inside the container.
In order to find them I have to do "docker exec -ti CONTAINER ps aux"

In the documentation it says "docker container top CONTAINER [ps OPTIONS]"
so doing docker container top CONTAINER aux 
is different from
 docker exec -ti CONTAINER ps aux

**Comment by mistyhacks** [comment]
Yes, because you are using the `docker exec` command to run the `ps aux` command inside the container, instead of using the `docker top` command. They are very different.

If you want to see `docker top` extended to show zombie processes inside the container, please file an RFE in the https://github.com/docker/cli repository.
