### ISSUE TITLE
Unable to add swarm service in Docker 

### ISSUE THREAD

**Issue by rangarajancr** [docker/docker.github.io#5684]
Dear Team,

I am trying to add docker swarm service successfully added manager and worker in it.

once i ssh into that i am unable to add the worker or manager to it , i do get following error , please look into this and help me 

Boot2Docker version 17.12.0-ce, build HEAD : 378b049 - Wed Dec 27 23:39:20 UTC 2017
Docker version 17.12.0-ce, build c97c6d6
docker@worker2:~$ docker swarm join --token SWMTKN-1-3hdplcks4ydxkw7gyh0fc035x72j3e81ejaexukt1i5w8son25-5kca0qkgdf6ly2i74o577eabg 192.168.99.103:2376
Error response from daemon: rpc error: code = Internal desc = connection error: desc = "transport: remote error: tls: bad certificate"
docker@worker2:~$ docker swarm join --token SWMTKN-1-3hdplcks4ydxkw7gyh0fc035x72j3e81ejaexukt1i5w8son25-5kca0qkgdf6ly2i74o577eabg 192.168.99.103:2377
Error response from daemon: remote CA does not match fingerprint. Expected: 8bbcbfcbd3888526676eb5605902e9ac7ab43d8691cb5d025b1a43964f7386bd
docker@worker2:~$

**Comment by JimGalasyn** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution. If this really is a documentation issue and I have misunderstood, please reopen it with more information.
