### ISSUE TITLE
Feedback for: docker-for-windows/index.md

### ISSUE THREAD

**Issue by wysiharig** [docker/docker.github.io#570]
File: [docker-for-windows/index.md](https://docs.docker.com/docker-for-windows/)

hi,
i alwaya get this error
![docker_fail](https://cloud.githubusercontent.com/assets/23475281/20302416/79255d9e-ab27-11e6-8f29-a702396b0482.JPG)

**Comment by londoncalling** [comment]
@wysiharig Thank you for your feedback. However, it looks like your issue is not
about Docker documentation, but that you may be having trouble with
Docker itself. Please file a Docker support ticket or check out
https://forums.docker.com/ to see if you can find a solution.
 
If this really is a documentation issue and I have misunderstood,
please reopen it with more information
