### ISSUE TITLE
Display at the top of the API doc that all the calls are to be issued to https://hub.docker.com

### ISSUE THREAD

**Issue by odupuy** [docker/docker.github.io#5775]
File: [registry/spec/api.md](https://docs.docker.com/registry/spec/api/), CC @joaofnfernandes 

I had to google, find some source code as an example

**Comment by joaofnfernandes** [comment]
I think you're misunderstanding this documentation. Docker Registry is an open-source registry that you can deploy locally so that you can manage your images privately without having to push/pull from Docker Hub.

It so happens that Docker Hub uses Registry under the hood, but Docker Hub doesn't have a publicly supported API. this means that some endpoints might be similar between the two, but they might diverge.

Since there's nothing to update in the docs I'm going to close this issue, but feel free to comment.
