### ISSUE TITLE
Docker container ps vs docker container ls (and other mentions)

### ISSUE THREAD

**Issue by gjanders** [docker/docker.github.io#5850]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/), CC @johndmulhausen

Hi,

A minor issue but the summary and parts of the page mention:
docker container ls                                # List all running containers
docker container ls -a             # List all containers, even those not running
docker container stop <hash>           # Gracefully stop the specified container
docker container kill <hash>         # Force shutdown of the specified container
docker container rm <hash>        # Remove specified container from this machine
docker container rm $(docker container ls -a -q)         # Remove all containers

However the recording and what I believe are the newer/easier way to do these commands would be:
docker ps
docker ps -a
docker stop
docker ...

Happy to be corrected but the terminal recording appears to use the above where the documentation appears to use the "docker container..." form.

Thanks!

**Comment by joaofnfernandes** [comment]
@gjanders you got it backwards 😄
We started by shipping `docker ps, docker rm, ...` but as we introduced more concepts in Docker (like networks, volumes, secrets), it was no longer obvious for new users what were you doing with a `docker rm`.

As a new user you would have to learn that `docker rm` is implicitly `docker container rm`. But there were a few exceptions. An example is `docker inspect`, which you can use with a bunch of different objects.

For that reason, we've implemented `docker container <operation>`. It's consistent with how you manipulate the other objects available, and since it's more verbose it's easier for new users.

I think the getting started guides should be as much verbose as possible, to make it easier for new users. For that reason I'm closing this issue, but feel free to comment if you disagree.

**Comment by gjanders** [comment]
That's fine, it would be nice if the video and the documentation matched. Thanks!

**Comment by joaofnfernandes** [comment]
@gjanders I know, right? Consistency makes it some much easier to learn things.
