### ISSUE TITLE
invalid json at "Disable the default bridge network"

### ISSUE THREAD

**Issue by Chell256** [docker/docker.github.io#5902]
File: [engine/userguide/networking/index.md](https://docs.docker.com/engine/userguide/networking/), CC @johndmulhausen 
The json displayed  at "Disable the default bridge network" is not valid and would break the docker daemon. Changing it from
`"iptables": "false"` 
to 
`"iptables": false`
should fix this

**Comment by mistyhacks** [comment]
Hi @Chell256 and thanks for your report. Since you already figured out how to fix this example, it might be fun for you to contribute the fix yourself! If you go back to the page in question and click "Edit this page" on the right-hand side, the page will open in Github in the text editor, where you can make the change and submit it as a pull request. Thanks!

**Comment by mistyhacks** [comment]
Closed in #5936
