### ISSUE TITLE
Why docker installation can't be simpler

### ISSUE THREAD

**Issue by amineparis** [docker/docker.github.io#5909]
Why docker installation is not like any other package `sudo apt-get install docker` ? why we should run many commands that most of them fail most of the time and we spend hourse looking for workarounds !!!

**Comment by mistyhacks** [comment]
"most of them fail most of the time"? I'm not sure what you mean. If you are getting failures or the instructions are wrong, then please let us know the specifics.

It is a simple command `sudo apt-get install docker-ce`, but you have to set up Docker's repository for it first. Docker is distributed by Docker, Inc, and not by the various OS distribution vendors.

See https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce-1, after the repo is installed it's basically 2 steps (update the list of available packages from the repo, and install).

**Comment by amineparis** [comment]
`Failed to fetch https://download.docker.com/linux/ubuntu/dists/vivid/stable/binary-amd64/Packages  HttpError404`

**Comment by amineparis** [comment]
In my case It's risky to upgrade server now, Is their a way to install docker on vivid ?

**Comment by thaJeztah** [comment]
There are some very old packages of Docker at yum.dockerproject.org, but I would not recommend going that road; running on such an outdated system is highly insecure

**Comment by mistyhacks** [comment]
Since Ubuntu doesn't support Vivid either, it means you are running an old unpatched kernel, old software packages which may have vulnerabilities, etc. For instance, I don't think there would be fixes for recent problems like Spectre. I'd strongly encourage you to upgrade your OS, at least to a LTS version of Ubuntu. Closing this ticket now since you were trying to uninstall an unsupported config that we never claim works.
