### ISSUE TITLE
persistent secrets

### ISSUE THREAD

**Issue by MichaelKofler** [docker/docker.github.io#5961]
File: [engine/swarm/secrets.md](https://docs.docker.com/engine/swarm/secrets/), CC @johndmulhausen 

The documentation says: These files are never persisted in disk, but are managed in memory.

However, as far as I understand it, /run in a Docker container is persistent. I can 

docker exec -it <containername> /bin/sh
cat /run/secrets/whatever

even if I stop the container and start it again.

I guess I mis-understand this feature somehow?

**Comment by joaofnfernandes** [comment]
@MichaelKofler while the docs could be clearer on this, I don't see a clear action item here, so I'll close this issue.

I understand your source of confusion because you can exec into the container, see that the file exists, and inspect the content of the file containing the secret. Intuitively you'd guess that the secret file is persisted.
But let's poke around and see what we can find, assuming you're running Docker on Linux, Docker for Mac or Docker for Windows:

```
# create your secret
echo "super-hyper-secret" | docker secret create secret-message -

# create a service that uses the secret
docker service create \
  --secret secret-message --name nginx nginx

# Find the container ID for that service task and exec into it
docker exec -it <id> /bin/sh

# Now we're inside the container, so we can see the secret
cat /run/secrets/secret-message
super-hyper-secret

# Check what's mounted on the filesystem
mount | grep secret
tmpfs on /run/secrets/secret-message type tmpfs (ro,relatime)
```

This means that what you're seeing as a file from inside the container is actually a `tmpfs` volume that's being mounted into the container. Tmpfs is a filesystem that keep all files in memory and doesn't write them to disk.

The caveat is that this is only true for Linux-based containers. Windows doesn't have support for in-memory filesystems, so if you're running Windows containers the secret file is written to disk, so you should make sure the directory where secrets are stored is not accessible to other users.
[If you want to learn more](https://docs.docker.com/engine/swarm/secrets/#windows-support)
