### ISSUE TITLE
Missing Docker for AWS template versions in archive

### ISSUE THREAD

**Issue by charly-vega** [docker/docker.github.io#5964]
The **"Deploy Docker Community Edition (CE) for AWS (stable)"** URL at the "Release notes" page links to the 17.12 CE version of the AWS CloudFormation stack (https://docs.docker.com/docker-for-aws/release-notes/#1709-ce at the time of this issue)

Plus, the template archive should include all versions up until 17.09 CE; it now only lists versions 17.03 CE and 17.06 CE.

A complete template archive is really important so running stacks can be upgraded without skipping any versions.

File: [docker-for-aws/archive.md](https://docs.docker.com/docker-for-aws/archive/), CC @johndmulhausen

**Comment by gbarr01** [comment]
Hi, @charly-vega , we are in the process of updating the page: https://github.com/docker/docker.github.io/commit/5e380f624c0ff0d3c0f8affc3aa109cca0bd71eb

**Comment by gbarr01** [comment]
Please let us know if this doesn't resolve your concerns.

**Comment by vce-xx** [comment]
@gbarr01 The question was about Docker for AWS templates : [Docker for AWS template archive](https://docs.docker.com/docker-for-aws/archive/)
The link that you provided doesn't seem to address that.
For instance, because there are currently some issues with 17.12, we 'd like to find in the template archive the template for version 17.09.
