### ISSUE TITLE
repository name vs. image name

### ISSUE THREAD

**Issue by codelabor** [docker/docker.github.io#6002]
### Problem description

On docker cli, 'repository' means 'namespace/image name'.
<img width="698" alt="screen shot 2018-02-14 at 7 59 23 pm" src="https://user-images.githubusercontent.com/815767/36202013-6b687d8e-11c5-11e8-8ce4-37a9ad419bf8.png">

On docker hub, 'repository' means 'image'.
<img width="504" alt="screen shot 2018-02-14 at 8 20 43 pm" src="https://user-images.githubusercontent.com/815767/36202015-6dd45cbe-11c5-11e8-9533-8bc40db45161.png">

### Problem location

- I saw a problem on the following URL: https://hub.docker.com/add/repository/

### Project version(s) affected

N/A

### Suggestions for a fix

Could you change 'Create Repository' page label like this?:
Add a repository name (Required) (X)
Add a image name (Required) (O)

**Comment by gbarr01** [comment]
Hi, @codelabor ... Thanks for the submission. 

I don't see how repo on the cli means namespace/image.  You command asks docker to list all images in your repo named "kitematic" ... 

Also, the instructions on The Hub are to create a repo so that you can store images (that you create later) in it. As your own instructions indicate, there's no need to create an image ... in fact, it doesn't make sense here. With what would you create that image? You cannot simply create an image name as a placeholder for future building. 

I am going to close this issue, but we are always open to persuasion.
