### ISSUE TITLE
404 at /engine/reference/commandline/daemon/

### ISSUE THREAD

**Issue by alfredfrancis** [docker/docker.github.io#6025]
URL: /engine/reference/commandline/daemon/

**Comment by gbarr01** [comment]
Thanks, @alfredfrancis . Will fix. In the meantime: https://docs.docker.com/engine/reference/commandline/dockerd/

**Comment by joaofnfernandes** [comment]
@alfredfrancis I can't find any references to that url in the current docs.
How did you get to that url? Was it a page that linked to it, a bookmark you had, or something else?

We had an article with that url, but it got deleted more than a year now and all the references to it were fixed. So I'm betting you had a bookmark or something similar.

**Comment by gbarr01** [comment]
Hi, @alfredfrancis , like @joaofnfernandes , i see no references to this URL. Please update your bookmarks.

**Comment by thaJeztah** [comment]
This was the old location of that document, so we may want a redirect for it (very likely there's many references out there linking to that)

**Comment by gbarr01** [comment]
@thaJeztah , this is a generated cli doc ... can i fix this with _data/redirects.csv?

**Comment by thaJeztah** [comment]
@gbarr01 hmm, good point, I'm not sure how the redirects were added when the CLI docs were changed to be generated (instead of pulling the `.md` files from the docker/cli repository).

There may be redirects that we're missing in this repository, but that were added upstream, such as in this case:
https://github.com/docker/cli/blame/master/docs/reference/commandline/dockerd.md#L3

I see there are "stubs" for most of the CLI commands in this repository; https://github.com/docker/docker.github.io/tree/master/engine/reference/commandline, but there's no such file for `dockerd.md` (I suspect in that case, it will use a default stub? not sure how it works, will have to dig into that), so what I _think_ is needed is:

- check if there's other stubs missing in that directory
- check the https://github.com/docker/cli/tree/master/docs/reference/commandline directory, and search for all the "aliases" that are defined there in those markdownfiles
- update stubs in this repository with those redirects

We can probably remove the aliases upstream, if they're not used, and to prevent having to manage them in two locations.

Alternatively, we could have an option in the YAML generator that adds the aliases (not sure about that one)
