### ISSUE TITLE
Why curl?

### ISSUE THREAD

**Issue by Forage** [docker/docker.github.io#6047]
File: [install/linux/docker-ce/ubuntu.md](https://docs.docker.com/install/linux/docker-ce/ubuntu/), CC @johndmulhausen

Why insist on installing `curl` while it is only used to download the key and `wget`, which is present by default on Ubuntu, does the job just as well?

**Comment by joaofnfernandes** [comment]
That's a good question 😄
The reason to use `curl` is that it's kind of the de facto standard in many documentation sites, and we want to make it easy for everyone to focus in learning Docker without having to learn a ton of other things at the same time.

So we opt to consistently use `curl`, even if it's not installed by default in some distributions.

On the installation page it's possible that we install curl but don't use it that much, but there are a ton of other places in the docs that use curl. In those places we can assume that curl is already installed, instead of telling you each time that you should install it.

I don't think we should change the install page to use wget, so I'll close this issue, but feel free to comment.
