### ISSUE TITLE
404 at /registry/configuration/

### ISSUE THREAD

**Issue by smcquay** [docker/docker.github.io#6086]
URL: /registry/configuration/

I was trying to follow links here:

https://github.com/docker/docker.github.io/blob/master/registry/deploying.md
https://docker.github.io/registry/deploying/

And it has a dead link to configuration. Not sure where this info went to; still searching.

**Comment by smcquay** [comment]
It seems to have been removed in 554b2c99679cb2e1334313483943a0b8be9767d2

**Comment by smcquay** [comment]
It also seems as though the file referenced there is available [here](https://docs.docker.com/registry/configuration/); the difference is `docs.docker.com` vs `docker.github.io`.

**Comment by joaofnfernandes** [comment]
I think you found the answer by yourself. Basically, there's a couple of files that are not managed in this repository, and at build time we pull them from upstream.

What you see at https://docker.github.io/ is not the full docset, since it doesn't include those files that are managed upstream. Use https://docs.docker.com instead.

The article you're looking for is here https://docs.docker.com/registry/configuration/.

Having said that, I don't see any reason for us to continue making https://docker.github.io/ available.
I've filed #6101 so that we can follow-up on this.
