### ISSUE TITLE
Link 404s

### ISSUE THREAD

**Issue by kottofy** [docker/docker.github.io#6096]
File: [docker-hub/github.md](https://docs.docker.com/docker-hub/github/), CC @johndmulhausen 

"create an Automated Build"

**Comment by joaofnfernandes** [comment]
@kottofy I can't seem to find the link that's broken. I see a sentence with 

> You can [create an Automated Build](https://hub.docker.com/add/automated-build/github/)

But the url seems to work.

**Comment by gbarr01** [comment]
@kottofy , i think the problem is that the link you are referring to is an anchor: https://docs.docker.com/docker-hub/github/#creating-an-automated-build

... and clicking an anchor can take you slightly past the heading so you have scroll up a tad. 

Or are you saying that the anchor used to be: 

https://docs.docker.com/docker-hub/github/#create-an-automated-build

If so, please update your bookmarks as I see no references to it in the doc set.
