### ISSUE TITLE
Kali (Rolling) Linux Install Fix

### ISSUE THREAD

**Issue by spikel46** [docker/docker.github.io#6163]
File: [install/linux/docker-ce/debian.md](https://docs.docker.com/install/linux/docker-ce/debian/), CC @gbarr01 

In steps 3 and 4 of "*Set Up the Repository*", Kali Linux users will run into issues because of the auto-generated commands. I circumvented these by

Step 3:
Changing:
`$ curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | sudo apt-key add -` 

to

`$ curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -` 

And in Step 4 I used (as super user):
`echo "deb [arch=amd64] https://download.docker.com/linux/debian jessie stable" > /etc/apt/sources.list.d/docker.list `

Just FYI

**Comment by joaofnfernandes** [comment]
@thaJeztah I would consider Kali Linux to be a separate distro, so while it's compatible with Debian, I don't think we should bend the docs for Kali. What do you think?

**Comment by thaJeztah** [comment]
Yes, we should not modify the documentation for distros that we don't support (including Debian derivates, because we don't test on those).

_However_, I do agree that we don't need the `$(. /etc/os-release; echo "$ID")` part in the instructions to get the `"debian"` string. I checked the instructions for (e.g.) Ubuntu, and there we also use a hardcoded string, which makes it a bit more readable as well;

I suggest changing step 3 to;

```bash
$ curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
```

And the same change in step 4. (note that there are two separate variations; one for `amd64` and one for `s390x`);

```bash
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
```


We should _keep_ the `$(lsb_release -cs)` (that provides `wheezy` / `jessie` / `stretch`), because not all users may know the codename for the version of Debian they're using.


@spikel46 are you interested in contributing, and opening a pull-request to make those changes?

**Comment by DhiaEddineSaidi** [comment]
hello @spikel46 , is it safe to install it on Kali-rolling ($(lsb_release -cs) => produces kali-rolling ) ?
did you test it ?

**Comment by Hillsie** [comment]
Installation instructions on the Kali site => `https://www.kali.org/docs/containers/installing-docker-on-kali/`
