### ISSUE TITLE
To doc: Allow Dockerfile to be outside of build-context

### ISSUE THREAD

**Issue by gbarr01** [docker/docker.github.io#6199]
References:
https://github.com/docker/docker-ce/blob/v18.03.0-ce-rc3/CHANGELOG.md
https://github.com/docker/cli/pull/886

Possible doc location: 
https://docs.docker.com/engine/reference/builder/
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

**Comment by gbarr01** [comment]
@thaJeztah ... I'm finding text from last October that already says this: 

> The current working directory where you are located when you issue a docker build command is called the build context, and the Dockerfile must be somewhere within this build context. **By default, it is assumed to be in the current directory, but you can specify a different location by using the -f flag. Regardless of where the Dockerfile actually lives**, all of the recursive contents of files and directories in the current directory are sent to the Docker daemon as the build context.

The first sentence is contradictory but from "By default" on, it appears that this feature may have been documented. What am I missing here? What is new?

**Comment by thaJeztah** [comment]
I think the part that needs to be removed in that paragraph is "and the Dockerfile must be somewhere within this build context", otherwise that paragraph looks ok.

It was already possible to set the location of the Dockerfile using the `-f` flag, but previously that would fail if `-f` was not within the build-context, i.e., previously


This was allowed:

```
docker build -f /projects/my-project-files/subdir/Dockerfile /projects/my-project-files/
```

But this would fail (because `/projects/dockerfiles/` is not inside `/projects/my-project-files/`) :

```
docker build -f /projects/dockerfiles/Dockerfile /projects/my-project-files/
```

**Comment by gbarr01** [comment]
Got it. Thanks, @thaJeztah .
