### ISSUE TITLE
Interlock lb port is 8080

### ISSUE THREAD

**Issue by NicoTexas** [docker/docker.github.io#6240]
File: [ee/ucp/interlock/usage/ssl.md](https://docs.docker.com/ee/ucp/interlock/usage/ssl/), CC @johndmulhausen 

See https://beta.docs.docker.com/ee/ucp/interlock/usage/ssl/

Could you explain why in the configuration of the service
```
docker service create \
    --name demo \
    --network demo \
    --label com.docker.lb.hosts=demo.local \
    --label com.docker.lb.port=8080 \
    --label com.docker.lb.ssl_cert=demo.local.cert \
    --label com.docker.lb.ssl_key=demo.local.key \
    ehazlett/docker-demo
```
Why is the label com.docker.lb.port set to 8080 ?

**Comment by joaofnfernandes** [comment]
The `ehazlett/docker-demo` app listens on port 8080 for traffic, so what this snippet does is:

* Deploy the service, but there's no need to use `--pubish` because we don't want to expose that port to the outside world.
* Attach this service to the `demo` network. Interlock will reconfigure the Proxy service to also be attached to this network. This way the proxy and the service can communicate.
* The `com.docker.lb.hosts` tells Interlock to route traffic for the host `demo.local` to this service.
* The `com.docker.lb.port` tells Interlock to use port `8080` when routing to the service, since we know the service is listening on that port.
* The other labels tell the TLS certificate and key to use for the Interlock proxy service.

Now you might wonder, how do we know that the `ehazlett/docker-demo` app listens on port 8080?
The docs don't say it, but one way you can figure it out is by inspecting the image:

```
docker image inspect --format '{{ .ContainerConfig.ExposedPorts }}' ehazlett/docker-demo
```

---

@NicoTexas this functionality/docs are part of the UCP 3.0 beta, so the best place to get help and provide feedback is at https://forums.docker.com/c/docker-data-center/eebeta

I'm also working on improving these docs right now, but that is being tracked on an upstream repo. For that reason I'll be closing this issue.
