### ISSUE TITLE
Do not suggest `docker` group to beginners.

### ISSUE THREAD

**Issue by 0cjs** [docker/docker.github.io#6241]
The [get-started/index.md](https://docs.docker.com/get-started/) document suggests:

> To avoid permission errors (and the use of `sudo`), add your user to the `docker` group.

The security implications of this are not subtle (all users who can talk to the `docker` daemon [trivially have full root access](https://github.com/0cjs/sedoc/blob/master/app/docker-tips.md#leveraging-docker-for-root-access)), but they are all too easily and frequently ignored.

Rather than suggest to beginning users that they do something so insecure when there is a high likelyhood that they won't understand the full implications of this, we should instead simply suggest that they run `sudo docker`, thus leaving the system in a state where it's more clear that these users have root access (at least in default configurations of `sudo`).

Cc: @gbarr01

**Comment by gbarr01** [comment]
@thaJeztah , he seems to make a good point. Do you agree?

**Comment by thaJeztah** [comment]
Hm, there's definitely things to improve here; 

Yes; this note comes a bit "out of the blind"; the note starts with "to avoid permission errors" (why?) but the introduction so far does not mention that additional privileged may be needed. Note that this only targets users running Docker on Linux connecting to the Docker daemon using a socket; Docker for Mac, and (I think) Docker for Windows don't require additional permissions.

So that's the tricky bit; we can't use `sudo` in the examples, because on Mac this isn't needed, and on Docker for Windows, there's no `sudo` 😅 

Perhaps it's a bit out of scope this early in the getting started, but the _daemon_ always runs privileged, so even if the user doesn't need `sudo` (e.g. in situations where you don't connect using to `/var/run/docker.sock`), you'd still have `root` (or equivalent) permissions on the host where the daemon runs (which could be a VM).

The current text mentions adding the user to the `docker` group, perhaps we should change the note; remove that information, and use the title of the section we're linking to instead ("Manage Docker as a non-root user"). Possibly we should repeat the warning about root access;

<img width="944" alt="screen shot 2018-03-26 at 09 18 44" src="https://user-images.githubusercontent.com/1804568/37892046-c83da680-30d6-11e8-800f-3d59f270ffbe.png">

**Comment by gbarr01** [comment]
That makes sense. Thanks so much, @thaJeztah .

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
