### ISSUE TITLE
Include an explicit statement in the docs advising against moving /var/lib/docker to an NFS share

### ISSUE THREAD

**Issue by anweiss** [docker/docker.github.io#6267]
### Problem description

Per [this](https://github.com/moby/moby/issues/22539#issuecomment-217316284) comment in the upstream (CC @thaJeztah), we should have an explicit statement in the documentation that tells users not to move `/var/lib/docker` to an NFS share; more specifically, telling users not to set the Docker daemon `--data-root` flag to an NFS share.

### Problem location and fix suggestions

We should include a statement prohibiting this somewhere on the [About storage drivers](https://docs.docker.com/storage/storagedriver/) page along with an explanation as to why one shouldn't do so. We should also include a similar statement next to the `--data-root` daemon flag docs somewhere in [this](https://github.com/docker/cli/blob/master/docs/reference/commandline/dockerd.md#run-multiple-daemons) section.

**Comment by joaofnfernandes** [comment]
@anweiss it seems you have a lot of context on this. Can you elaborate or point to a discussion on why you should not use and NFS share for this?

**Comment by anweiss** [comment]
Deferring to @thaJeztah on ^

**Comment by thaJeztah** [comment]
Adding @cpuguy83 as well, as he may have more detailed information

There's a couple of issues with using NFS shares;

- nfs may not support all the things that the storage-drivers expect (causing odd failures)
- I _think_ some directories inside `/var/lib/docker` _could_ work (image store? volumes?), but:
- the `/var/lib/docker` directory, or any subdirectory in it, should be exclusive to a single daemon. If multiple daemons share that directory (which could be if multiple daemons use the same NFS share), [bad things can happen](http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/).

**Comment by cpuguy83** [comment]
As @thaJeztah said, the daemon assumes exclusive access to /var/lib/docker.
I doubt overlayfs or aufs would work on an nfs share (pretty sure neither do)... the other drivers of course wouldn't be on the share anyway since they require a local storage device.

**Comment by joaofnfernandes** [comment]
Got it! The message we should use for docs should center around `/var/lib/docker` needs to be dedicated to a single daemon.

I was trying to dig into this because we have similar issues when using Registry and DTR with NFS. I can't seem to find the issue where I was tracking that information, but in the case of those products the actual problem with NFS is that they require read-after-write consistency, so you need to make sure you configure your NFS share with that in mind.

While I understand why you would want to use Registry and DTR with NFS, I don't understand the use-case for trying to run an Engine with NFS. Are users trying to implement a high-availability strategy for Engine (non-swarm mode), so they look to NFS for that?

**Comment by anweiss** [comment]
I've gotten this ask from users that are getting started with Docker predominately due to a lack of their initial understanding of all of the different scenarios involving `/var/lib/docker` and local storage vs. Docker volumes and container storage mounts vs. DTR shared storage.
