### ISSUE TITLE
Target and published port terms mixed in `Bypass the routing mesh` section.

### ISSUE THREAD

**Issue by exordium-frozen** [docker/docker.github.io#6298]
File: [engine/swarm/ingress.md](https://docs.docker.com/engine/swarm/ingress/), CC @gbarr01 

Hi there,

Here is an ambiguity in the docs, section `Bypass the routing mesh`. Take a look at this:
```
If you expect to run multiple service tasks on each node (such as when you have 5 nodes but run 10 replicas), you cannot specify a static target port. Either allow Docker to assign a random high-numbered port (by leaving off the target), or ensure that only a single instance of the service runs on a given node, by using a global service rather than a replicated one, or by using placement constraints.
```

Here is mentioned `target` port. But, instead, should be `published`.  
Indeed, it is impossible to map single outside port to multiple inside ports.  

I spent several minutes trying to understand, but then made an experiment and ensured that there is a mistake in the docs.

**Comment by joaofnfernandes** [comment]
I see... This seems to refer to the verbose arguments used with `--publish`.

```
--publish published=8080,target=80,mode=host
```

These docs might help you [understand better the port options](https://docs.docker.com/engine/reference/commandline/service_create/#publish-service-ports-externally-to-the-swarm--p---publish).

I'm going to close this issue, because I believe that the sentence will make more sense once you read the docs I've pointed out. If you think we can improve that section to be clearer, feel free to open another issue or better yet, help us fix!

<img width="1280" alt="1" src="https://user-images.githubusercontent.com/1525937/37931262-ebc9e514-30f9-11e8-86f7-baa34b87c9ca.png">
