### ISSUE TITLE
Incorrect content

### ISSUE THREAD

**Issue by Zhoubaochen** [docker/docker.github.io#6356]
File: [network/network-tutorial-overlay.md](https://docs.docker.com/network/network-tutorial-overlay/), CC @gbarr01 
Communicate between a container and a swarm service，this section does not seem to match the title

**Comment by joaofnfernandes** [comment]
As far as I can tell the section is correct. The problem seems to be that that when you click the link, the site ends up scrolling a bit more than what you expect it to. That problem is being tracked at #2199, so I'll close this one as a duplicate.

![1](https://user-images.githubusercontent.com/1525937/38206539-a3a21886-365f-11e8-82df-decbd3c925f5.gif)

**Comment by gulerayhan** [comment]
that section explains the communication between 2 containers in default bridge network, not "Communicate between a container and a swarm service". So its not correct and needs to be fixed.
