### ISSUE TITLE
Describe OS pre-requisites for EE Engine Installs 

### ISSUE THREAD

**Issue by yongshin** [docker/docker.github.io#6369]
File: [install/linux/docker-ee/centos.md](https://docs.docker.com/install/linux/docker-ee/centos/), CC @gbarr01 

It seems that the pre-reqs for engine only installs are missing. Perhaps something similar to what is described here for Host Platforms is what we need: https://success.docker.com/article/compatibility-matrix 

There isn't an easy way to find out the pre-reqs for Ubuntu, CentOS, RHEL etc if you were to think about installing the EE engine.

**Comment by joaofnfernandes** [comment]
Independently on who ends up working on this, keep in mind that we should have a single source of truth for system requirements, and right now that is the [compatibility matrix](https://success.docker.com/article/compatibility-matrix).

Instead of replicating that info in the docs, the docs should link to that matrix.

**Comment by gbarr01** [comment]
I believe I address this issue in PR https://github.com/docker/docker.github.io/pull/6363

**Comment by yongshin** [comment]
@joaofnfernandes It does not, since it still does not talk about what OS versions are compatible to our EE engine

**Comment by gbarr01** [comment]
Fixed by https://github.com/docker/docker.github.io/pull/6363
