### ISSUE TITLE
Feedback for: compose/swarm.md

### ISSUE THREAD

**Issue by yashgt** [docker/docker.github.io#638]
File: [compose/swarm.md](https://docs.docker.com/compose/swarm/)

The pages says that compose and swarm work together and that running docker-compose up will cause a multi-host deployment. When I tried it I got:

[admin@gol05854 compose]$ docker-compose up -d
WARNING: Some networks were defined but are not used by any service: mynet
WARNING: The Docker Engine you're using is running in swarm mode.

**Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.**

To deploy your application across the swarm, use the bundle feature of the Docker experimental build.

More info:
https://docs.docker.com/compose/bundles

**Comment by londoncalling** [comment]
@yashgt sorry for the delay on this and thanks for the feedback. 

A few things are in play here, and have evolved more since you raised this issue.

The https://docs.docker.com/compose/swarm/ page you are referring to should be marked at the top with a "Legacy" banner, because starting with Docker 1.12 (a few releases ago) "standalone Swarm" was superseded by [Swarm mode](https://docs.docker.com/engine/swarm/).  We will eventually sunset these topics.

The example may work if you walk through all the link paths off to the other topics but that's a complicated workflow, and the better command to use for Swarm mode is `docker stack deploy` with a `docker-stack.yml` file.

The best way to proceed and learn about Swarm mode, `docker stack deploy` and docker-stack.yml` is to start with the pages referenced in that banner:

- [Swarm mode overview](https://docs.docker.com/engine/swarm/)
- [Getting started with Swarm mode](https://docs.docker.com/engine/swarm/swarm-tutorial/)
- [Learn Docker sample app](https://docs.docker.com/engine/getstarted-voting-app/)

I'm going to close this issue for now, and we'll raise the priority to remove those legacy topics from the current documentation as soon as it's possible. Sorry for the confusion, please send more feedback or questions as needed.
