### ISSUE TITLE
Feedback for: engine/admin/index.md

### ISSUE THREAD

**Issue by akunaatrium** [docker/docker.github.io#639]
File: [engine/admin/index.md](https://docs.docker.com/engine/admin/)

Should contain information also for Ubuntu 16.04 because configuring the daemon is different there.

**Comment by mstanleyjones** [comment]
It's actually not useful for the distribution-specific info to be in this file, because it is also in https://docs.docker.com/engine/installation/linux/ubuntulinux/. I'll pull it out of here and redirect you to the right parts of the other file. For now, please have a look at https://docs.docker.com/engine/installation/linux/ubuntulinux/#/configure-docker-to-start-on-boot, which shows you the recommended way to configure Docker, which is not dependent on which distribution you use or which init script manager you use. This is very new, as PR #640 was only merged today.

**Comment by mstanleyjones** [comment]
This has been addressed in the topic https://docs.docker.com/engine/installation/linux/linux-postinstall/
