### ISSUE TITLE
depends_on

### ISSUE THREAD

**Issue by HaakonHobaekConceptos** [docker/docker.github.io#6413]
File: [compose/reference/run.md](https://docs.docker.com/compose/reference/run/), CC @gbarr01

Doesn't depends_on also affect  "run", and not only "up"?

**Comment by joaofnfernandes** [comment]
🤔`docker compose run <service>` allows you to run a single service defined in your compose file. Since you're deploying a single service `depends_on` has no effect.

Am I missing something @shin- ?

**Comment by shin-** [comment]
By default, a service's dependencies will be started when executing a `run` command.

The current docs only mentions links (because it was written a while ago), but they work identically to `depends_on` as far as dependency resolution is concerned.

Ideally, we would replace the (deprecated) links mentions with `depends_on` language, and add a footnote indicating links work the same way.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
