### ISSUE TITLE
Update to "Plan the Upgrade"

### ISSUE THREAD

**Issue by hannah-docker** [docker/docker.github.io#6464]
File: [ee/ucp/admin/install/upgrade.md](https://docs.docker.com/ee/ucp/admin/install/upgrade/), CC @gbarr01

```
In particular, manager nodes must have at least 4GB of memory.
```

Should be:
```
In particular, manager nodes must have at least 8GB of memory. 
```

**Comment by gbarr01** [comment]
cc: @JimGalasyn

**Comment by joaofnfernandes** [comment]
@hannah-docker The docs mention 4 GB because that is what UCP is enforcing with 3.0.0.

```
MinMemoryGB = float64(4.0)
MinStorageGB = float64(3.0)
```

So I think there's a couple of things we need to do here:
- [ ] Sync with QA team to see if we have tested running clusters with the minimum requirements documented
- [ ] Discuss with PM team if we should bump the UCP validations in the product itself
- [ ] Clean the docs so that pages talking about minimum requirements link to the requirements page, so that we can keep the information centralized and up to date.

**Comment by hannah-docker** [comment]
@joaofnfernandes Thank you for the clarification.

In the third point are you talking about modifying this page? https://docs.docker.com/ee/ucp/admin/install/system-requirements/

```
Minimum requirements
8GB of RAM for manager nodes or nodes running DTR
4GB of RAM for worker nodes
3GB of free disk space
```

**Comment by joaofnfernandes** [comment]
Yes. Basically the install, upgrade, and release notes, should all tell you to check the system requirements before installing/upgrading.
Those articles should not go into detail about what the new requirements are and instead should link to the system requirements article you pointed out.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
