### ISSUE TITLE
Tutorial Redis volume doesn't work on Windows

### ISSUE THREAD

**Issue by starrychloe** [docker/docker.github.io#6574]
File: [get-started/part5.md](https://docs.docker.com/get-started/part5/), CC @gbarr01
https://docs.docker.com/get-started/part5/#persist-the-data

This doesn't work on Windows

```
    volumes:
      - "/home/docker/data:/data"
```

I tried that and several variations.

```
C:\Temp\docker-tutorial>docker service ps getstartedlab_redis
ID                  NAME                        IMAGE               NODE                DESIRED STATE       CURRENT STATE             ERROR                              PORTS
w5rcysu1jqkg        getstartedlab_redis.1       redis:latest        default             Ready               Rejected 4 seconds ago    "invalid bind mount source, mu"
zjvfn6wvty8b         \_ getstartedlab_redis.1   redis:latest        default             Shutdown            Rejected 9 seconds ago    "invalid bind mount source, mu"
zra00klx2723         \_ getstartedlab_redis.1   redis:latest        default             Shutdown            Rejected 15 minutes ago   "invalid mount target, must be"
zn0deh9g3q7n         \_ getstartedlab_redis.1   redis:latest        default             Shutdown            Rejected 21 minutes ago   "invalid mount config for type"
zu99op04xu6a         \_ getstartedlab_redis.1   redis:latest        default             Shutdown            Rejected 28 minutes ago   "invalid mount config for type"
```

Windows 8.1, Docker version 18.03.0-ce, build 0520e24302, Docker Toolkit

**Comment by gbarr01** [comment]
@starrychloe , can you provide more information? 

- Windows version (min must be Windows 10): 
- Docker version: 
- Are you using Linux or Windows containers?
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

**Comment by starrychloe** [comment]
That's good info. I edited the issue. I didn't see any options for choosing Linux or Windows. Whatever's the default after you install it. I'm pretty sure it's Linux.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by hunglxtp** [comment]
This bug is always present with me, i'm with windows 10 Pro, docker version 19.03.2

uxajgssst77d        getstartedlab_redis.1            redis:latest                      myvm1               Ready               Rejected less than a second ago   "invalid bind mount source, mu…"
ngxslx9f1chv         \_ getstartedlab_redis.1        redis:latest                      myvm1               Shutdown            Rejected 5 seconds ago            "invalid bind mount source, mu…"
unq04i96qd3i         \_ getstartedlab_redis.1        redis:latest                      myvm1               Shutdown            Rejected 10 seconds ago           "invalid bind mount source, mu…"
03rmpb3b3vrz         \_ getstartedlab_redis.1        redis:latest                      myvm1               Shutdown            Rejected 15 seconds ago           "invalid bind mount source, mu…"
6qbvldmlkwwz         \_ getstartedlab_redis.1        redis:latest                      myvm1               Shutdown            Rejected 20 seconds ago           "invalid bind mount source, mu…"
