### ISSUE TITLE
Create versioned links at each release, not after

### ISSUE THREAD

**Issue by akimd** [docker/docker.github.io#6589]
### Problem description

As of today there is:
- https://docs.docker.com/docker-for-mac which is about 18.03
- https://docs.docker.com/v17.12/docker-for-mac/ which is about 17.12

but there is no https://docs.docker.com/v18.03/docker-for-mac/.  I would need to have a permanent link to use.

**Comment by joaofnfernandes** [comment]
We used that strategy for UCP and DTR, but without extra work that strategy doesn't work well for search engine optimization.

If you have a url structure like:
* `/docker-for-mac` which always represents the latest, people writing content outside our control (blog posts, articles, other docs) will probably link to that page. Over time that page has a ton on inbound links, which signals to search engines that the page is valuable.
* `/docker-for-mac/version` or /version/docker-for-mac`. As soon as you release a new version, people writing content will link to that version. But then you will release a new version and people will link to that version. You don't have a way to accumulate a lot of inbound links into a single url, because you are diluting all possible inbound links across all versions. Since the number of inbound links is lower for each page, that signals to search engines that the page is not that valuable.

The perfect strategy for this would be two-fold:
* Have both `/version` and `/latest`, so that you could
  * Pin a link to a specific release. This is a requirement if you want to link from the product to the docs
  * When navigating on the website users should always see `/latest` first. This makes sure that  most people creating content link to the same url and don't dilute inbound links across a ton of different urls
* Add `<link rel="canonical>` to the versioned pages and make them point to the `/latest` version of that page. This signals to crawlers that even though the url might be different, they should consider all the versioned pages to be the same one and centralize the way inbound links are counted into a single url.

Unfortunately I don't think we have the resources to implement this strategy, so I would prefer we kept with the strategy we've been using with engine (only create the versioned url for previous releases)

**Comment by akimd** [comment]
This was a very clear and important piece of information.  Maybe it should be written down somewhere?  Then close this Issue whenever you want.

**Comment by joaofnfernandes** [comment]
Let's close this issue then. I was tracking something similar on a private repo, so it's good that we're having this discussion in this public repo, so that others can find this information later on.
