### ISSUE TITLE
Feedback for: machine/install-machine.md

### ISSUE THREAD

**Issue by Vivek788** [docker/docker.github.io#661]
File: [machine/install-machine.md](https://docs.docker.com/machine/install-machine/)

The instructions for installing docker-machine directly doesn't work on Ubuntu. We had to follow this solution in stackoverflow to get it working.

http://stackoverflow.com/questions/37870663/docker-machine-direct-install-on-ubuntu-with-curl-getting-permission-denied-with

**Comment by londoncalling** [comment]
@Vivek788 thanks, I'll make these updates to the docs

**Comment by londoncalling** [comment]
@Vivek788 I've updated the docs instructions for Linux install of Docker Machine per PR #1043 .You might have encountered problems previously because of the way the install commands were displaying in our docs. 

Commands shown in the docs should now match those on the Machine releases download page, and work properly when you cut-and-paste. I tested on both Mac and Linux with these results:

```
root@ubuntu-oceanbox:~# curl -L https://github.com/docker/machine/releases/download/v0.9.0-rc2/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine &&
>   chmod +x /tmp/docker-machine &&
>   sudo cp /tmp/docker-machine /usr/local/bin/docker-machine
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   600    0   600    0     0   1164      0 --:--:-- --:--:-- --:--:--  1162
100 24.1M  100 24.1M    0     0  5060k      0  0:00:04  0:00:04 --:--:-- 7374k
root@ubuntu-oceanbox:~# docker-machine version
docker-machine version 0.9.0-rc2, build 7b19591
```

I'll close this issue as soon as the docs update is published, but feel free to re-open it if you run into more problems. (fyi, I also tested the alternate commands you referenced on Stack Overflow, which worked but I had to modify them slightly to get them to work. The commands shown on our docs and releases page worked as expected.) 

Thanks for the feedback!
