### ISSUE TITLE
Unclear when it is planned to include Kubernetes in Docker for Mac stable

### ISSUE THREAD

**Issue by kachkaev** [docker/docker.github.io#6618]
File: [docker-for-mac/kubernetes.md](https://docs.docker.com/docker-for-mac/kubernetes/), CC @gbarr01 

> Kubernetes is only available in Docker for Mac 17.12 CE Edge and higher, on the Edge channel. Kubernetes support is not included in Docker for Mac Stable releases.

It'd be great to know about the plans to include Kubernetes into a stable channel of Docker for Mac. It is currently unclear whether this is ever going to happen. Seeing a time estimate (even a rough one) would be great too.

**Comment by joaofnfernandes** [comment]
Unfortunately we don't have a public roadmap for this, that's why you can't find anything about it in the docs.
The main driver of this is to make sure that whatever functionality lands on stable releases, has been extensively tested and makes sense for everyone.

I'm closing this issue because there's nothing we can improve in the docs, but feel free to comment.

**Comment by joaofnfernandes** [comment]
Agree, and I think that information already exists. The time of the releases is documented here - https://docs.docker.com/install/#time-based-release-schedule

> * Docker CE Edge releases generally happen monthly.
>* Docker CE Stable releases generally happen quarterly, with patch releases as needed.

Knowing that the latest stable CE version is 18.03, you can infer that the next one is probably going to be 18.06 (released in June).

But as you pointed out, it doesn't mean support for Kubernetes will be made stable by them.
