### ISSUE TITLE
Missing documentation in compose file reference. 

### ISSUE THREAD

**Issue by deepio** [docker/docker.github.io#6643]
### Problem description

I can not find any documentation pertaining to these specific items.

- Where is this in the documentation? `&`
```
services:
  django: &django
```

- This `<<` and this `*`
```
  celeryworker:
    <<: *django
```
The yaml compose file has version 2 as the reference version, I've looked through the reference pages for docker-compose 2 and 1. If I had to guess, it must copy similar settings from one service into others? 

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: 
https://docs.docker.com/compose/compose-file/compose-file-v1/
https://docs.docker.com/compose/compose-file/compose-file-v2/

**Comment by joaofnfernandes** [comment]
Did you find those two snippets in the Docker docs, or somewhere else?
I can't seem to find anything like that in the docs.

**Comment by deepio** [comment]
@joaofnfernandes Thank you for your reply. These are specific to yaml files in general, not docker. However, they work well in docker when trying to minimize code duplication. I would have liked to see documentation in docker, but I can understand if you(+docker community) choose not to include it.

**Comment by joaofnfernandes** [comment]
Oh, I see. Keep in mind that yaml is just a way to serialize data. That means that it's up to applications to define how the data should be structured, and in turn how to handle deserialization and validation of the yaml.

With Docker, that means that it's up to `docker-compose` and `docker stack deploy` to do that work, and I'm not sure if the deserialization libraries they use support yaml aliases.

Even if they support it, I don't think your compose files are going to be that big that you would benefit a lot from refactoring common structures into an alias.

I'm going to close this issue since this is more generic than just Docker, but feel free to comment if you find out a way to make this work.
