### ISSUE TITLE
Instructions for installing kubectl aren't specifying the same version EE uses

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#6746]
File: [ee/ucp/user-access/kubectl.md](https://docs.docker.com/ee/ucp/user-access/kubectl/)

The instructions for installing `kubectl` aren't specifying the same version EE uses; it is using the latest.  It would make sense to install the same version of kubectl as EE.

**Comment by millerdz** [comment]
☝️ Also, note that when you follow the install instructions and get latest kubectl, you'll end up with this error message for your `kubectl get pods -n kube-system`:

```No resources found.
Error from server (NotAcceptable): unknown (get pods)
```

**Workaround**:
If you specifically install kubectl v1.10.3 (the client version included with Docker 4 Mac Edge release), then the above commands work as expected. Instead of using this url `https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl`, you would use this URL: `https://storage.googleapis.com/kubernetes-release/release/v1.10.3/bin/linux/amd64/kubectl`.

**Recommendation:**

Change:

From:
`https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl`

To:
*NOTE:* The version listed below of `v1.9.1` is because that's the newest version that is +1 MINOR version away per Kubernetes `Note that kubectl only guarantees compatibility with clusters that are +/-1 minor version away.` [More Kubernetes version compatibility details.](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew) 
`https://storage.googleapis.com/kubernetes-release/release/v1.9.1/bin/linux/amd64/kubectl`

**Comment by joeabbey** [comment]
FYI, DCI is currently installing the `kubectl` that matches the kubernetes installed in UCP Major.Minor 

https://github.com/docker/certified-infrastructure/blob/develop/automation/ansible/roles/kubectl/defaults/main.yml

(If we do start shipping incremental updates, we can easily add that granularity)

**Comment by gitamiller** [comment]
Really like Olly's install process in his pull request #7134
