### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by zedwick** [docker/docker.github.io#6772]
At the bottom of https://docs.docker.com/install/linux/docker-ce/debian/ under "Next steps" there is a link to the "user guide" which leads to this page: https://docs.docker.com/engine/userguide/index.md which apparently does not exist.

**Comment by zedwick** [comment]
Seems this only occurs if javascript is disabled. With javascript enabled, the link instead leads to https://docs.docker.com/engine/userguide/ which does exist. So this issue seems to actually be that simple links do not work without javascript. The link above in Next Steps is also broken in the same manner without javascript enabled.

**Comment by moreal** [comment]
In my thought, I don't think it is not correct that the script of page makes me to redirect from /engine/userguide/ to /config/daemon/

Because we just installed a docker in our computer. How about redirecting to /get-started, not /config/daemon?

I want to send PR about this issue, but I don't know the branch i can push.
Can someone help me about that?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
