### ISSUE TITLE
API operations missing ?

### ISSUE THREAD

**Issue by CharanBR** [docker/docker.github.io#6829]
File: [ee/ucp/authorization/define-roles.md](https://docs.docker.com/ee/ucp/authorization/define-roles/)

This doc doesn't talk about how to use the APIs. Can this be updated ?

**Comment by joaofnfernandes** [comment]
You can check the [API docs here](https://docs.docker.com/reference/ucp/3.0/api/).  While I think that we need to have some examples on how to use the API, I don't think we should update that particular article to talk about the API.

The goal of that article is to explain the concepts (subjects, roles, grants) so that anyone (using either the web UI or API) can understand the basic primitives provided by UCP.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
