### ISSUE TITLE
Not enough docs for println format

### ISSUE THREAD

**Issue by pavelsr** [docker/docker.github.io#6855]
File: [config/formatting.md](https://docs.docker.com/config/formatting/)

if just printing result of `inspect` `.Source` and `Destination` paths are in same row

```bash
# docker inspect -f '{{ range .Mounts }}{{println .Source .Destination}}{{ end }}' osticket
/home/admin/osticket/i18n /data/upload/include/i18n
/var/lib/docker/volumes/9f059da2de175102ab9a9e6ccfffea6a5fad0492911dee075dcfd4d0b8f8563f/_data /data/upload/include/plugins
/var/lib/docker/volumes/736ed98bce6fc17487c48a81926c2968e3463135783670626d27a09104590b3b/_data /var/log/nginx
```

So 3 rows total

But if I catch output into array, I got 6 elements:

```bash
my_array=( $(docker inspect -f '{{ range .Mounts }}{{println .Source .Destination}}{{ end }}' osticket) )
echo ${my_array[0]} # /home/admin/osticket/i18n
echo ${my_array[1]} # /data/upload/include/i18n
echo ${my_array[2]} # /var/lib/docker/volumes/9f059da2de175102ab9a9e6ccfffea6a5fad0492911dee075dcfd4d0b8f8563f/_data
...
``` 

So `.Source` would be 0 and even elements, and `.Destination` would be odd 

Why there is such difference in behaviour?

**Comment by joaofnfernandes** [comment]
Notice that your first command returns `.Source` and `.Destination` separated by space.
On the second command, you create an array, but Bash uses spaces as delimiters to decide what is one array element. That's why `.Source` ends up being even elements on the array, and `.Destination` odd elements.

I don't think there's anything here specific to Docker, so I'm going to close this issue, but feel free to comment.
