### ISSUE TITLE
Document locking and unlocking of swarm managers

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker.github.io#689]
### Problem description

The raft logs are always encrypted on disk, and the encryption key is written to disk sometimes encrypted (it's encrypted if autolock managers is enabled)

But if your managers are not auto-locked, the key that encrypts the raft data is written basically in plain text in the TLS key's headers.  If it's auto-locked, the key that encrypts the raft data gets rotated, and is stored encrypted in the TLS key's headers.

if managers are auto-locked, they can't be restarted automatically after a reboot, for instance - someone has to go in manually to unlock each individual manager).  But if managers aren't auto-locked, security-wise, the raft data may as well not be encrypted, since the encryption key is stored right there.

we encrypt, and write the key to disk, because it's easier to just rotate the encryption key rather than have to forcibly delete all the unencrypted raft data

### Project version(s) affected

Engine 1.13

### Related PRs

- #568 
- https://github.com/docker/swarmkit/pull/1598
- https://github.com/docker/docker/pull/27967

cc/ @diogomonica @cyli

**Comment by mstanleyjones** [comment]
Issue to track docs for lock / unlock of swarm managers: #689 (PR coming later today)

**Comment by diogomonica** [comment]
- As of 1.13 all raft data is stored encrypted at rest in all the managers by default
- By default we generate a key for you and store it also on disk, so that managers can restart without operator intervention
- However, if a disk gets stolen, or you accidentally backup both the data and the key, you will be effectively leaking all of the cluster data, which starting with 1.13 might include secrets
- Because of this, we allow you to take ownership of this key, and you are able to enable `autolock`, which effectively means that the key used for encryption of your data never gets persisted to disk.
- Taking ownerhip of the key also means that a manager can no longer restart without human intervention, since providing the key is now of the responsibility of the operator (or external application).
- At any point in time you may rotate the key that is used to unlock the cluster, or give the responsibility of managing the key back to the managers, so that they can go back to restarting without external intervention.

**Comment by mstanleyjones** [comment]
Closed via #694
