### ISSUE TITLE
Complaint: Not a true CLI reference

### ISSUE THREAD

**Issue by SetTrend** [docker/docker.github.io#6923]
This is a comment about [Reference documentation on "Use the Docker command line"](https://docs.docker.com/engine/reference/commandline/cli/)

It reads: "To list available commands, either run `docker` with no parameters or execute `docker help`:"

Huh?

Frankly, from a "reference documentation" I'd expect it to explain every single command and every single option for that command thoroughly in a printable format for being printed and put next to the reader's machine, But it wouldn't expect it to _refer_ to the - hard to read - CLI itself.

I feel the term "reference" has been interpreted wrong here.

**Comment by joaofnfernandes** [comment]
That particular page covers a couple of generic things that right now don't make sense anywhere else, like configuring the CLI client.
But on the left navigation you can check the reference documentation for every command. Here's an example for `docker build`

![screen shot 2018-06-22 at 10 44 49](https://user-images.githubusercontent.com/1525937/41791027-54248228-7609-11e8-94fb-b288550a92e6.png)

That page lists all the supported flags, and provides extensive examples on how to use them.

I don't think this issue is actionable, and for that reason, I'm closing it. Feel free to comment if you disagree.

**Comment by SetTrend** [comment]
Thank you for clarifying and your good explanation, @joaofnfernandes .

I missed the navigation menu on the left because the stylesheet of the Docker documentation project erroneously decided that my browser window is too small to display the menu, and there seems to be no hint pointing to the fact that a navigation menu exists:

![docker css layout](https://user-images.githubusercontent.com/9283914/41906605-8f138af4-793e-11e8-9576-b0bae1a25432.png)

Despite the fact that the documentation lacks a hint to the navigation menu in this layout, my browser window is actually large enough (displayed on a 17" screen):

![sampleimage2](https://user-images.githubusercontent.com/9283914/41906715-dda4363c-793e-11e8-89f7-46dbd0b65d67.png)

Let me propose to redo the media queries in your project for it to utilize absolute lengths in media queries instead of pixels. (➡️ See [Using Lengths in CSS Media Queries](/SetTrend/CSS3---absolute-media-queries).)
