### ISSUE TITLE
Reference to installing docker-compose is not required

### ISSUE THREAD

**Issue by shashyajoshi** [docker/docker.github.io#6935]
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/)

The prerequisites section mentions that the user needs to install docker-compose, but that is not used anywhere in part 3.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by terryburton** [comment]
I think this is still relevant (despite its age), but do not know whether the "refactor" addresses this point specifically.

Docker Compose is not strictly required to follow the guide because other elements of the stack process the docker-compose.yml files. There's a risk that readers might be misled into believe that this is a necessary installation requirement to access swarm and stack functionality.

Docker Compose might be useful for bloat-free testing and development of docker-compose.yml files, but the guide gives no example of its use for such purposes - so perhaps it's best avoided altogether.

**Comment by craig-osterhout** [comment]
This issue seems no longer applicable to the current docs. As far as I can tell, Docker Compose is no longer listed prereq in the getting started unless the user chooses to complete the Docker Compose section. If you feel this issue is still applicable, please let us know.
