### ISSUE TITLE
Digital Ocean within Cloud Providers not present

### ISSUE THREAD

**Issue by joshualamorie** [docker/docker.github.io#7031]
File: [docker-cloud/infrastructure/link-do.md](https://docs.docker.com/docker-cloud/infrastructure/link-do/)

When I look at the Cloud Settings, there isn't anything labelled 'Cloud Providers', only 'Service Providers'.  Within this I only see 'AWS' and 'Azure'.  There isn't anything for Digital Ocean.

Is this because I have an individual account?

Has the system changed, but the documentation has not?

Has this feature been removed?

Thanks

**Comment by thomas-hervey** [comment]
I too am wondering if this is an issue because of individual accounts. I am following [a tutorial](https://docs.docker.com/docker-cloud/cloud-swarm/link-aws-swarm/) to link docker cloud to AWS, but under my settings I don't even have a service providers section. My settings skip from general to source providers (even though there is a Service Providers nav bar option)
![settings](https://i.imgur.com/gZQKkqZl.png)

**Comment by L-Hudson** [comment]
https://vimeo.com/15351476
