### ISSUE TITLE
Docker Slack Workspace Access?

### ISSUE THREAD

**Issue by salderma** [docker/docker.github.io#7112]
File: [registry/help.md](https://docs.docker.com/registry/help/)

Perhaps this is by design, but you advertise a link for dockercommunity.slack.com, but there seems to be no way to gain access to chat for help.

**Comment by salderma** [comment]
It appears this is noted in another issue #6198, however still not resolved completely.

**Comment by L-Hudson** [comment]
From bryceryan: @laureen there’s an older blog post about the purpose of the community slack and how to get invited. it would not be obvious from the docs or from the landing page on dockercommunity.slack.com how to do that, though. blog post: https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/ since that was posted by the community team, it might be useful to check in with them at some point.

**Comment by bermudezmt** [comment]
Sorry for the delay, @salderma . We've updated the link - hopefully this will get you what you need. Thank you for contacting us! The change will be reflected in https://github.com/docker/docker.github.io/pull/8279
