### ISSUE TITLE
Download Docker CE without logging in

### ISSUE THREAD

**Issue by witekdev** [docker/docker.github.io#7179]
Please reconsider your stance on this issue: https://github.com/docker/docker.github.io/issues/6910

Problem description

Docker for Mac and Docker for Windows cannot be downloaded without logging into Docker Store.
This is especially painful when you forget your docker store password and the reset link takes forever to arrive in your inbox.

Problem location

On the following URL: Install Docker for Mac and Install Docker for Windows

Suggestions for a fix

Do not require a login to docker store to download the CE editions.

**Comment by witekdev** [comment]
7 hours later, my docker store password reset email has still not arrived. I tried twice. Boosting the motivation for this issue to be seriously considered. Thank you.

**Comment by sirkubax** [comment]
@joaofnfernandes via https://github.com/docker/docker.github.io/issues/6910#issuecomment-398819417

> improve the Docker for Mac and Windows experience for users moving forward.

Could you name directly (as a bullet points) how would the user benefit? For sure that was not an empty words, you had to have something in mind to make this move and this statement.

I'd say that the only experience user (who pops in to get the file and forget about your website) would have is a frustration, but I may be wrong.

----
I'm against the fake limitations to the public projects, but if you really have a true explanation, I'd accept that.
Your move.

**Comment by turbo** [comment]
This also specifically impacts **users**. I.e. people who heard of Docker or otherwise need to run software packaged as Docker stacks/images. They don't develop, they use. Now, in addition to getting them to trust "this Docker thing", they've got to register a new account at a third party, agreeing to ToS et al, which have nothing to do with the product they're trying to get running.

We were talking about delivering our (Windows) enterprise on-premises app (1.5k customers, 200k+ daily users) as a Docker virtual appliance, but I will put that project on hold. Because I fear that the insultingly evasive and objectively false responses by Docker to the original issue are just the beginning. The days Docker existed in a vaccum are long gone, and there are a handful of viable alternatives.

But please do prove me and others wrong. Reverse this "feature", post a short mea culpa, and restore a bit of trust in [your target market&trade;](https://www.defmacro.org/2017/01/18/why-rethinkdb-failed.html).

**Comment by Chuckv** [comment]
My concern would be that user protests of this action could be considerably costly to the project.

For example, what if everyone with a docker store login were to start sending in 'stop processing' requests under GDPR..  Even if they are not EU citizens.  Firstly just dealing with that volume of mail is going to be a burden.. then you either need multiple policies (expensive) based on where people are citizens, or you save costs there and apply GDPR rights to all your users.  Either way there's going to be a bunch of back and forth to establish someone's identity and if they are allowed to make requests of you via GDPR.. That's a lot of work. 

Then to compound that, Nobody really knows how to handle the stop-processing request, how do you retain the data but ensure it is not processed in any way?   and while difficult for you, it's easy for the user to tell if you fail because if they get an email from the project its clear that their data is still being processed, and then let slip the dogs of complaints to the regulatory agencies.  

and if you though dealing with user requests was fun, just imagine dealing with multiple EU regulators who want to talk to you about your uses for the data and if the data being used is appropriate to the task or could it have been anonymized, or did you really need the email to provide a better user experience? 

Seriously folks, you've walked into a virtual minefield, turn around and carefully re-trace your steps before things start blowing up all around you.

**Comment by AlonsoChavarriaga** [comment]
The radio silence speaks volumes rather loudly!

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by ericketts** [comment]
from the other thread, the changelog pages have direct links to every version on them, you can use these to download without a user/pass (working as of the posting of this comment):
* [windows](https://docs.docker.com/docker-for-windows/release-notes/)
* [mac](https://docs.docker.com/docker-for-mac/release-notes/)

**Comment by 1138-4EB** [comment]
@ericketts, it has changed since you commented, isn't it?
