### ISSUE TITLE
There is no docker-ce package for AARCH64 (armhf)

### ISSUE THREAD

**Issue by jimmymagemtek** [docker/docker.github.io#7213]
I following the instructions of installing docker-ce on AARCH64 (armhf) from the URL below,

https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce-1

But I got the error message as below,

$sudo apt-get install docker-ce
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package docker-ce

My o.s. is Ubuntu 16.4 LTS.
Any suggestion is appreciated.

**Comment by ahh-docker** [comment]
Hello! Thanks for filing an issue with the Docker documentation team. Unfortunately, it looks like your issue is more of a support issue than a documentation issue.

For the Docker Community Edition (CE), please visit https://forums.docker.com/, and post your issue there.

For Docker Enterprise Edition (EE) subscribers, please visit https://success.docker.com/support, and contact Docker Support directly.

If this is a documentation issue, please reopen the issue, along with more detailed comments on what needs a review and possible edit. Thanks!
