### ISSUE TITLE
Missing actual download link for windows Docker Toolbox

### ISSUE THREAD

**Issue by celier** [docker/docker.github.io#7257]
File: [toolbox/toolbox_install_windows.md](https://docs.docker.com/toolbox/toolbox_install_windows/)
Hello, I found a small issue within the doc to install Docker Toolbox for Windows.
While trying to download the Docker Toolbox on "Step 2 : Install Docker Toolbox" of [Install Docker Toolbox for Windows](https://docs.docker.com/toolbox/toolbox_install_windows/), doc says to follow link to [Docker Toolbox](https://www.docker.com/toolbox), which redirects to [Docker Toolbox for Windows](https://docs.docker.com/toolbox/), which says download link is in the [Install Docker Toolbox for Windows](https://docs.docker.com/toolbox/toolbox_install_windows/) doc we came from to begin with.

**Comment by celier** [comment]
Nevermind, the link is almost at the top of the doc, just out of the natural reading flow.

**Comment by jancellor** [comment]
Pretty sure the link is missing.

(1) https://docs.docker.com/toolbox/
(2) https://docs.docker.com/toolbox/overview/
(3) https://docs.docker.com/toolbox/toolbox_install_windows/
(4) https://docs.docker.com/toolbox/toolbox_install_mac/

If you follow the text for Windows, (1) says go to (3) to install, and (3) says go to (1) to install. For Mac, (1) says go to (4) to install, which is correct because there is a big download button. The Windows version of this button is missing in (3). Incidentally, the overview (2) actually contains links to download for both Windows and Mac and is linked from (1) but no text indicates that you should go there.

**Comment by rik43** [comment]
same. 
solution https://github.com/docker/toolbox/releases

**Comment by tahiryasin** [comment]
Direct download link
https://download.docker.com/win/stable/DockerToolbox.exe
