### ISSUE TITLE
Wrong response with "docker node inspect" command

### ISSUE THREAD

**Issue by githubfromgui** [docker/docker.github.io#7282]
The command _docker node inspect --format '{{ .ManagerStatus.Leader }}' self_ says that it returns FALSE, but it's not correct, because the next command using _docker node inspect --pretty self_ (the same node **self**) displays TRUE.

File: [edge/engine/reference/commandline/node_inspect.md](https://docs.docker.com/edge/engine/reference/commandline/node_inspect/)

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This issue is old and the topic has changed. The current output provides examples to show the type and format of the information that may be displayed. The values themselves are irrelevant and may vary depending on your environment. If you feel this is still an issue, please let us know.
