### ISSUE TITLE
Still able to download docker without being logged in

### ISSUE THREAD

**Issue by lebfe** [docker/docker.github.io#7309]
It should not be possible to download docker without being logged in: https://store.docker.com/editions/community/docker-ce-desktop-windows

However, using this direct link allows anyone to download docker directly: https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe

It really hurts my user experience to be able to directly download docker.

I hope you will fix this issue and be consistent in the future, by making it not possible to download docker in any way without being logged in.

**Comment by ahh-docker** [comment]
Hello! Thanks for filing an issue with the Docker documentation team. Unfortunately, it looks like your issue is more of a support issue than a documentation issue.

For the Docker Community Edition (CE), please visit https://forums.docker.com/, and post your issue there.

For Docker Enterprise Edition (EE) subscribers, please visit https://success.docker.com/support, and contact Docker Support directly.

If this is a documentation issue, please reopen the issue, along with more detailed comments on what needs a review and possible edit. Thanks!
