### ISSUE TITLE
Performance impacted in docker 1.12.6

### ISSUE THREAD

**Issue by cmg1986** [docker/docker.github.io#7383]
There are multiple micro-service docker containers are running using docker-compose (1.19) & docker (1.12.6), so when i check my app end point for perf testing.. found time has been increased as compare to docker 1.8.
i checked same code base on 1.8 & 1.12.6 & found performance deviation in 1.12.6.

As an implementation, i am creating my own network in docker-compose & attaching containers to them.
ANy idea specific to performance analysis.

**Comment by ahh-docker** [comment]
Hello! Thanks for filing an issue with the Docker documentation team. Unfortunately, it looks like your issue is more of a support issue than a documentation issue.

For the Docker Community Edition (CE), please visit https://forums.docker.com/, and post your issue there.

For Docker Enterprise Edition (EE) subscribers, please visit https://success.docker.com/support, and contact Docker Support directly.

If this is a documentation issue, please reopen the issue, along with more detailed comments on what needs a review and possible edit. Thanks!
