### ISSUE TITLE
Not necessary to logout and log back

### ISSUE THREAD

**Issue by dkurzaj** [docker/docker.github.io#7384]
File: [install/linux/linux-postinstall.md](https://docs.docker.com/install/linux/linux-postinstall/)

Instead of advising to logout and log back in, maybe we could just advise to execute:
`newgrp docker` ?

But I'm not sure, maybe it hasn't the same range as the logout/login technique.

**Comment by nigelpoulton** [comment]
I've tested this on a few versions of Linux, and it's worked on every version. I also see that 7510 was approved but never merged, so I propose adding the following:

You may be able to issue a `newgrp docker -` command instead of logging out and back in. The `-` option forces a new environment, and you will be given a new shell (losing any command history etc). 

========

Randomly, does anyone have a clue what this comment is referring to "If testing on a virtual machine, it may be necessary to restart the virtual machine for changes to take effect." ??

Ping @sudo-bmitch
