### ISSUE TITLE
Docker Edge macOS super slow since latest update

### ISSUE THREAD

**Issue by sterichards** [docker/docker.github.io#7418]
### Problem description
Since my latest update to Version 2.0.0.0-beta1-mac75 (27117) I'm getting extremely slow Docker and local system. I had previously resolved Docker being slow by changing my Docker disk image from .qcow to .raw and also using :cached on my volumes. But since the latest update, i'm back to have a super slow system and very unresponsive Docker

### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by ahh-docker** [comment]
Hello! Thanks for filing an issue with the Docker documentation team. Unfortunately, it looks like your issue is more of a support issue than a documentation issue.

For the Docker Community Edition (CE), please visit https://forums.docker.com/, and post your issue there.

For Docker Enterprise Edition (EE) subscribers, please visit https://success.docker.com/support, and contact Docker Support directly.

If this is a documentation issue, please reopen the issue, along with more detailed comments on what needs a review and possible edit. Thanks!
