### ISSUE TITLE
404: at http://54.71.194.30:4018/userguide/dockervolumes/

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#77]
If you search on Google for "docker for mac volumes", one of the top results is pointing to `http://54.71.194.30:4018/userguide/dockervolumes/`, which is a broken link.

**Comment by johndmulhausen** [comment]
It looks like /v1.8/ links implied /engine/ before, which is problematic. Will have to edit 404.md to fwd people.

**Comment by johndmulhausen** [comment]
All Google indexes of old docs have been axed, which reduces the surface of this bug by a lot, however I'm keeping this open until I can do "double forwarding" (i.e. catch both an alias and an old version and resolve it with one forward)

**Comment by samrocketman** [comment]
Related.  I just visited https://docs.docker.com/v1.11/engine/reference/commandline/daemon/#daemon-configuration-file after reading `/etc/default/docker` and got redirected to http://54.71.194.30:4111/engine/reference/commandline/daemon/

I found this issue by web searching for the IP address.

**Comment by johndmulhausen** [comment]
@samrocketman Yes, we're working on better (non-IP address) URLs for the old docs, so that part is at least expected, if temporary, behavior. What I'm down to on this is ensuring that there are two levels of forwarding:

1) When trying to go to /v1.11, you end up at the correct archive URL, which is already happening, and
2) When trying to go to /v1.11/reference you are further redirected to archiveURL/engine/reference -- i.e., the redirect from /reference to /engine/reference works, even in the case of old docs. Trickier, to be sure. At the moment, only current-version aliases work, i.e. docs.docker.com/reference redirects to docs.docker.com/engine/reference

**Comment by johndmulhausen** [comment]
So, in reviewing this, I actually think we don't want the cascading forwards. This is because most forwards exist for the support of old URLs, which are precisely what were in place when the docs, as archived, were originally published.

For example: if you go to docs.docker.com/v1.11/mac -- that works right now, because in the v1.11 docs, there actually was a document at /mac. However, if we applied current forwarding logic and used cascading forwarding, an attempt to reach the v1.11/mac would first forward to the doc archive URL, *then* forward to /docker-for-mac/ at the archive URL, because we currently have an active forwarding directive that maps /mac to /docker-for-mac/. That directive should only be applied to the current/live docs, not archive docs. 

What I'll need to do is pull old redirect.csv files for old doc versions, and implement 404.md in every version of the docs archives, with each archive drawing from their respective redirect.csv.

**Comment by johndmulhausen** [comment]
This guy can be closed; our doc archive story is solid now.
