### ISSUE TITLE
Update Kitematic user guide to match current UI/app

### ISSUE THREAD

**Issue by jewettg** [docker/docker.github.io#777]
File: [kitematic/userguide.md](https://docs.docker.com/kitematic/userguide/)

All screen shots do not match anything I am seeing after installing 0.12.0.  
Is there more up-to-date docs?

**Comment by londoncalling** [comment]
### Hints for Hackathon

- The latest Kitematic app is available at: https://github.com/docker/kitematic/releases/
- We started the updates here: https://docs.docker.com/kitematic/userguide/ by updating the Overview content and the first image or two
- Suggest starting with [Creating a new container](https://docs.docker.com/kitematic/userguide/#creating-a-new-container) and working through the procedures, taking new screen snaps if current ones do not match, and updating the docs

**Comment by constanzekratel** [comment]
I'm going to start working on this one

**Comment by jmaitrehenry** [comment]
@constanzekratel do you need some help? I just install Kitematic

**Comment by londoncalling** [comment]
@jmaitrehenry I would go ahead and start working on it, create a PR etc and you guys can either share the work/points or whomever gets some good changes in first can have it. Just note that we rely on Netlify previews as part of our build check processs and it's down right now so that will stall us being able to merge PRs until it's back up. However we can still look at the updates you make to the files on GitHub in the meantime.

**Comment by jmaitrehenry** [comment]
I just push the last images!

**Comment by constanzekratel** [comment]
That's great. I still have an outstanding PR, not for images but for minor fixes I made to formatting. I'll be submitting that today.

**Comment by londoncalling** [comment]
Points for this to @jmaitrehenry , since the logged issue referenced a problem with images
