### ISSUE TITLE
no communication to docker ce from wsl bash

### ISSUE THREAD

**Issue by roytanmoy** [docker/docker.github.io#7924]
I am able to use docker from windows command prompt but not  from windows bash terminal.
~# docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
I have tried to create a /mnt/c/ to /c but it seems to be not working.

**Comment by roytanmoy** [comment]
this seems to be an open issue in windows bash.

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood,please reopen it with more information.
