### ISSUE TITLE
documentation too vauge: Enable SAML Authentication

### ISSUE THREAD

**Issue by sc10n** [docker/docker.github.io#7941]
File: [ee/ucp/admin/configure/enable-saml-authentication.md](https://docs.docker.com/ee/ucp/admin/configure/enable-saml-authentication/)

The documentation for ADFS settings for SAML is very vague and misleading. 

```
* Attribute Store: Active Directory.
  - Add LDAP Attribute = Email Address; Outgoing Claim Type: Email Address
  - Add LDAP Attribute = Display-Name; Outgoing Claim Type: Common Name
* Claim using Custom Rule. For example, c:[Type == "http://schemas.xmlsoap.org/claims/CommonName"] => issue(Type = "fullname", Issuer = c.Issuer, OriginalIssuer = c.OriginalIssuer, Value = c.Value, ValueType = c.ValueType);
* Outgoing claim type: Name ID
* Outgoing name ID format: Transient Identifier
* Pass through all claim values
```

This says that these are required values for ADFS settings. However, it doesn't specify which claim to use? Do we use all three? If so, the second and third ones are incomplete, what type of claim rule is the third one supposed to be? What are the incoming claims supposed to be? I would recommend specifying claim rule type and specifics for the rule.

**Comment by bermudezmt** [comment]
@pkennedyr can you help with questions from @sc10n above? Happy to address the documentation enhancement request once we have more details. cc: @paigehargrave

**Comment by nwalter82** [comment]
I have the same issue, the documentation is vague and/or very incomplete.

**Comment by paigehargrave** [comment]
@pkennedyr can you help with questions from @sc10n above? Happy to address the documentation enhancement request once we have more details.

**Comment by pkennedyr** [comment]
@ry4nz Can you advise on the questions posed by @sc10n above re: ADFS settings for SAML?

**Comment by ry4nz** [comment]
More detail info can be found here https://github.com/docker/orca/issues/5713

**Comment by paigehargrave** [comment]
@ry4nz @sc10n @nwalter82 - PTAL at #8832 - PTAL - I copied in some rough text and have no experience with this subject matter, so please add clarification as needed. Thank you!.

**Comment by nwalter82** [comment]
This is what I figured out:

Claim Rules:
1. Values from AD to SAML
Display-name : Common Name
E-Mail-Addresses : E-Mail Address
SAM-Account-Name : Name ID
2.  Transform Account Name to Name ID 
  Incoming type : Name ID
 Incoming Format: Unspecified
  Outgoing Claim type: Name ID
  Outgoing Format:  Transient ID
3.  Create Full Name for UCP (Custom Rule):  
c:[Type == "http://schemas.xmlsoap.org/claims/CommonName"]
 => issue(Type = "fullname", Issuer = c.Issuer, OriginalIssuer = c.OriginalIssuer, Value = c.Value, ValueType = c.ValueType);
4.  Pass Admin Value to allow admin access based on AD Group (Send Group Membership as Claim)
Users Group :  Your Admin Group
outgoing claim type: is-admin
outgoing claim value: 1
5.  Group mebership (for more complex organizations with multiple groups to manage access)
Send LDAP Attributes as Claims
Store:  Active Directory
Mapping:
Token-Groups - Unqualified Names : member-of


Note that we dropped using email address as an ID due to bugs we found in the way push and pull works in DTR.  Users with an @ symbol are not able to push or pull images from their personal repositories.  We replaced with just SAMAccountID though this may not be ideal if you have multiple domains.  Maybe a custom rule that appends a dash and creates something like "domain-SAMAccountName" as a login would be better.

Also be aware that there is a bug with single logout currently, it just does not work at all with ADFS/SAML.

Finally, there is a bug in the redirect process UCP does not pass a redirect URL to ADFS so users by default as sent back to UCP.  If you are using DTR this means the login flow goes like this:  DTR -> UCP -> ADFS -> UCP.  Users should go DTR -> UCP -> ADFS -> DTR.

**Comment by sc10n** [comment]
@nwalter82 Thanks for the claim rules. This has our UCP/DTR working with ADFS now. Is there any timeline on fixing the redirect after login issue? I have DTR users that don't utilize UCP (as its not certified for use in our environment yet) so it will be extremely confusing for them to end up at the UCP dashboard. I don't think I can turn on SAML until that is fixed.

**Comment by paigehargrave** [comment]
@nwalter82 @sc10n Thank yo u- PTAL and see if documentation changes are OK per #8832 .

**Comment by paigehargrave** [comment]
Closing due to changes made in #8832.
