### ISSUE TITLE
Release notes for DTR is missing for 2.4.8.

### ISSUE THREAD

**Issue by clemenko** [docker/docker.github.io#8067]
### Problem description
We are missing the Release Notes for DTR 2.4.8.
https://docs.docker.com/ee/dtr/release-notes/

### Problem location

https://docs.docker.com/ee/dtr/release-notes/

### Project version(s) affected
DTR 2.4.8

### Suggestions for a fix
Add the Release notes.

**Comment by bermudezmt** [comment]
https://github.com/docker/docs-private/issues/914#issuecomment-453638691 - Please see comment here. cc: @anthonyleungdocker @Docker-Minh I've had a few folks hit me up on the lack of change logs for `2.4.8` and `2.3.10`. Might make more sense to add a one-line change log?

**Comment by Docker-Minh** [comment]
@bermudezmt Thanks....I've asked @cquon to take a look.  This patch we made an update to golang because of the security issue.  My understanding was that we didnt document that anywhere else.

**Comment by bermudezmt** [comment]
@Docker-Minh this was my understanding also. Since there has been no precedent for mentioning Golang version bumps in any of the release notes for Engine, UCP, and DTR, I am closing this issue. Thanks, @cquon and @jose-bigio, who have both looked into this. cc: @paigehargrave in case you get questions later.
