### ISSUE TITLE
docker network issues on windows laptop with co-operate network

### ISSUE THREAD

**Issue by adilogishetty** [docker/docker.github.io#8094]
I am facing issues regarding the network for docker in my co-operate network on windows laptop.  i have set all the proxies and network configuration right , even though cant pull or download my images . 

issues:

1) when i try to pull any image i get the below issue .
Error response from daemon: Get https://registry.gear.ge.com/v2/: proxyconnect tcp: dial tcp :0: connect: connection refused

2)
![image](https://user-images.githubusercontent.com/21300480/51917343-57bf9b00-23ad-11e9-9339-517981b978bb.png)

also get network TCP reset issue 

i try to fix it by switching windows to linux containers regularly or rest docker or re-install docker for the above issues . dont find docker stable for windows .

Docker version 18.09.1, build 4c52b90

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood,please reopen it with more information.
