### ISSUE TITLE
Better port change callout

### ISSUE THREAD

**Issue by daywalked** [docker/docker.github.io#8241]
File: [ee/ucp/admin/install/upgrade.md](https://docs.docker.com/ee/ucp/admin/install/upgrade/)

A better callout that there are additional ports that are required from the previous UCP version. While the docs make the statement of "Ensure ports" it isn't a reference of port changes over time, but makes the user go track down different pages to compare between them. 

Port diff tables callout, explicitly in this upgrade page, would help clarity.

**Comment by traci-morrison** [comment]
@daywalked The `Troubleshooting` section has a reference to a page describing the ports used (https://docs.docker.com/ee/ucp/admin/install/system-requirements/#ports-used). In an effort to not duplicate content, we link to the relevant page instead of adding the content directly. Does this resolve the issue or would you like to provide additional information/context? Thank you!

**Comment by daywalked** [comment]
Abandoning.
