### ISSUE TITLE
Multiple errors with key and then signature can't be verified

### ISSUE THREAD

**Issue by fadimki** [docker/docker.github.io#8247]
File: [engine/examples/postgresql_service.md](https://docs.docker.com/engine/examples/postgresql_service/)

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
