### ISSUE TITLE
Fix inspect wiki page format example

### ISSUE THREAD

**Issue by Rora** [docker/docker.github.io#8252]
File: [engine/reference/commandline/inspect.md](https://docs.docker.com/engine/reference/commandline/inspect/)

The format example `docker inspect --format='{{json .Config}}' $INSTANCE_ID` doesn't work on windows 10. it requires double quotes e.g. `docker inspect --format="{{json .Config}}" $INSTANCE_ID` 

This should be fixed in the docs or relogged as a bug.

**Comment by nigelpoulton** [comment]
Hi Rora, can you supply any more info.

I've just tried it on my Windows 10 machine with the following config and it works as per the documentation:

Windows 10 Pro.  Version 1803 build 17134.648
Powershell
Docker Desktop 2.0.3.0 Edge channel
Engine version 18.09.3

Thanks

**Comment by nigelpoulton** [comment]
OK, my bad, I see this occurs if using `cmd.exe` instead of `Powershell`. I'll look into adding something to the docs.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/blob/master/docs/reference/commandline
In general, the $ usually hints that the command examples are for Linux.
