### ISSUE TITLE
Kali Linux post docker install update error!

### ISSUE THREAD

**Issue by dsx12** [docker/docker.github.io#8261]
After installing docker I can apt-get upgrade my system but when I apt-get update I receive the following error(s):

Hit:1 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease
Ign:3 https://download.docker.com/linux/debian kali-rolling InRelease
Err:4 https://download.docker.com/linux/debian kali-rolling Release
  404  Not Found [IP: 2600:9000:201a:7400:3:db06:4200:93a1 443]
Get:2 https://kali.download/kali kali-rolling InRelease [30.5 kB]
Get:5 https://kali.download/kali kali-rolling/main i386 Packages [17.1 MB]
Get:6 https://kali.download/kali kali-rolling/main amd64 Packages [17.2 MB]
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/debian kali-rolling Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Does anyone have a clue how to fix this issue???

**Comment by groundrat1993** [comment]
Seeing a similar issue.  Maybe changes coming since the release of 2019.1?


Get:1 http://kali.download/kali kali-rolling InRelease [30.5 kB]
Ign:2 http://kali.download/kali kali-rolling/non-free Sources
Get:3 http://kali.download/kali kali-rolling/main Sources [12.8 MB]
Ign:2 http://kali.download/kali kali-rolling/non-free Sources
Ign:4 http://kali.download/kali kali-rolling/contrib Sources
Get:5 http://kali.download/kali kali-rolling/main amd64 Packages [17.2 MB]
Ign:4 http://kali.download/kali kali-rolling/contrib Sources
Ign:6 http://kali.download/kali kali-rolling/contrib amd64 Packages
Ign:6 http://kali.download/kali kali-rolling/contrib amd64 Packages
Ign:7 http://kali.download/kali kali-rolling/non-free amd64 Packages
Ign:2 http://kali.download/kali kali-rolling/non-free Sources
Ign:4 http://kali.download/kali kali-rolling/contrib Sources
Ign:7 http://kali.download/kali kali-rolling/non-free amd64 Packages
Get:6 http://kali.download/kali kali-rolling/contrib amd64 Packages [375 kB]
Get:7 http://kali.download/kali kali-rolling/non-free amd64 Packages [796 kB]
Err:2 http://http.kali.org/kali kali-rolling/non-free Sources
  Connection failed [IP: 104.18.103.100 80]
Ign:4 http://http.kali.org/kali kali-rolling/contrib Sources
Fetched 375 kB in 4min 1s (1552 B/s)
Reading package lists... Done
E: Failed to fetch http://http.kali.org/kali/dists/kali-rolling/non-free/source/Sources  Connection failed [IP: 104.18.103.100 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by L-Hudson** [comment]
Thanks for opening this ticket, however, this GitHub issue tracker is not intended as a general support forum, but for [reporting bugs and feature requests for the documentation](https://raw.githubusercontent.com/docker/docker.github.io/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

* the Docker Support Forums - https://forums.docker.com
* the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not an issue with the documentation, but feel free to continue the conversation after I closed 🤗
