### ISSUE TITLE
where is the linux support Docker 0.7.0 Alex Larsson

### ISSUE THREAD

**Issue by tcpaul** [docker/docker.github.io#8262]
### Problem description

Look for your favorite distro page is missing

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/en/latest/installation/

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/en/latest/installation/

- Other: be more linux friendly

**Comment by thaJeztah** [comment]
That's a very very old location for the installation page. We should add a redirect for that

Curious though; where did you find a link to that URL?

**Comment by thaJeztah** [comment]
ah; looks to be in this blog post https://blog.docker.com/2013/11/docker-0-7-docker-now-runs-on-any-linux-distribution/

**Comment by tcpaul** [comment]
yeah thats the one. When i ```pacman -S docker``` am I using moby or docker ce? and why does the website only link windows and mac, this whole thing is based off linux containers

**Comment by thaJeztah** [comment]
The current version of the installation page can be found here; https://docs.docker.com/install/#supported-platforms

The community edition of Docker Engine is supported on Ubuntu, CentOS, Debian, and Fedora. 
[Docker Engine Enterprise](https://docs.docker.com/ee/supported-platforms/) is supported on Ubuntu, RHEL, CentOS, SLES, Oracle Linux, and Windows

Other platforms (e.g.  Debian and Ubuntu forks such as Linux Mint) _may_ work, but are not tested. 

In addition, there are statically compiled binaries (https://docs.docker.com/install/linux/docker-ce/binaries/) which may work for unsupported platforms (but have some limitations, as some features require dynamic linking)

**Comment by thaJeztah** [comment]
Opened a pull-request to add a redirect for the old location; https://github.com/docker/docker.github.io/pull/8269

**Comment by tcpaul** [comment]
ok im on arch linux and it works like butter ```pacman -S docker``` but I must say you make it look like docker is only for windows and mac

**Comment by thaJeztah** [comment]
> ok im on arch linux and it works like butter `pacman -S docker`

I guess that works; with a note that those likely are the distro-maintained packages (not the official docker packages).

Arch linux is fast moving distro (they keep up with latest packages), which unfortunately resulted in docker being broken frequently. Because of that, it was removed from the list of distros that Docker provides packages for.

> but I must say you make it look like docker is only for windows and mac

Can you explain this a bit more? The installation page https://docs.docker.com/install/#supported-platforms shows the platforms that Docker can be installed on which includes Linux, but also macOS and Windows.

Happy to hear what changes you'd like to see, but trying to understand what led you to that conclusion.

**Comment by tcpaul** [comment]
go to docker.com and click "get started"
