### ISSUE TITLE
Dockerized jenkins master to connect to jenkins agent

### ISSUE THREAD

**Issue by akmabrouk** [docker/docker.github.io#8285]
Hello,
I have jenkins master in docker container on CentOS 7 VM pulled from docker hub as jenkins image and run as a container. However, I have another VM where jenkins agent is installed manually (java, git, maven)

The question is: How do I connect the dockerized master  to the non dockerized slave through SSH ?
I know the setup on jenkins master GUI but from the command line I do not. I would know if the setup is without using Docker.

Your help is much appreciated. Thank you.

**Comment by L-Hudson** [comment]
Thanks for opening this ticket, however, this GitHub issue tracker is not intended as a general support forum, but for [reporting bugs and feature requests for the documentation](https://raw.githubusercontent.com/docker/docker.github.io/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

* the Docker Support Forums - https://forums.docker.com
* the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not an issue with the documentation, but feel free to continue the conversation after I closed 🤗
