### ISSUE TITLE
sudo docker run -p 4000:4000 -e DEBUG=botium* botiumbox

### ISSUE THREAD

**Issue by krishnasaikumarraju** [docker/docker.github.io#8305]
### Problem description

![image](https://user-images.githubusercontent.com/42143138/53031320-a0411480-3492-11e9-897e-eb80d1098081.png)

### Problem location
commands:
sudo docker run -p 4000:4000 botiumbox
sudo docker run -p 4000:4000 -e DEBUG=botium* botiumbox

### Project version(s) affected
package.json :
![image](https://user-images.githubusercontent.com/42143138/53031548-12195e00-3493-11e9-83a8-5c3aaa1c7bb8.png)

docker-compose.yml:
![image](https://user-images.githubusercontent.com/42143138/53031639-3f660c00-3493-11e9-9b32-19ddcd160131.png)

prisma.yml:
![image](https://user-images.githubusercontent.com/42143138/53031703-5f95cb00-3493-11e9-8280-0b1c4bcadf8c.png)

### Suggestions for a fix
dockerfile which is clonned from git repository:
![image](https://user-images.githubusercontent.com/42143138/53031812-9370f080-3493-11e9-8975-ead1de38c2a1.png)

Please can you provide best reference links to work on botium-box to generate a reports for smapi( i.e alexa skill ).

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
