### ISSUE TITLE
How to dockerize jenkins with other web applications so that they can talk to each other

### ISSUE THREAD

**Issue by akmabrouk** [docker/docker.github.io#8313]
Hi
As you know jenkins in a docker container is isolated. How do I make it talk  to applications pulled from github?

I pulled docker official image from docker hub and and launched jenkins container as follows:

docker run -d  -p 8080:8080 -p 50000:50000 -v /my/home/jenkins_home:/var/jenkins_home jenkins/jenkins

Many thanks

**Comment by akmabrouk** [comment]
Other applications are dockerized too using Dockerfile.

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood,please reopen it with more information.
