### ISSUE TITLE
apt update failing after initial install of docker - network error on directory for non-free download

### ISSUE THREAD

**Issue by groundrat1993** [docker/docker.github.io#8344]
Unable to complete apt update command.  Searching the link through a browser finds a network error in http://http.kali.org/kali/dists/kali-rolling/non-free/source/

The Sources.gz file is listing at only 132K, and give a "Failed - Network error" message.

See apt update output below:

Get:1 http://kali.download/kali kali-rolling InRelease [30.5 kB]
Ign:2 http://kali.download/kali kali-rolling/non-free Sources
Get:3 http://kali.download/kali kali-rolling/main Sources [12.8 MB]
Ign:2 http://kali.download/kali kali-rolling/non-free Sources
Ign:4 http://kali.download/kali kali-rolling/contrib Sources
Get:5 http://kali.download/kali kali-rolling/main amd64 Packages [17.2 MB]
Ign:4 http://kali.download/kali kali-rolling/contrib Sources
Ign:6 http://kali.download/kali kali-rolling/contrib amd64 Packages
Ign:6 http://kali.download/kali kali-rolling/contrib amd64 Packages
Ign:7 http://kali.download/kali kali-rolling/non-free amd64 Packages
Ign:2 http://kali.download/kali kali-rolling/non-free Sources
Ign:4 http://kali.download/kali kali-rolling/contrib Sources
Ign:7 http://kali.download/kali kali-rolling/non-free amd64 Packages
Get:6 http://kali.download/kali kali-rolling/contrib amd64 Packages [375 kB]
Get:7 http://kali.download/kali kali-rolling/non-free amd64 Packages [796 kB]
Err:2 http://http.kali.org/kali kali-rolling/non-free Sources
  Connection failed [IP: 104.18.103.100 80]
Ign:4 http://http.kali.org/kali kali-rolling/contrib Sources
Fetched 375 kB in 4min 1s (1552 B/s)
Reading package lists... Done
E: Failed to fetch http://http.kali.org/kali/dists/kali-rolling/non-free/source/Sources  Connection failed [IP: 104.18.103.100 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by bermudezmt** [comment]
Thanks for opening this ticket, however, this GitHub issue tracker is intended for [reporting bugs and feature requests for the documentation](https://raw.githubusercontent.com/docker/docker.github.io/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of:

* the Docker Support Forums - https://forums.docker.com
* the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I’m closing this issue because this is not an issue with the documentation, but feel free to continue the conversation after I closed.
