### ISSUE TITLE
-d

### ISSUE THREAD

**Issue by hotkongzaa** [docker/docker.github.io#8365]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by paigehargrave** [comment]
Thanks for opening this ticket, however, this GitHub issue tracker is limited to [reporting bugs and feature requests for the documentation](https://raw.githubusercontent.com/docker/docker.github.io/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

* the Docker Support Forums - https://forums.docker.com
* the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I’m closing this issue because this is not an issue with the documentation, but feel free to continue the conversation after I closed :hugging_face:
forums.docker.com
Docker Forums
Docker discussion forum
