### ISSUE TITLE
`dtr reconfigure` behaviour changed in 2.6 with regard to switching storage backends

### ISSUE THREAD

**Issue by adamancini** [docker/docker.github.io#8370]
### Problem description
In DTR 2.6, changing storage backends involves initializing a new metadatastore.  In previous versions of DTR, the expected behaviour of `docker/dtr reconfigure --nfs-storage-volume` when changing NFS storage servers did not involve an initialization step, and it was trivial to move NFS servers by copying the entire contents of the NFS share to another server and switching endpoints with `reconfigure`

With DTR 2.6, if you `reconfigure` and change NFS servers, the metadatastore is initialized and tag history is lost.  We can avoid this by performing a `dtr restore` immediately afterward and specifying the `--dtr-storage-volume` option pointed at the existing NFS volume.

If someone were to change NFS servers in the way they are used to, from operating previous versions of DTR, they can encounter a situation where it appears that they've lost their entire tag history.  

This is not adequately explained in one single place - the information must be inferred from other sources

via DTR release notes page
>When installing and restoring DTR from an existing backup, users are now required to specify a storage flag: --dtr-use-default-storage, --dtr-storage-volume, or --nfs-storage-url. This ensures recovery of the configured storage setting when the backup was created. See docker/dtr restore for more details.

via DTR `restore` CLI reference
https://docs.docker.com/reference/dtr/2.6/cli/restore/

via DTR `reconfigure` CLI reference
https://docs.docker.com/reference/dtr/2.6/cli/reconfigure/

### Problem location

https://github.com/docker/escalation/issues/1121

### Project version(s) affected

DTR 2.6
https://docs.docker.com/ee/dtr/admin/configure/external-storage/nfs/

**Comment by adamancini** [comment]
@trapier

**Comment by adamancini** [comment]
Suggestions for fix:

Outline the process of moving storage correctly, considering the behaviour of dtr:2.6, and link to release notes/known issues

**Comment by bermudezmt** [comment]
@adamancini just to make sure I'm up to speed on this issue - is the "suggestions for fix" fully outlined in the kbase article you are working on? Do I then need to:
- add a brief description of the new behavior
- link to the kbase with the `2.6` NFS steps
- link to release notes 

How about the `restore` and `reconfigure` CLI pages? Are the storage flag descriptions still a little bit vague and need further clarification?

**Comment by adamancini** [comment]
@bermudezmt yeah I think we need to at minimum outline that behaviour on the "Use NFS" page, and I think we should also put a note in the `reconfigure` docs since that's the main way we'd encounter this problem

**Comment by bermudezmt** [comment]
@adamancini @caervs Please have a look at https://github.com/docker/docker.github.io/pull/8384 which will hopefully prevent further escalations around this issue. I am still confused by this comment from @quadespresso :

> Also, it would appear that --nfs-storage-url is the flag which will trigger the "hello there, you must be a new storage backend -- let me prune all existing image metadata from RethinkDB" response.
> 
> The path forward: use --dtr-storage-volume instead of --nfs-storage-url (verified as DTRT by @caervs)

Does the above mean we shouldn't be recommending --nfs-storage-url as a restore flag? How about for reconfigure?

**Comment by caervs** [comment]
@bermudezmt correct. With any DTR that has online gc there's really no way to recover all the metadata from a storage backend alone which is why you need to restore with the metadata from a backup. So we deprecated support for moving your storage from one backend to another.

If customers really need this though we should consider adding and back-porting flags for separately recovering metadata and switching storage backends. For now, for just the NFS use-case we have the above workaround.

**Comment by bermudezmt** [comment]
@squizzi @caervs Want to make sure we capture all the necessary updates to prevent this issue later on. It looks like I had missed a page in #8384 that also needs updating, https://docs.docker.com/ee/dtr/admin/disaster-recovery/restore-from-backup/:
> If you’re using NFS as a storage backend, also include --nfs-storage-url as part of your restore command, otherwise DTR is restored but starts using a local volume to persist your Docker images.

Since I've previously documented that a storage flag is required but it can basically be `--dtr-storage-volume`, `--dtr-use-default-storage`, OR `--nfs-storage-url` – yet specifying `--nfs-storage-url` has caused the customer escalation – I'll need some guidance on updating the descriptions for these storage options, and whether the implications are different for `docker/dtr reconfigure` and `docker/dtr restore`. Does this make sense?

**Comment by caervs** [comment]
> Does this make sense?

Absolutely. I can give some guidance here. Wanna go over the details next week when you're in SF? I think it'll be easier face-to-face.

**Comment by adamancini** [comment]
So in conversation today with @axeal and @RomainBelorgey we customers asking how to move from NFS to S3-compatible storage, and we don't set up a named volume for S3 storage, so it's not clear to me how a customer would "move" from one S3 bucket to another or from NFS/volume storage to S3 (and vice versa)  without a long-argument flag with `restore` to S3.

If the accepted process for switching storage is going to be:
1) backup metadata
2) change storage
3) restore metadata and use --dtr-storage-volume to use existing storage

what's the process if there's no named volume, such as with S3?

**Comment by squizzi** [comment]
@caervs ditto on @adamancini 's comment above, from looking at the code it doesn't appear to me that we have any way to move storage backends from NFS to S3 (or really any other "endpoint based storage" for that matter), we can't employ the `dtr-storage-volume` workaround here outside of perhaps having customer use an s3 volume driver instead of the specific settings in DTR to manage their s3.

My assumption is this functionality is deprecated.  I agree with Ada's thinking here that this is certainly a major departure in customer expectations and something they will want to do, we're going to be seeing a lot of this in the future.
