### ISSUE TITLE
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"ip\": executable file not found in $PATH": unknown

### ISSUE THREAD

**Issue by andresfaj** [docker/docker.github.io#8434]
File: [network/network-tutorial-macvlan.md](https://docs.docker.com/network/network-tutorial-macvlan/)

I want to run a docker container, and I want the ip of that container to be an ip visible from my home network.
I'm trying to do that with a macvlan docker network.
Does anyone know another way to do this or how to solve this problem?

Thank you all

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood,please reopen it with more information.
