### ISSUE TITLE
error response from daemon docker container not running

### ISSUE THREAD

**Issue by kausthub97** [docker/docker.github.io#8530]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
