### ISSUE TITLE
I want to create user at Mesibo but i am facing some issues Sorry, we can't find that page It seems the page you’re looking for doesn’t exist. Maybe you’re on the wrong track, maybe you found a broken link. Who knows?  Either way, here’s a couple of options for you:  Open an issue Go to back Tweet us something

### ISSUE THREAD

**Issue by techradiusopc** [docker/docker.github.io#8570]
<Describe how you got there>
Please anyone here to help related to these issues and also help to complete my this task 
and I am using following URL for creating a user at "Mesibo".

"https://mesibo.com/api/api.php?token=cn9cvk6gnm15e7lrjb2k7ggggax5h90n5x7dp4sam6kwitl2hmg4cmwabet4zgdw&op=useradd&appid=com.mesibo.demoapp&addr=18005550001"

token = Application Token
appid = Android or iOS app id (for example, com.mesibo.xxx). In case of web, just pass, ‘web’ as appid. Note that, for security reasons, the token generated for a particular appid will only be usable on app matching that appid.
addr = end point address, for example, a user phone number.

Thanks

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/&nbsp; to see if you can find a solution.  

If this really is a documentation issue and I have misunderstood,please reopen it with more information.
