### ISSUE TITLE
Where do the Docker for Windows release notes come from?

### ISSUE THREAD

**Issue by AnthonyMastrean** [docker/docker.github.io#8575]
### Problem description

I'm trying to find a reliable location for notifications about Docker for Windows releases. The docs.docker.com pages do not provide feeds (#8574). The various "page to RSS" services out there are _terrible_. And your own release notes pages lag the actual releases (https://github.com/docker/compose/issues/6620).

### Problem location

https://github.com/docker/docker.github.io/blob/master/docker-for-windows/release-notes.md

### Project version(s) affected

(all)

### Suggestions for a fix

So, I had the same problem with [Compose release notes](https://docs.docker.com/release-notes/docker-compose/). I went searching and found that the release notes originate from the [GitHub releases](https://github.com/docker/compose/releases). I can now use the API for more robust notifications (like Zapier's "watch for new releases").

However, I don't see any [Docker for Windows releases](https://github.com/docker/for-win/releases)... do you actually just write the release notes directly in that md file? or am I missing the source?

**Comment by usha-mandya** [comment]
The best way to get notifications about newer versions of Docker Desktop, the application (mac / Windows) checks internally for newer versions.
To get external notifications in order to plug custom scripts on this, it is possible to check the latest published version at https://download.docker.com/mac/edge/appcast.xml and https://download.docker.com/windows/edge/appcast.xml, but this is an internal Desktop mechanism that is subject to change without notice.
