### ISSUE TITLE
the page needs to provide context

### ISSUE THREAD

**Issue by djh42** [docker/docker.github.io#8592]
File: [engine/docker-overview.md](https://docs.docker.com/engine/docker-overview/)

I came to the overview page via a google search. It seemed quite well written and about the right level. So I started reading and followed it to the point where it says

`$ docker run -i -t ubuntu /bin/bash`

I tried that and it failed. I joined the forum and got told (a) I need to start dockerd and (b) I need elevated privileges (root was suggested).

So I believe this page should either include instructions to start dockerd before presenting the example and use a # prompt rather than a $ or it should include text at the beginning pointing out that it is not the first page in the tutorial and indication where the starting point is. The left-hand column is not prominent enough without some supporting text.

**Comment by djh42** [comment]
To make a specific suggestion. I believe it would be helpful to add at the top of the page something like:

> Now that you've read how to get and install Docker, and got an understanding of its components by reading previous parts in this tutorial, we provide an overall summary of Docker.

It does feel a little strange to provide the Overview after the more detailed explanations though, so maybe a more substantial overhaul would be better.

**Comment by bermudezmt** [comment]
@thaJeztah @shampabh Is this something you can prioritize for future Engine work?

**Comment by djh42** [comment]
Not quite sure what has changed or how that is an answer to the issue?

**Comment by craig-osterhout** [comment]
Hi @djh42, thanks for sharing the issue. The docs have been restructured. 
Please take a look at the current [get-started tutorial](https://docs.docker.com/get-started/) and let us know if any of the issues persist for new users.
In the current docs, the overview topic ([engine/docker-overview.md](https://docs.docker.com/engine/docker-overview/)) is an overview of concepts rather than a task. At the end of that topic, the user is guided to install Docker and go through the get-started tutorial.
