### ISSUE TITLE
there is no "installation" guide in docs

### ISSUE THREAD

**Issue by kandeshvari** [docker/docker.github.io#8624]
### Problem description

No page for docker installation at https://docs.docker.com/install/linux/docker-ce/#install-using-the-repository

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. As this issue is old, the context may have changed. It appears that is issue is no longer applicable to the current docs. If the issue still persists, please let us know.
If you were looking for Linux installation instructions, you can now find them here, https://docs.docker.com/engine/install/
