### ISSUE TITLE
I'd like to know what are 'normal' or 'alarming' results. I have containers using 50% of their memory, don't know why..

### ISSUE THREAD

**Issue by erwinvanlun** [docker/docker.github.io#8742]
File: [engine/reference/commandline/stats.md](https://docs.docker.com/engine/reference/commandline/stats/)

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/  to see if you can find a solution.  

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
