### ISSUE TITLE
Why can't access the docker server from browser?

### ISSUE THREAD

**Issue by agrawalsmart7** [docker/docker.github.io#8825]
Hi,

I have an image of php:7.2-apache. It runs successfully in the docker. I have created a file in /var/www/html/ in that. And Now I want to access that file. I tried to get the IP of docker mahcine and it was 172.17.0.7 and my host machine is on 192.168.0.2. Its all about the subnets. 

So can you please tell me how can I change that?

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not
about Docker documentation, but that you may be having trouble with
Docker itself. Please file a Docker support ticket or check out
https://forums.docker.com/&nbsp; to see if you can find a solution.
 
 If this really is a documentation issue and I have misunderstood,
please reopen it with more information.
