### ISSUE TITLE
Docker container cannot connect to host machine: No route to host

### ISSUE THREAD

**Issue by Mohamed095** [docker/docker.github.io#8852]
My docker containers cannot reach my host machine!

When I enter the container, I am able to ping my host machine:

However when I try and retrieve the home page using curl inside the container:

curl http://${HostIP}:80

I get:

curl: (7) Failed connect to ${HostIP}:80; No route to host

I cannot figure out what should be done to resolve this No route to host error.

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
