### ISSUE TITLE
explain "pool" category of releases/channels

### ISSUE THREAD

**Issue by brainwane** [docker/docker.github.io#8875]
File: [install/linux/docker-ce/debian.md](https://docs.docker.com/install/linux/docker-ce/debian/)

(but also https://docs.docker.com/install/ )

The documentation says:

> Docker CE has three types of update channels, stable, test, and nightly:

> *    Stable gives you latest releases for general availability.
> *    Test gives pre-releases that are ready for testing before general availability.
> *    Nightly gives you latest builds of work in progress for the next major release.

So what are "edge" and "pool" in, for instance, https://download.docker.com/linux/debian/dists/buster/ ? And why does one go into `pool/stable/` for the current stable release rather than `stable/`, which is more intuitive and is what I initially assumed I should choose?

**Comment by cflee** [comment]
`pool` seems to have the same meaning as in the [Debian Repository Format](https://wiki.debian.org/DebianRepository/Format), in that it contains the deb files instead of the Packages/Release files, so it's not something they came up with -- though the location is a bit unexpected. Usually it'd be at the archive root, i.e. `https://download.docker.com/linux/debian/pool` instead, but it seems like that's just convention and it's valid to put it under the dist instead.
