### ISSUE TITLE
Feedback for: engine/admin/logging/splunk.md

### ISSUE THREAD

**Issue by shazChaudhry** [docker/docker.github.io#89]
URL: engine/admin/logging/splunk.md

My environment is  "docker for windows v1.12.1 and VirtualBox on windows 10"; created a node using command "docker-machine create --driver virtualbox node1". Once a  node is created, how can the daemon be configured? This is the error I am getting:
docker@node1:~$ dockerd --log-driver=splunk
FATA[0000] Error starting daemon: pid file found, ensure docker is not running or delete /var/run/docker.pid

where is the daemon configuration file that can be configured before restarting the node?

**Comment by mstanleyjones** [comment]
Hi, when using Docker Machine, you pass your configuration options when creating the machine. See https://docs.docker.com/machine/reference/create/#/specifying-configuration-options-for-the-created-docker-engine for details.

However, you should consider using Docker for Windows instead of Docker Machine, since you are on Windows 10. See https://docs.docker.com/docker-for-windows/.

It looks like your question is not specifically about the documentation, but about using Docker. If you have more questions along these lines, consider asking a question on forums.docker.com. Thanks!
