### ISSUE TITLE
docker shared folder

### ISSUE THREAD

**Issue by kolet** [docker/docker.github.io#8923]
not sure if this is the right place.

i have read multiple articles , and even here on a close issue https://github.com/docker/docker.github.io/issues/2979

i am trying to share a container folder with the host and no the way around.

i want to share the (container) apache log directory with the host and the www folder.

to share a folder from the host to the container that would be simple as 
```
sudo docker build -t myimage. &&  docker run  -d --name wordpress -p 80:80 -v /host/folder/:/container/folder/  myimage
```

 problem occurs when u want to share the container folder WITH the host, basically what happen is when running /srv/log/:/var/log/apache2/ instead of sharing "var/log/apache2" with the host,  it shares "srv/log" to var/log/apache2 which make apache crash .

same if i want the share the www folder from the docker to the host.
instead of sharing the www folder with the host, it shares the host folder and exposed it on port 80 :s

i have yet found a solution about it.
i dont wish to hold the files on the host.

is there a way to share a docker folder WITH the host (and not host:container) ?

thanks

**Comment by kolet** [comment]
up :o

**Comment by kolet** [comment]
no one as answer for that ?

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out
https://forums.docker.com/&nbsp; to see if you can find a solution.
  
If this really is a documentation issue and I have misunderstood, please reopen it with more information.
