### ISSUE TITLE
copy file from host to container does not happening 

### ISSUE THREAD

**Issue by Rezk97** [docker/docker.github.io#8943]
i am using nvidia docker 2 and trying to copy a folder from my computer to the container using this command and i already cd to the folder path
docker cp ./model tf_container_gpu:/serving
the command runs with no output 2 days ago when i tried this it worked correctly and when i use this ls command in the container shell it shows me my folder but now when i am trying to copy the command run with no output to but the container does not have the folder

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
