### ISSUE TITLE
Wrong folder when extracting backup files

### ISSUE THREAD

**Issue by ibreschi** [docker/docker.github.io#8989]
File: [storage/volumes.md](https://docs.docker.com/storage/volumes/)

As from title.

```
docker run --rm --volumes-from dbstore2 -v $(pwd):/backup ubuntu bash -c "cd /dbdata && tar xvf /backup/backup.tar --strip 1"
```
to 
```
docker run --rm --volumes-from dbstore2 -v $(pwd):/backup ubuntu bash -c " tar xvf /backup/backup.tar"
```

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/&nbsp;to see if you can find a solution.  

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
