### ISSUE TITLE
docker windows server 2016 does not start - no matching manifest

### ISSUE THREAD

**Issue by andrecavalcanti** [docker/docker.github.io#8993]
Docker does not start

I'm using Windows Server 2016 Version 1607

if a run  docker run -d --name windows_nginx -p 8080:80 nginx:latest

I get the error below

![image](https://user-images.githubusercontent.com/6551266/60172499-caa53480-97da-11e9-8bfe-4ae31d9f6fb3.png)

![image](https://user-images.githubusercontent.com/6551266/60172437-a9dcdf00-97da-11e9-9ca2-3d3d1e539499.png)

![image](https://user-images.githubusercontent.com/6551266/60172473-bbbe8200-97da-11e9-852e-d46b76bafeb5.png)

Thanks,

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
