### ISSUE TITLE
Got error when trying to delete image from local registry

### ISSUE THREAD

**Issue by Hoangnse03193** [docker/docker.github.io#9028]
hi all,

I deploy  a local registry as bellow
https://docs.docker.com/registry/deploying/

After push an image to that local registry, I delete this image from local registry by Docker Registry HTTP API V2
https://docs.docker.com/registry/spec/api/

And then run garbage collect

docker exec registry bin/registry garbage-collect /etc/docker/registry/config.yml

After that I push the same image, that I push before, to local host and then try to pull it again from the local registry, 
I got error
"Error response from daemon: manifest for localhost:5000/my-ubuntu:latest not found: manifest unknown: manifest unknown".
And when I try to delete this image again I got status " HTTP/1.1 404 Not Found"

Any one know what wrong and how to fix it?

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
