### ISSUE TITLE
Add explanation for 'dangling image'

### ISSUE THREAD

**Issue by hamiltont** [docker/docker.github.io#9053]
File: [engine/reference/commandline/image_prune.md](https://docs.docker.com/engine/reference/commandline/image_prune/)

This doc repeatedly references dangling images, but never explains what those are. This is a bit of a catch-22. if you don't know what the term means, there's no help here, but if you do know what it means then you probably don't need these docs.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. You can find the definition here, https://docs.docker.com/config/pruning/
The topic referenced in the issue is maintained in an upstream repo. If you'd like to report the issue to maintainers, please help create an issue in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
