### ISSUE TITLE
Add image size to docker search result

### ISSUE THREAD

**Issue by Ayanmullick** [docker/docker.github.io#9059]
File: [engine/reference/commandline/search.md](https://docs.docker.com/engine/reference/commandline/search/)

Please add the image size column to the image search results. One should be able to see image size before pulling.

**Comment by thaJeztah** [comment]
Thanks for opening this issu; this doesn't look like a request for the documentation,  but a feature request for the docker daemon (which should be opened in https://github.com/moby/moby/issues)

Unfortunately though; I think think the Docker Hub API that's used to search images returns this information, so it's not possible to add that unless Docker Hub returns that information.

I'll close this issue because of the above, but feel free to continue the conversation
