### ISSUE TITLE
net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by JokerDevops** [docker/docker.github.io#9136]
hi,
I used docker-compose to build the harbor mirror warehouse and opened HTTPS for accessing login through the browser. But there are always some problems when I use it with docker.
I logged in with `docker login harbor.name.com.`
I use the `docker pull harbor.name.com/test/test:1` download my mirror.
I use the `docker push harbor.name.com/test/test:2` upload I wake up.
It's successful, but sometimes it comes up when I use `docker login` or `docker pull` or `docker push` will be net/HTTP: request canceled while waiting for the connection (Client) Timeout exceeded while awaiting headers)

My harbor warehouse and docker host are both under a local area network.

**Comment by EricBatty** [comment]
I hope to get your help. Thank you

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
