### ISSUE TITLE
Dockerfile Healthcheck Default Cannot be 0s

### ISSUE THREAD

**Issue by shane-walker** [docker/docker.github.io#9207]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)
https://docs.docker.com/engine/reference/builder/#healthcheck

The default value for Healthcheck `start-period` should be `1ms` or whatever the actual default value is since `0s` is not valid.
> Error response from daemon: Dockerfile parse error line 42: Interval "start-period" cannot be less than 1ms

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
This content is maintained in an upstream repo at https://github.com/docker/cli/tree/master/docs/reference. If the issue is still applicable, please help open the issue in that repo so it can get looked at.

For additional reference:
https://github.com/docker/cli/commit/a58f798fdf87a6986e3c50538342e3b713421e9a
