### ISSUE TITLE
Docker machine is heavily used in Get Started but it is superseded

### ISSUE THREAD

**Issue by GPPassos** [docker/docker.github.io#9262]
### Problem description

Apparently Docker Machine was superseded, or at least [it is under Superseded products and tools in Products Manuals](https://docs.docker.com/machine/overview/) (without any explicit guidance, but see https://github.com/docker/docker.github.io/pull/9239).

However, it is heavily used in the Get Started, suggesting to new users that it is the recommended technology.

Is this intended to be the case or should the get started be changed?

### Problem location

It involves the [Get Started](https://docs.docker.com/get-started/) and [the location of Docker Machine in navigation bar on the left](https://docs.docker.com/machine/overview/) .

### Suggestions for a fix

1. It should be made explicit whether (and why, or at least some pointer) Docker Machine was superseded (https://github.com/docker/docker.github.io/pull/9239)
2. If so, the Get Started should likely be changed to use the new tool that supersedes docker machine

**Comment by ls42** [comment]
Is someone able to tell what the replacement for docker-machine is? I'm unable to find the answer in #9239 either.

**Comment by ivanistheone** [comment]
In case anyone else is wondering, the replacement for docker-machine is to just set `DOCKER_HOST` env variable to `ssh://<user>@<host>`. In other words, there is no more need need for docker-machine since docker tooling now support ssh transport as a built-in feature.
 
Learned via https://github.com/docker/machine/issues/4537

Details:
 - If you have ssh login for `root` on the remote machine set `export DOCKER_HOST=ssh://root@example.com` (may be considered bad security practices)
 - To use a non-root user `user` set `export DOCKER_HOST=ssh://user@example.com` after adding `user` to the `docker` group using `sudo usermod -aG docker user`.  (tested on Ubuntu 18.04)

**Comment by justincormack** [comment]
Docker machine is no longer mentioned in the Get Started Guide, which now uses Docker Desktop, so closing this issue. As mentioned above and elsewhere, in general you can provision a machine with Docker easily, just find a machine image with Docker pre installed or use `get.docker.com` and then use the ssh transport as above.

**Comment by tedgoddard** [comment]
@justincormack Sorry to reanimate this closed issue, but it's a top search hit. It looks like `docker context create` provides some of the cloud provisioning features, but it's not clear how to use `docker-machine create --driver azure --size Standard_NC6s_v2` (it doesn't seem possible to specify the machine size to ensure that a GPU is available, say.)
