### ISSUE TITLE
There is loop referencing when looking for windows installer

### ISSUE THREAD

**Issue by AnimusPEXUS** [docker/docker.github.io#9273]
File: [docker-for-windows/install.md](https://docs.docker.com/docker-for-windows/install/)
There is loop referencing when looking for docker for windows installer and no actual installer can be found.

![Screenshot_2019-08-20 Docker Hub](https://user-images.githubusercontent.com/28504589/63376630-f259e880-c396-11e9-918f-95441b67e5b5.png)
![Screenshot_2019-08-20 Install Docker Desktop for Windows](https://user-images.githubusercontent.com/28504589/63376633-f2f27f00-c396-11e9-90d6-cb91ad80691b.png)

**Comment by AnimusPEXUS** [comment]
Is Docker Toolbox is the installer I looking for? Is it deprecated or i wrongly understood the articles?

**Comment by guba-odudkin** [comment]
Same. Any help?

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood,please reopen it with more information.
