### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by Mattacks** [docker/docker.github.io#9337]
File: [_samples/library/debian/index.md](https://docs.docker.com/samples/library/debian/)

Which is correct:
'primarily of free...'
or
'entirely of free'
?

**Comment by ollypom** [comment]
Hey @Mattacks , this page is actually not maintained in this repository, so unfortunatley I will close this issue. This is issue is related to https://github.com/docker-library/docs/. 

Specifically your issue is referring to differences in https://github.com/docker-library/docs/blob/master/debian/README-short.txt and https://github.com/docker-library/docs/blob/master/debian/README.md. Feel free to raise an Issue or PR in that repository.
