### ISSUE TITLE
All the disk-related operations are extremely slow after update

### ISSUE THREAD

**Issue by guba-odudkin** [docker/docker.github.io#9360]
### Problem description
After todays update PHP projects are impossible to use. file_exists() checks started taking forever:
140 file_exists() calls take more than 2 seconds. Nothing else was changed, only docker updated. 
SSD disk with NTFS. 
update: ant filesystem operation from within docker is extremely slow

### Project version(s) affected
Windows 10 64 bit
Docker 2.1.0.2 (37877)

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
