### ISSUE TITLE
`tmpfs-size` does not take effect

### ISSUE THREAD

**Issue by weiliang-ms** [docker/docker.github.io#9403]
### Problem description
When i set `tmpfs-size=1024` , it does not take effect.

Documentation is provided below：

![image](https://user-images.githubusercontent.com/18642754/64486309-2588ec80-d25e-11e9-9d63-7094a135a451.png)

### Problem location

My test results：
![image](https://user-images.githubusercontent.com/18642754/64486417-7f3de680-d25f-11e9-936f-23d6be0459b2.png)

### Project version(s) affected

My Docker version：
![image](https://user-images.githubusercontent.com/18642754/64486326-5cf79900-d25e-11e9-8d47-1c5c12cd3bd1.png)

**Comment by weiliang-ms** [comment]
Isn't the default unit byte？

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood,please reopen it with more information.
