### ISSUE TITLE
Docker Desktop 2.1.2.0 (38030) won't install on Windows 10 Professional

### ISSUE THREAD

**Issue by philb32** [docker/docker.github.io#9411]
### Problem description

Windows is telling me that 2.1.2.0 (38030) update is available, but the installation always fails.

### Problem location

Don't know. It's something to do with file permissions. I did upload a bug report but I don't know how to find the UUID of it.

So my installation is stuck at 2.0.5.0 (35318)

**Comment by boumanb** [comment]
I'm experiencing the same issue.

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
