### ISSUE TITLE
Docker data lost when host is restarted

### ISSUE THREAD

**Issue by D-04** [docker/docker.github.io#9488]
### Problem description
Upon restart of the host machine all the docker containers that were mounted with `-v` to a local filesystem on the host machine lost their data.

### Details
I am running `Docker version 18.09.7, build 2d0083d` on `Ubuntu 18.04.3 LTS x86_64` 

I also found out that this happened to other people that had their rootFS mounted to tmpfs but mine isnt mounted to tmpfs.

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood,please reopen it with more information.
