### ISSUE TITLE
container not running

### ISSUE THREAD

**Issue by JHmiddleton45** [docker/docker.github.io#9489]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by JHmiddleton45** [comment]
vagrant@ubuntu-xenial:~/go/src/trade-finance-logistics/network$ docker exec -it cli bash
Error response from daemon: Container 513df9b51f83e8ed8ebe9fe7003b1cd9afc3d2b4be35e0ae26e358a2d8c016c3 is not running

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check https://forums.docker.com/ to see if you can find a solution.  

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
