### ISSUE TITLE
All ports are exposed on Windows transparent network

### ISSUE THREAD

**Issue by danzaharescu** [docker/docker.github.io#9557]
### Problem description

I am using docker for windows, 1809 core, and I want to control what ports are exposed to the outside world. I am using the transparent network type, created like this:

docker network create -d transparent --subnet=mysubnet --gateway=mygateway mytransparentnet

To start the container, I am using 

docker run -p 8080:8080   -v \\.\pipe\docker_engine:\\.\pipe\docker_engine (other volumes)....  --network=mytransparentnet  --ip  myip --name=containerName --rm imageName:1.0

In Dockerifile, I have 
EXPOSE 8080:8080 

The problem is that any port is exposed to the outside world. I need that some ports to only be accessible internally. Is there any solution to achieve this ?
 
### Problem location

Did not find any reference to this problem.

### Project version(s) affected

Docker version 18.09.2, build 6247962

### Suggestions for a fix

If I start the container with no network configured, the behavior is as needed, I cannot access internal ports.
But I need to access an external server from within the container, so the network has to be transparent.

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
