### ISSUE TITLE
Feedback for: engine/userguide/networking/work-with-networks.md

### ISSUE THREAD

**Issue by bscheshir** [docker/docker.github.io#96]
URL: engine/userguide/networking/work-with-networks.md

"Let’s try to reach these aliases from container4 (which is connected to both these networks) and container5 (which is connected only to isolated_nw)."
isolated_nw not included container5 now! (docker network disconnect isolated_nw container5)
flip example logic with "local_alias"

**Comment by mstanleyjones** [comment]
Thanks for your feedback. I'll review the docs and make sure the logic is correct.

**Comment by mstanleyjones** [comment]
Hi @bscheshir, thanks again for your feedback on this. As it turns out, it is perfectly fine (and part of the point of the exercise) that `container5` doesn't yet exist when you like `container4` to it. I've done a pretty big rewrite of this whole topic, and part of that rewrite was to add clarity around that step specifically. You can link to a container which doesn't yet exist, and there are some reasons you might do it. Please have a look at #235 and let me know if that helps. I've asked some developers who are very familiar with Docker networking to review it as well.

I think I've addressed your issue, so I'll close this and we can move any follow-up discussion into the PR. Thanks!
