### ISSUE TITLE
Insecure Registry Connection Failed

### ISSUE THREAD

**Issue by bradfox2** [docker/docker.github.io#9673]
### Problem description

docker pull `private registry hostname:imagename` results in:

"Error response from daemon: Get `registry server hostname:port`: dial tcp: lookup `registry server hostname` on 192.168.65.1:53: no such host "

after an upgrade from 2.0.0.3 to 2.1.0.3

Unable to connect to insecure registry on 2.1.0.3, was able to connect previously on 2.0.0.3 with same settings.  Registry is set in docker daemon settings.   Providing the server IP directly does not work either. 

### Project version(s) affected

2.1.0.3

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood,please reopen it with more information.
