### ISSUE TITLE
Feedback for: engine/userguide/networking/work-with-networks.md

### ISSUE THREAD

**Issue by BSCheshir** [docker/docker.github.io#97]
URL: engine/userguide/networking/work-with-networks.md

"$ docker run -d --name redis_db --network multihost redis

ERROR: Cannot start container bc0b19c089978f7845633027aa3435624ca3d12dd4f4f764b61eac4c0610f32e: container already connected to network multihost

$ docker rm -f redis_db

$ docker network disconnect -f multihost redis_db

$ docker run -d --name redis_db --network multihost redis

7d986da974aeea5e9f7aca7e510bdb216d58682faa83a9040c2f2adc0544795a"

use unknown network multihost

**Comment by mstanleyjones** [comment]
Hi there. Thank you for your feedback. This is the repository for Docker documentation work. The commands you have run are correct and when you ran the final `docker run` command, you did get a container ID returned, so that means the container did start correctly the second time. Perhaps the old container `bc0b19c089978f7845633027aa3435624ca3d12dd4f4f764b61eac4c0610f32e` had not cleaned up all its endpoints correctly when it exited. If you need support with your Docker installation or feel that you are encountering a bug, please file a support request with Docker or file an issue in https://github.com/docker/docker/issues.

**Comment by BSCheshir** [comment]
@mstanleyjones I tell about the quoted example. This example will not working with previous.

**Comment by mstanleyjones** [comment]
I'm sorry, I'm not understanding your previous comment. Your final command in the quoted example did work, as it returned the container ID.

**Comment by BSCheshir** [comment]
I'm sorry too, I wrote very short message. Again :( This happens because English is not my native language.
So... The example page https://docker.github.io/engine/userguide/networking/work-with-networks/#disconnecting-containers tell about isolated_nw, not multihost. Part about redis and multihost from another Earth :)
I reread page and look at source code, are identical. I think need example like 
```
$ docker run --network=isolated_nw -itd --name=container3 busybox

ERROR: Cannot start container bc0b19c089978f7845633027aa3435624ca3d12dd4f4f764b61eac4c0610f32e: container already connected to network isolated_nw

$ docker rm -f container3

$ docker network disconnect -f isolated_nw container3

$ docker run --network=isolated_nw -itd --name=container3 busybox

7d986da974aeea5e9f7aca7e510bdb216d58682faa83a9040c2f2adc0544795a
```
(id may be not valid)
