### ISSUE TITLE
Kubernetes on docker Desktop: How do you ssh to the docker-desktop node?

### ISSUE THREAD

**Issue by MaurGi** [docker/docker.github.io#9847]
File: [docker-for-windows/wsl-tech-preview.md](https://docs.docker.com/docker-for-windows/wsl-tech-preview/)

```
$ kubectl get nodes                   
NAME             STATUS   ROLES    AGE   VERSION
docker-desktop   Ready    master   37m   v1.15.5
```

with minikube, I can run `minikube ssh`  - how do I do that with Docker Desktop kubernetes?

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood,please reopen it with more information.

**Comment by DamianFekete** [comment]
```
docker run -it --rm --privileged --pid=host justincormack/nsenter1
```
From https://stackoverflow.com/questions/55378663/equivalent-of-minikube-ssh-with-docker-for-desktop-kubernetes-node

**Comment by jerrylususu** [comment]
> ```
> docker run -it --rm --privileged --pid=host justincormack/nsenter1
> ```
> 
> From https://stackoverflow.com/questions/55378663/equivalent-of-minikube-ssh-with-docker-for-desktop-kubernetes-node

Just a quick tip for anyone trying to find files / folders mounted to the pods, the equivalent of `/` on the node can be found in `/containers/services/docker/rootfs/`. (Source in the same Stack Overflow link)
