### ISSUE TITLE
 failed to redirect to the specific docker image container

### ISSUE THREAD

**Issue by mahtabriz** [docker/docker.github.io#9952]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

**Comment by lena-larionova** [comment]
Unfortunately, that doesn't give us much info to work with. Can you please provide more information about the issue?

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information
