### ISSUE TITLE
Page identifies DTR 2.4 as latest version

### ISSUE THREAD

**Issue by cemckenzie** [docker/docker.github.io#9965]
File: [datacenter/dtr/2.4/guides/index.md](https://docs.docker.com/datacenter/dtr/2.4/guides/)

**Comment by lena-larionova** [comment]
What do you mean? I know the version selector has the version that you're on visible, but I don't see it labelled as "latest". When I open the drop-down, it shows 2.7 as the latest for me. 

We can't really have 2.7 display as the default visible version in the drop-down, since it wouldn't be selectable. I could add something to the text identifying the latest version though, if that helps?

**Comment by KoryKessel-Docker** [comment]
Edited the header .html file to better indicate that the version therein is a previous version and to also clarify the means for accessing the current version and other previous versions.
