### ISSUE TITLE
exec command documentation does not mention exit code

### ISSUE THREAD

**Issue by westgate** [docker/docker.github.io#9972]
File: [engine/reference/commandline/exec.md](https://docs.docker.com/engine/reference/commandline/exec/)

the docker exec command does not mention what is returned by the exec command. it appears to be the result of the executed command.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline

If you're asking about the exit code, you can check the man page, https://github.com/docker/cli/blob/master/man/src/container/exec.md
